- .gitignore
- bayesianfuncs.py
- chatcommunicate.py
- datahandling.py
- excepthook.py
- globalvars.py
- parsing.py
- spamhandling.py
- utcdate.py
- ws.py
This commit restructures the code. Almost all code was stored in ws.py
before so it became kind of a mess. Now the code is split up in multiple
files.
> Restructured code

- bodyfetcher.py
- excepthook.py
- findspam.py
- ws.py
Get post bodies and run regexes on them.
> Fetch bodies

- findspam.py
I *believe* this is the correct way to do this.. Figured I'd give it a try ;)
> +bodybuilder

- findspam.py
http://chat.meta.stackexchange.com/transcript/message/3185215#3185215
> Add "mytechlabs" to the list of bad websites.

- findspam.py
More Info: http://chat.stackexchange.com/transcript/message/20650581#20650581
> Adds several common spam domains detected by Zephyr

- findspam.py
Adds a domain that was common in March 2015 to blacklisted sites
> March 2015 spam urls

- chatcommunicate.py
Increase link text size because the chat action icons obscure the link
on my monitor
http://meta.stackexchange.com/questions/252888/chat-message-actions-obscure-links-at-end-of-line
...
> Increase link text size

- findspam.py
More details: http://chat.stackexchange.com/transcript/message/21888796#21888796
> Updates black listed websites with most common spam URLs from May 2015

- findspam.py
Including TLDs didn't seem necessary for these.
> two more domains that appeared more than once

- findspam.py
New keywords from last night; prinenidz was particularly active, and not detected automatically:
http://stackexchange.com/search?q=prinenidz
> +prinenidz and a few more

- findspam.py
> +aoatech +pharaohtools

- findspam.py
* menintalk is a spammy website with a wide reach
* Pure Testo Xplode appeared in several posts
* a few other recent spam websites
> +menintalk and others

- findspam.py
- menshealth was spamming today
- "poker online" (also appeared today) is an extremely spammy topic; it may appear legitimately but is worth investigation even then. Poker.SE is not so active, and spam sometimes survives there for years.
> +menshealth +pokeronline

- findspam.py
Keywords from last night, and more general website matching approach
> more websites, keywords

- findspam.py
*  Added Profactor T 
* Generalized fatburn pattern; it's reliably spam when used in site domain. Same for topcare.
> +profactor, better fatburn

- findspam.py
* new products: oro lift, ultra ketone
* moved skincare to no-word-boundaries, because it's now used in domain name
* fixed "testo" regex so that "contesto" doesn't trigger on Italian.SE
* better male enhancement
What will spam filters think of this message is anyone's guess...
> +oro lift, ultra ketone, better skin care

- findspam.py
A few new things showed up today.
New pattern: corrupt|repair on blogspot.
> today's crop of sites and products

- chatcommunicate.py
@JonClements has been begging for a tea command for weeks.
Latest example: http://chat.stackoverflow.com/transcript/message/25094228#25094228
> Added a tea brew command

- globalvars.py
I added some more regulars to the smokey list:
- josilber
- cimmanon
- Mogsdad
- Lynn Crumbling
- Rizier123
> Added some more regulars to the smokey list

- findspam.py
Because of this spam: http://stackoverflow.com/a/32273815
> Added onlinegiftdeal.com

- bayesian/bayes.py
- bayesian/classify.py
- bayesian/learn.py
- bayesian/reset.py
- bayesian/status.py
- bayesian/testharness.py
- bodyfetcher.py
- chatcommunicate.py
- continuousintegration.py
- findspam.py
- globalvars.py
- parsing.py
- spamhandling.py
- test/test_srccheck.py
So I'm told that %-formatting is officially a thing that should not be
used in new code(tm), and I figured this was a half-decent way to
acquaint myself with the codebase.
> Change %-formatting to {}-formatting

- README.md
I had to ask, so I figured others will be similarly demented from time to time.
> README.md: Link to wiki for doco

- findspam.py
http://meta.stackoverflow.com/a/306431/578411
> blacklisted eximiussoftsolutions.com

- findspam.py
Added "Retrodynamic Formula" per http://i.imgur.com/8mCxEaY.png which smokey missed.
> Added new keyword

- findspam.py
Updated the passport regex to match http://i.imgur.com/RUZvfWJ.png and added a missing comma.
> updated regex

- globalvars.py
http://chat.meta.stackexchange.com/transcript/message/4113940#4113940
> added robert longson for the tavern on the meta

- chatcommunicate.py
> Add reply-squelch option to notify and unnotify commands.

- globalvars.py
> add JAL to priviledged users

- chatcommunicate.py
**Warning: untested!**
Per [Braiam's feature request](http://chat.meta.stackexchange.com/transcript/message/4166606#4166606), The `!!/why` command will now tell who manually reported a post and in what forum.
> Adding `why` data for reported posts.

- globalvars.py
http://chat.meta.stackexchange.com/transcript/message/4197216#4197216
> add chmod 666 telkitty to mse tavern users

- globalvars.py
http://chat.stackoverflow.com/transcript/message/27021409#27021409
> add Thaillie to socvr privileged users

- globalvars.py
He's already in for the Tavern, but HQ is much nicer for spam busting. It's less chitchat. :)
> Adding Robert Longson to Charcoal HQ too .

- globalvars.py
http://chat.stackoverflow.com/transcript/message/27172788#27172788
> added approxiblue  for SOCVR

- globalvars.py
http://chat.stackoverflow.com/transcript/message/27253234#27253234
> added cerbrus to SOCVR room

- globalvars.py
http://chat.stackoverflow.com/transcript/message/27284524#27284524
> add Tim Castelijns to SOCVR priviledged users

- findspam.py
http://chat.meta.stackexchange.com/transcript/message/4312923#4312923
> blacklisted  resumewritingservicecleveland.us

- globalvars.py
Changed user 3956566's display name from **MrsEd** to **Ms Yvette** since she changed her display name on SE.
> Changed user 3956566's display name

- bodyfetcher.py
Explicitly report errors and glitches.
> Better exception handling around quota_remaining

- globalvars.py
> add Alexender O'Mara

- globalvars.py
I would like to be allowed to write `sd tp` :-)
> Added myself as a privileged user

- bodyfetcher.py
Try and get a better idea about the false rollover glitch.
> Always report zero quota

- chatcommunicate.py
Searching for "quota" should return (most) quota messages. :)
Plus one bit of missing punctuation.
> More "SEO" quota report for easier chat search.

- globalvars.py
> added praveen Kumar

- chatcommunicate.py
- test/test_chatcommunicate.py
Better grammatical correctness in some of the lesser-seen messages.
> Chat grammar

- globalvars.py
http://chat.stackoverflow.com/transcript/message/28359042#28359042
> added intboolstring to SOCVR priviledged users

- LICENSE-APACHE
- LICENSE-MIT
- README.md
We got all necessary signatures on #129. Let's do this. 
Closes #129
> Relicense to dual MIT/Apache-2.0

- findspam.py
Reported in Teachers' Lounge by TimB.
> +unstopableshrine.webs.com

- ws.py
Requested by Money mod Joe Taxpayer in Teachers' Lounge
> Add money report room

- globalvars.py
http://chat.stackoverflow.com/transcript/message/28535513#28535513
> added Magisch to socvr

- globalvars.py
http://chat.stackoverflow.com/transcript/message/28671889#28671889
> added bhargav-rao for SOCVR

- globalvars.py
http://chat.stackoverflow.com/transcript/message/28737794#28737794
http://chat.stackoverflow.com/transcript/message/28737741#28737741
> added tushar and Ferrybig for SOCVR

- findspam.py
https://metasmoke.erwaysoftware.com/post/17813
> Add sexuallubricants to the blacklist

- globalvars.py
https://chat.stackoverflow.com/transcript/message/28889824#28889824
> Add Petter Friberg to SOCVR

- globalvars.py
Adding my user IDs.  Fixed version of #145.
> adding JAL to chat.SE and c.mSE

- findspam.py
https://metasmoke.erwaysoftware.com/search?body=aminoprimexl.com&commit=Search
> Add aminoprimexl.com to the blacklist

- findspam.py
Increase catch rate for spam related to `Push Money App`
https://metasmoke.erwaysoftware.com/search?body=Push+Money+App
> Add `Push Money App` to the blacklist

- chatcommunicate.py
Having this shortcut is a good idea because this allows us to mark the not an answer posts quicker. 
Related:
https://chat.stackexchange.com/transcript/message/28151263#28151263
> Add shortcut `n` that runs `naa-`

- globalvars.py
http://chat.stackoverflow.com/transcript/message/29456409#29456409
> Added Ian to SOCVR

- findspam.py
Keyword regex on `Volive( Solutions)?`.
> +Volive Solutions

- findspam.py
https://metasmoke.erwaysoftware.com/search?body=educba.com
> +educba.com

- globalvars.py
http://chat.stackexchange.com/transcript/message/28856620#28856620; privileged in SOCVR
> +Wai Ha Lee to CHQ

- findspam.py
because of this ```http://stackoverflow.com/a/37310469/```
> freenom added

- bodyfetcher.py
- chatcommunicate.py
- spamhandling.py
This updates calls to `handle_spam`, `check_if_spam`, `post_message_in_room` and `handle_commands` to use named parameters instead of positional parameters.
> Adds named args to several function calls

- globalvars.py
http://chat.stackoverflow.com/transcript/message/31120881#31120881
> added Eric D for SOCVR

- chatcommands.py
- globalvars.py
- helpers.py
- ws.py
> Allow easy changing of SmokeDetector name and repository with environment variables

- findspam.py
Changed the regex for nigger so it will catch nigger, nigga, and now niggur.
See [this](http://chat.stackexchange.com/transcript/message/31246377#31246377) and [this](http://chat.stackexchange.com/transcript/message/31248637#31248637) for more context.
> Added new regex for nigger

- globalvars.py
Hope this is the correct way to request privileges. I've been in the SOCVR for a few months now, 3k+ rep, looking to help cleanup the site.
> Add FrankerZ to privileged list for SOCVR

- findspam.py
http://chat.stackexchange.com/transcript/message/31565079#31565079
> +readyscript.ru

- globalvars.py
Already privileged in SOCVR, Long time Member of SOCVR
> Added Kyll from SOCVR to Charcoal HQ List

- findspam.py
Blacklist requested by Ashish Ahuja @ http://chat.stackexchange.com/transcript/message/31739463#31739463
> new website blacklist: bigclasses.com

- findspam.py
See [this](m.erwaysoftware.com/posts/by-url?url=//stackoverflow.com/a/39014373). Metasmoke appears to be down ATM so you may not be able to access the link.
> Added 'you scum' to offensive regex

- findspam.py
Has been used to spam:
iqdermaessentials.com -> https://metasmoke.erwaysoftware.com/post/37624
> +1 new blacklisted website

- globalvars.py
> + JanDvorak for SOCVR

- globalvars.py
Has been around for a while. Has read the guidance posts and talked to members. I think its safe to let him feedback.
> Added Oldskool to Charcoal HQ

- globalvars.py
I'm just adding myself to The Tavern as well, so I can give feedback there too.
I also added some spaces so that all of the comments line up nicely :)
[Chat.meta.se profile for reference](http://chat.meta.stackexchange.com/users/285368/angussidney)
> Added angussidney to tavern

- findspam.py
See:
- http://chat.stackexchange.com/transcript/message/31975133#31975133
- https://metasmoke.erwaysoftware.com/post/38690
I added `makehimmine.com.au` to blacklist and 'Dating Coaching' to the bad keywords
> +makehimmine.com.au

- findspam.py
https://metasmoke.erwaysoftware.com/post/38744
http://ru.stackoverflow.com/q/560832/
> Blacklist shopicheck.com

- findspam.py
https://metasmoke.erwaysoftware.com/post/39415
> + hivimoore.com

- findspam.py
See http://chat.stackexchange.com/transcript/message/32138264#32138264 and http://chat.stackexchange.com/transcript/message/32138350#32138350
> +soundmagic.us

- findspam.py
See:
- https://metasmoke.erwaysoftware.com/post/39744
- Multiple other occurrences today, from 4 different spam accounts
> +  raybiztech.com

- findspam.py
Heaps of spam on 3d printing, and we aren't detecting it all. 10 posts and counting.
> +cegonsoft (URGENT)

- findspam.py
Link appeared here: https://metasmoke.erwaysoftware.com/post/41896
> Blacklisted website fixmyprinter.com

- findspam.py
See [here](https://metasmoke.erwaysoftware.com/post/42093) and [here](https://metasmoke.erwaysoftware.com/post/42096).
> +samedaypros.com

- findspam.py
https://metasmoke.erwaysoftware.com/post/42110
> Blacklisted website excelpasswordremover.com

- findspam.py
https://metasmoke.erwaysoftware.com/post/42127
> Blacklisted website seyf-educ.com

- globalvars.py
clearance from Tiny and myself
http://chat.stackoverflow.com/transcript/message/33206318#33206318
> added Andrew L. for socvr privs

- findspam.py
https://metasmoke.erwaysoftware.com/post/42140
https://metasmoke.erwaysoftware.com/post/42131
https://metasmoke.erwaysoftware.com/post/41846
> Blacklisted few websites

- findspam.py
https://metasmoke.erwaysoftware.com/post/42243
> +fluffypancakerecipe.com

- blacklisted_websites.txt
Appeared twice: 
https://metasmoke.erwaysoftware.com/post/42684
https://metasmoke.erwaysoftware.com/post/42685
> +textmonster.in

- findspam.py
- test/test_spamhandling.py
This is fairly prevalent in recent spam, and recently one instance was missed.
> URL repeated at end of long message

- blacklisted_websites.txt
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=uflysoft&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search not currently caught.
> Added uflysoft.com to the blacklist

- blacklisted_websites.txt
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=sea59.com&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> Twice used now, not caught

- blacklisted_websites.txt
reject or accept this at your convenience Art or Undo, I just thought the file doesn't need to contain these anymore.
> Removed dummy values added by testing of the !!/blacklist command

- globalvars.py
Has been privileged in SOCVR for a long time.
> Putting in Triplee in Charcoal HQ.

- blacklisted_websites.txt
> Removing test values from blacklisted_websites.txt

- globalvars.py
Profile link for reference: http://chat.stackexchange.com/users/128113
> Added 'arda' to privileged list in Charcoal

- blacklisted_websites.txt
Proactively reduce the risk of false positives, and make it more similar to the ones
immediately after.
> Tighten regex for blacklisted site sh.st

- gitmanager.py
Like everywhere else in the code, we need to cope with Unicode in user names.
> git user name is a Unicode string

- bad_keywords.txt
Common supplement name. Recently started changing domains again so they wouldn't be caught.
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=maxtropin&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> Blacklisting "maxtropin"

- ws.py
> ws.py: Add a configuration for the Magento room

- findspam.py
[Wingding just used the name "w1ngd1ng."](http://m.erwaysoftware.com/posts/by-url?url=//stackoverflow.com/a/40499116)  I changed the regex from `wingding` to `w[i1]ngd[i1]ng`.
> Blacklist "w1ngd1ng"

- bad_keywords.txt
Not currently caught in relevant filters.
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=Titanium+Backup&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> Has been used to spam 5 times now

- bad_keywords.txt
Better remove it from the BL for now.
> According to moderators on A.SE it seems to ... actually have uses.

- findspam.py
A recent post by a well-known troll was missed.  Extend the regex to hopefully cover future variations.
> findspam.py: Extend regex for w.ding

- bad_keywords.txt
To help track some more elusive one-off spams.
> According to Angussidney's suggestion

- bad_keywords.txt
53 hits overall, about a dozen in the last month; a spam earlier today almost evaded detection (only got caught for blacklisted web site, which is obviously brittle)
> bad_keywords.txt: add "booty pop"

- findspam.py
As requested by [Wrzlprmft](http://chat.stackexchange.com/users/68718) here:
http://chat.stackexchange.com/transcript/message/33819862#33819862
> findspam.py: alert for image from low-rep users

- chatcommands.py
- metasmoke.py
This will allow users to reply to a report to determine whether or not it has been autoflagged.
Also, by the looks of it, I can no longer push to master, I have to make a pull request. I believe this will break the blacklisting commands.
> Add autoflagged? subcommand

- bad_keywords.txt
This never detected anything, and after 20 days, the troll seems to be gone.
Background (10k+): http://meta.stackoverflow.com/questions/338781/how-to-raise-awareness-of-a-user-attempting-to-post-multiple-similar-terrible-q
Reverts commit: https://github.com/Charcoal-SE/SmokeDetector/commit/eb94b2e2fd9af1ccd374610842eb04a62964826c
> Remove SHA1 from eb94b2e2fd9af1ccd374610842eb04a62964826c

- bad_keywords.txt
Prevalent in recent spam, not included in the bad_keywords list.
> bad_keywords.txt: add "testabolan"

- metasmoke.py
I forgot to give the URL argument to the route, hence smokey throws an error when you try to use the `autoflagged?` command
> It might help to pass the command a URL

- bad_keywords.txt
Suggested by tripleee on chat: http://chat.stackexchange.com/transcript/message/34415527#34415527
> Upgrade 'testo' regex

- bad_keywords.txt
"fifaodell" No hits in MS -> https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=fifaodell&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
"brianfo" No hits in MS -> https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=brianfo&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
"baba ji" No recent hits with this one, updated it to be more reflective (with \W? it matches some TP's from 3 months ago)
"bajotz" No hits in MS -> https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=bajotz&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
"kolcak" No hits in MS -> …
> Remove old cruft from Bad_Keywords.txt

- blacklisted_websites.txt
Cutoff Point 8 months since last TP.  All websites affected are checked in regex and in plain on MS
-----------------------------------------------------------------------------------------------------
"Online ?Kelas" No hits in MS, doesn't appear to be a Website -> https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=online+%3Fkelas&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
"careyourhealths" No hits in MS -> https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=careyourhealths&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
"wowtoes" a single TP in MS, over a year ago -> https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&bod …
> Removing old cruft from Blacklisted_Websites.txt

- blacklisted_websites.txt
Remove duplicate and triplicate entries from blacklisted_websites.txt
> Fix duplicate URL blacklist entries

- bad_keywords.txt
24 TP matches / 0 FP matches in the last 4 months.
Thanks to triplee
> Thanks to @triplee, Matches more tps, no fps

- blacklisted_usernames.txt
T'was an error in using the command.
> Fixing error from command

- chatcommands.py
see http://chat.stackexchange.com/transcript/message/34852020#34852020 for reference
Wrong exception was being caught
> Should be an indexerror not a valueerror

- globalvars.py
Already privileged in SOCVR, active in MS
> Adding Cerbrus to Charcoal HQ

- findspam.py
Reduce FP rate from 18/37 to 10/29, including all the recent FPs.
Monologue at http://chat.stackexchange.com/transcript/message/35175862#35175862
> Exempt video.SE from black magic rules

- bad_keywords.txt
- blacklisted_websites.txt
nucific by Glorfindel:
http://chat.stackexchange.com/transcript/11540?m=35189068#35189068
fblikes:
http://chat.stackexchange.com/transcript/11540?m=35189068#35189068
> Pending blacklisting requests

- blacklisted_websites.txt
[Blacklisted assignment help websites](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=assignmenthelp) (!!/blacklist-keyword isn’t working ATM)
> Blacklisted assignment help websites

- bad_keywords.txt
HL Slim matches more than HL Slim Pro, at the cost of zero extra FPs (checked on SE itself as well)
> HL Slim Pro -> HL Slim

- findspam.py
Blacklisting nazi(s) on SciFi as per [moderator request](http://chat.stackexchange.com/transcript/message/35247701#35247701)
> Blacklisting nazi(s) on SciFi as per moderator request: 

- blacklisted_websites.txt
See https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=amazfitpace
> amazfitpace uses more TLDs

- globalvars.py
Confirm or Deny at your Leisure
> Adding CaffeineAddiction to CHQ

- bad_keywords.txt
https://metasmoke.erwaysoftware.com/search?utf8=✓&title=&body=testo+ultra
> Testo Ultra appears in a few posts just under the default autoflagging threshold

- bad_keywords.txt
7 TPs: https://metasmoke.erwaysoftware.com/search?utf8=✓&title=&body=gladiator
> Trying to catch new flashlight brands

- chatcommands.py
This should fix the problem.  Oops it went to Deploy not Master.
> Fix 'CHQ msg deletion on false positive' problem. (fixes #548)

- globalvars.py
Adding [FelixSFD](http://chat.stackexchange.com/users/248139/felixsfd) to privilege list in Charcoal. Nearly 3k on SO, 4k+ helpful flags on SO. He has read the wiki list apparently too.
> add @FelixSFD to charcoal priv list

- findspam.py
Updated two methods which work on major spam targets - the list of sites was a little outdated.
> Updated two methods which work on major spam targets

- findspam.py
See this search:
https://metasmoke.erwaysoftware.com/search?utf8=✓&title_is_regex=1&title=&body_is_regex=1&body=sourceforge%5C.net%5B%5Cw%2F%5D*convert&commit=Search
The last true positive was in 2015
> This hasn't gotten a true positive in over a year

- blacklisted_websites.txt
https://metasmoke.erwaysoftware.com/search?utf8=✓&title=&body=remosoftware
> Remove blacklisted website which has 0 TP / 1 FP on metasmoke

- Dockerfile
Added docker file for creating a cross platform development environment
> Added dev environment Dockerfile

- globalvars.py
approved by me
http://chat.stackoverflow.com/transcript/41570?m=35838367#35838367
> added FelixSFD as socvr privileged user

- bad_keywords.txt
- blacklisted_websites.txt
- Blacklisted leuxiaavis\.fr
- Cleanup bad keywords
> - Blacklisted leuxiaavis\.fr

- bad_keywords.txt
> Blacklist Renuglow

- bad_keywords.txt
... and an attempt to catch some of the posts by this user: http://meta.mathoverflow.net/q/3124/70594
He leaves his links in comments, so that they're harder to detect. [Here](https://metasmoke.erwaysoftware.com/search?utf8=✓&title=&body=favorite+Riemann+zeta+function) are two hits and I'm sure I've seen another one on MathOverflow in the past two weeks.
> Blacklist additions

- blacklisted_websites.txt
Requested here: http://chat.stackexchange.com/transcript/message/36029817#36029817
> Blacklist galexclusive\.com --autopull

- blacklisted_websites.txt
As suggested in the discussion after this comment:
http://chat.stackexchange.com/transcript/message/36030507#36030507
> blacklist vk\.com/lpanasenko1 --autopull

- blacklisted_websites.txt
Suggesting this after two spam answers that included this url https://metasmoke.erwaysoftware.com/post/60691 and https://metasmoke.erwaysoftware.com/post/60693
> Add apktrusted.com to blacklist

- blacklisted_websites.txt
So in the past few days I've been slowly uncovering some subtle spam here. In particular:
- User http://stackoverflow.com/users/1353441/alexandresaiz had been editing this into tag wikis, inappropriately tagging questions, inappropriately posting comments, and spamming it in answers. That account has subsequently been temporarily suspended.
- User http://stackoverflow.com/users/5444431/dmitriy-nevzorov is probably about to be temporarily suspended. That user had been spamming MoonMail in answers to but it turns out, according to his profile, he also works for that company.
Even though most of the spam has been tag/comments, and account suspensions + my own cleanups have been taking care of this there's a couple answers here and there, and this site I think is worth looking out for at …
> Moonmail.io added, see comment

- bad_keywords.txt
> Blackilst keyword zilotrope --autopull

- README.md
> Py2 requirement in README

- findspam.py
https://chat.stackexchange.com/transcript/message/36147676#36147676
> Revert "Blacklisting nazi(s) on SciFi as per moderator request: "

- blacklisted_websites.txt
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=csoftpro.com&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> 5 TP / 0FP / 0 Mentions on SE

- .travis.yml
Be sure to add any other files we want coverage on: simply do `--cov=<module name>` on `pytest`
> Added codecov support

- bad_keywords.txt
... not to be confused with 'test blacklist revert'.
> revert blacklist test

- blacklisted_websites.txt
https://metasmoke.erwaysoftware.com/search?body=couchsurfing
> Unblacklist couchsurfing\.com (8 FPs, 0 TPs)

- findspam.py
Context: http://chat.stackexchange.com/transcript/message/36231859#36231859
> Blacklisted city "noida" after some undetected spam

- globalvars.py
> SOCVR privileges for  henders

- globalvars.py
http://chat.meta.stackexchange.com/transcript/message/5902434#5902434
> added Mithrandir for privileges in Tavern

- ws.py
http://chat.stackexchange.com/rooms/56223/the-spam-blot as discussed here:
http://chat.stackexchange.com/transcript/message/36356365#36356365
> add graphicdesign.SE room for alerts

- ws.py
Reverts Charcoal-SE/SmokeDetector#621, refer to comments on the original issue.
> Revert "add graphicdesign.SE room for alerts"

- globalvars.py
approved by me http://chat.stackoverflow.com/transcript/message/36538913#36538913
> added Kayess to SOCVR

- blacklisted_websites.txt
https://metasmoke.erwaysoftware.com/search?body=usefulpcguide
> Unblacklisted usefulpcguide.com (7 FPs, 0 TPs)

- findspam.py
Add celebritynetworth.org and thecelebritynetworth.com to pattern-matched websites
> Add celebritynetworth.org and thecelebritynetworth.com to pattern-matched websites

- findspam.py
(also made sure the recent additions are detected in questions as well)
> Added surl.cn.com as link shortener

- findspam.py
celebrity prefix is optional, add optional dashes to capture new variant.
https://metasmoke.erwaysoftware.com/post/64148
> findspam.py: Refactor net-worths.net regex

- chatcommunicate.py
> Adding naa emoji alias

- bad_keywords.txt
Reduce occurrences of "alpha" and "supplements" to one big regex each,
and remove duplicates for "krojamsoft" and "nitric muscle"
> bad_keywords.txt: Refactor repeating phrases

- bad_keywords.txt
bad_keywords.txt: Minor refactoring to reduce duplication
> merge primalx and primal\Wx

- globalvars.py
based on http://chat.stackoverflow.com/transcript/message/36730045#36730045
approved by me
> added Machavity to SOCVR priv users

- bad_keywords.txt
- blacklisted_websites.txt
Regression: !!/blacklist-keyword command added a spurious empty line.
https://github.com/Charcoal-SE/SmokeDetector/commit/d3d8c34
> bad_keywords.txt, blacklisted_websites.txt: remove empty lines

- bad_keywords.txt
Refactored skin\Wnovela to also cover this.
> blacklist eye\Wnovela

- bad_keywords.txt
Required some refactoring.  I can't believe this wasn't already blacklisted.
(There are about five false positives, Skeptics / Health / Meta; but the volume
of spam easily outweighs the tiny risk.)
Metasmoke TP rate 1190/1193 currently:
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=fitwaypoint&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> blacklist male\Wenhancement

- globalvars.py
He's been here for a while. Consulted an Admin: http://chat.stackexchange.com/transcript/message/36937548#36937548
> Adding CalvT to CHQ

- bad_keywords.txt
allow \W?x after titanium\W?pro
> fixup recent blacklist addition

- blacklisted_websites.txt
Remove duplicates (fitwaypoint|flashcomindonesia|maxhealthtips)\.com from blacklisted_websites.txt
> Remove blacklist duplicates

- blacklisted_websites.txt
Many FP hits and many of the TP hits appear to be questionable, actually.
18/28 with TP feedback but several of those are from users who also have FP and/or NAA feedback, and a number of acceptable answers on other topics.
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=bsscommerce.com&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> Remove bsscommerce\.com from blacklist

- globalvars.py
Request by Angus in chat.
http://chat.stackexchange.com/transcript/message/37154740#37154740
> Add Hyper Neutrino to privileged users in Charcoal

- bad_keywords.txt
Fixup empty line left after [PR#704](https://github.com/Charcoal-SE/SmokeDetector/pull/704)
> fixup empty line left after soma\W?biotix PR

- findspam.py
Add Sri Lanka with some variants to the slightly misleadingly named city_list
> findspam.py: Add Sri Lanka to place names

- blacklisted_websites.txt
Quick tests from earlier today.
Commits faf2269ec70a55a517801e5b06dfe436fa4cc51d
and 2b191dbc1dcef3ae01e54a1c2e967ef758179206
> remove andy-testing-stuff commits

- findspam.py
Recent Apple support phone number spam
> findspam.py: add Apple to businesses

- blacklisted_websites.txt
Wrong TLD in commit ffb6f7e0ccc5aa0048fea08c63aa18c033d08b21
> revert hairlosspropecia.com

- chatcommands.py
Please make sure this works, as I’m not at a desktop to test.
> Add a better !!/status response with hours and days

- blacklisted_websites.txt
Commit 0af62f4db3e3075235c503204999a440ef9f5774 introduced a duplicate
> blacklisted_websites.txt: remove duplicate elliskinantiaging\.com

- findspam.py
Add Rohini to Indian place names
> findspam.py: Add Rohini to city_list

- blacklisted_websites.txt
Commit ac959850989b3c415ba8206dd5662ed80284f225 introduced a duplicate
> blacklisted_websites.txt: remove duplicate growmewise\.com

- bad_keywords.txt
Commit 54baca5bfdba88136f8ccd2c1263c39a017b0f27 introduced a duplicate
> bad_keywords.txt: remove duplicate staminon

- gitmanager.py
Don't blacklist if something is already blacklisted
> gitmanager.py: Add duplicate check

- blacklisted_websites.txt
Both spammed at same time as the other two
> Add .com & .ng to garanntor

- chatcommands.py
Let’s not try to mutate immutable objects.
> Better status command, part II

- test/test_chatcommunicate.py
> Add a few tests

- bad_keywords.txt
Allow for punctuation as well as whitespace between words.
> bad_keywords.txt: extend Long Path Tool expression

- globalvars.py
HyperNeutrino requested adding to Tavern [here](https://chat.stackexchange.com/transcript/message/37299132#37299132)
> +HyperNeutrino to Tavern

- globalvars.py
> SOBotics privileges

- chatcommands.py
Adds support for `!!/whois` with the option of either specifying `admin` or `codeadmin`
> Adds WHOIS command

- bad_keywords.txt
Tidy up some recent additions.
> Blacklist cleanup

- chatcommands.py
- findspam.py
- gitmanager.py
- watched_keywords.txt
Matches on this keyword list will trigger a rule "potentially bad keyword" which is separate from "bad keyword" and is intended to have a lower barrier than outright blacklisting.
Basically, if you want to be alerted when "something" comes up, Smokey can now do that.
Items on the watched keyword list are annotated with a date stamp to allow an administrator to prune the list periodically (down the line we might want to add code to do this automatically, too).
> Add a !!/watch-keyword command

- chatcommands.py
Improve the help message to let users see which roles are available.
> !!/whois: for unknown role, list known roles

- blacklisted_websites.txt
Sorry, typo (correct spelling already added separately)
> -realsupplementsadvisor.com

- bad_keywords.txt
Add an optional non-alphabetic after "hyper".
> hypertone\Wforce: also allow hyper-tone etc

- blacklisted_websites.txt
Is causing more fps than tps, see [here](https://metasmoke.erwaysoftware.com/search?body=imobie.com)
> Remove imobie.com

- watched_keywords.txt
Now blacklisted (commit 1caeed5290a8d030ec5a6a33f9393b9987492470)
> -mp3songsclub\.com

- watched_keywords.txt
This is blacklisted now; remove from watched_keywords.txt
> -vital\Wnutra

- gitmanager.py
If we are properly blacklisting something which exists in the watch list,
remove it from the watch list as part of this commit.
> gitmanager.py: remove from watchlist

- ws.py
Report everything from SciFi.SE
> Add SFF community cleanup room

- metasmoke.py
MS gets to pick the exit code: Reboot or die or pull or etc.
> Add ability for MS to kill the Smokey instance

- blacklisted_websites.txt
tons of missed spam from https://stackexchange.com/users/10712515/alexey-porubay?tab=activity
> cleveroad.com

- blacklisted_websites.txt
- https://metasmoke.erwaysoftware.com/post/69215
- http://m.erwaysoftware.com/posts/by-url?url=//askubuntu.com/a/920428
- http://m.erwaysoftware.com/posts/by-url?url=//superuser.com/a/1173555
- http://chat.meta.stackexchange.com/transcript/message/6065565#6065565
Probably others. Additionally network-wide search for "serverdrivers" yielded no *non*-spam results.
Sorry about adding to top of file instead of bottom, but github's inline editor really shits the bed with this file for some reason.
> serverdrivers.com

- blacklisted_websites.txt
- watched_keywords.txt
Collected a number of watch and website blacklistings from last night.
> Morning routine

- globalvars.py
- spamhandling.py
Mark all the "potentially bad keyword in {answer,body,title,username}" rules as experimental. Refactor some of the related code in `spamhandling.py` slightly.
> Watched is experimental

- bad_keywords.txt
- watched_keywords.txt
Mainly adding watches, but one blacklisted keyword as well.
> Morning routine 2017-06-01

- globalvars.py
Nisse Engström added to privileged users --autopull
> Nisse Engström added to privileged users --autopull

- findspam.py
- test/test_spamhandling.py
Adds new character_utilization_ratio function to check if a single character is over used in a post.
Initially only active on judaism.stackexchange.com
> Adds new character_utilization_ratio function to check if a single

- chatcommands.py
- gitmanager.py
> Link to chat message in add_to_blacklist; link to commit in chat reply

- gitmanager.py
`GitManager` expected a different item format when watching instead of blacklisting.  I changed it to format  the new item itself.
I haven't tested it because I accidentally ruined my dev environment, but it should work fine.
> Fix !!/watch

- globalvars.py
https://chat.stackoverflow.com/transcript/message/37758588#37758588
> adding suraj to socvr, approved by me

- chatcommunicate.py
- excepthook.py
This will help greatly when debugging problems like the one we're having with `!!/watch`.
> Add error logging when a command throws an exception

- bad_keywords.txt
- grouped together magic/spell spam
- expanded one of the patterns to match even more TPs by adding `\w*`
> updated spell caster spam

- bad_keywords.txt
- grouped "lost lover" keywords together
- added the "lost love/lover back" pattern
- updated "bring back lost lover" -> "bring back lost love" which has twice as many TPs and includes the former anyway
note that "lost love" on its own is excluded as a pattern
> update "lost lover" matches

- bad_keywords.txt
this regex has no search results ever in MS's history and i'm not sure what it's meant to be doing.
> removed weird mega-regex

- bad_keywords.txt
- consolidated the `skin-*` and `*-skin` keywords
- added a match (`aged skin`)
- overall the two larger regexes cover 161tp/0fp and 796tp/2fp respectively
> updated skin care keywords

- bad_keywords.txt
"teeth lightening" (7tp / 0fp) --> "teeth/tooth lightening/whitening" (75tp/0fp)
> expanded tooth product regex

- blacklisted_websites.txt
- watched_keywords.txt
Batching a number of edits to avoid multiple restarts.
> Morning routine 20170703

- nocrash.py
Hopefully reveal something more about why we are restarting.
> nocrash.py: add errorlog.txt logging

- blacklisted_websites.txt
based off of https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=createspace.com&username=&why=&site=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search - 4tps, 11fps. Maybe worth a !!/watch instead.
> removed createspace.com

- blacklisted_websites.txt
- watched_keywords.txt
Watched website -> blacklist, but slightly more generic
> Blacklist 192-168-1-1.co and 19216811.co

- blacklisted_websites.txt
- watched_keywords.txt
It's only had 3 hits, all from the same user.  I mean to put it on the watchlist, but I'm tired and I did the wrong thing without noticing.
> Switch palyaçom.com from the blacklist to the watchlist

- findspam.py
This is a high-profile support community for the Python web framework Django.
Currently at 0/8 false positives in Metasmoke.
> findspam.py: whitelist djangogirls.org

- findspam.py
Was recently in [this](https://metasmoke.erwaysoftware.com/post/77423) spam post
> Add 'investment' to pattern-matching email

- chatcommunicate.py
We have a couple cases where message history on deleted messages are pulled, and trigger 404 errors that may lead to harder crashing where they aren't captured proper.
Thus, let's add some 404-error protection for message history 404 errors.  If such an error happens we return nothing.  If it's any other type of 404 error in the message handling, raise that error.
> Better handle history 404 errors, so we don't have to trigger an error.

- blacklisted_usernames.txt
was a test in the first place, doesn't need to be there anyway
> -angussidneh from blacklisted usernames

- globalvars.py
per [this](https://chat.stackoverflow.com/transcript/message/38793909#38793909) request.  I approve this as an RO
> Adding Makyen to SOCVR

- .pullapprove.yml
Chat link: https://chat.stackexchange.com/transcript/message/39612692#39612692
> .pullapprove.yml: add NobodyNada

- findspam.py
Refactor and (I hope) fix a couple of apparent errors in the long regex.
> findspam.py: bad_link_text(): fix regex

- globalvars.py
as per @ShadowWizard's request: https://chat.stackexchange.com/transcript/message/39931265#39931265
> Add DonQuiKong to Tavern

- globalvars.py
Adding [g00glen00b](https://chat.stackoverflow.com/users/1915448/g00glen00b) to SOBotics. 15k rep, 1k+ flags.
> Add g00glen00b to SOBotics

- nocrash.py
Fail if wrong or unset unless running with no-git-user-check
> nocrash.py: check git user name

- globalvars.py
Creating [this PR](https://github.com/Charcoal-SE/SmokeDetector/pull/1111#issuecomment-333356735) again because I forgot to put the autopull in the title, and now it doesn't merge when a code admin approves it.
> Add Owen Hines to Charcoal (again) --autopull

- chatcommands.py
Help sort out which instance is responding when there are several running
> !!/rev includes !!/location output

- watched_keywords.txt
This entry caused ±10 fps in 48 hours, this is an attempt to reduce that.
> Updated 'hack' watchlist entry to reduce fps

- blacklisted_websites.txt
-homeworkhelponlinefrom blacklist --autopull
> -homeworkhelponline from blacklist --autopull

- bad_keywords.txt
- blacklisted_websites.txt
Some URLs were erroneously put in the keyword blacklist, so I'm moving them to the website blacklist.
> Move URLs to website blacklist --autopull

- watched_keywords.txt
https://metasmoke.erwaysoftware.com/search?body=xtext
> !!/unwatch xtext (8 FPs, 0 TPs in 15 days)

- chatcommands.py
- Don't call force-delete from delete. Instead, just take care
of it then and there.
> Fix sd delete the easy way

- watched_keywords.txt
See https://chat.stackexchange.com/transcript/message/40802909#40802909
> Watchlist entry for codecanyon.net updated

- chatcommands.py
This fixes the index out of range issue caused by #1176.
> Fix index out of range of whois command

- watched_keywords.txt
since watchlist entry (10 days ago): 3tp, 8fp, 1naa 
https://metasmoke.erwaysoftware.com/search?body=cyber&commit=Search
> unwatch "cyber(?!\W*security)"

- globalvars.py
High privilege, lots of helpful flags, making the right noises in the room.
> Add A-J to Charcoal

- watched_keywords.txt
Too many FPs: https://metasmoke.erwaysoftware.com/search?body=purevpn and too high risk, almost 500 hits on StackExchange: https://stackexchange.com/search?q=%22purevpn%22
> !!/unwatch purevpn

- bad_keywords.txt
- blacklisted_usernames.txt
- blacklisted_websites.txt
- watched_keywords.txt
The branch protection effectively broke the git-related commands, so I am starting a PR for the changes I would like to make in the blacklists and watch list.
I can easily add more commits, so if you would like me to include something here, just ping me in [Charcoal HQ](https://chat.stackexchange.com/rooms/11540/charcoal-hq).
> Queueing up git operations while waiting for blacklisting functionality to return

- globalvars.py
Interpersonal / Awkward silence regular
> +Jarko Dubbeldam to Charcoal HQ

- blacklisted_usernames.txt
https://metasmoke.erwaysoftware.com/search?username=support
> Support gives too many FPs

- chatcommands.py
> Add space around nested brackets to un-confuse the chat renderer

- chatcommunicate.py
- metasmoke.py
https://chat.stackexchange.com/transcript/message/41585771#41585771
> Implement fixes for quartata

- rooms.yml
Requested here:
https://chat.stackexchange.com/transcript/message/41660218#41660218
> Add Makyen to CHQ --autopull

- rooms.yml
Request here: https://chat.stackexchange.com/transcript/message/41717252#41717252
Based on visibility lately and high rep, I'd be partial towards bending the rules a bit to allow for a *really* short lurking period.
> Add iBug to Charcoal

- watched_keywords.txt
https://chat.stackexchange.com/transcript/message/41857963#41857963
> remove roll20\.net

- bad_keywords.txt
- watched_keywords.txt
* Remove watch
* Update blacklist
> Update keyword blacklist --autopull

- rooms.yml
Self-request privilege in Tavern. I am already privileged in CHQ.
> +iBug in Tavern on the Meta

- chatcommands.py
- test/test_chatcommands.py
This adds different variants of coffee (eg Cappuccino, Americano, Espresso) just like `!!/tea` to `!!/coffee`
> Add different types of coffee

- watched_keywords.txt
I forgot the backslash in the watch
> add backslash

- bad_keywords.txt
Blacklist `testosterone boosting` and `testo boosting`
> Update bad_keywords.txt --autopull

- findspam.py
Attempt to fix the seemingly missing character at the end of reports like `Title: Position A-B hatever.co` when the actual domain is `whatever.com`.
Also fix `Click Here` not being captured at all.
> Update findspam.py --autopull

- bad_keywords.txt
added 'clinic' and potential omitted space to the regex, and removed a couple of regexes made redundant
> expand herbal regex

- spamhandling.py
Fix bad report text. See [example](https://metasmoke.erwaysoftware.com/post/101823):
```
Blacklisted user - blacklisted for //scifi.stackexchange.com/a/178896 (https://m.erwaysoftware.com/posts/by-url?url=//scifi.stackexchange.com/a/178896) by http:https://chat.stackexchange.com/transcript/11540?m=42267382
^^^^^^^^^^^
```
> Update spamhandling.py --autopull

- bad_keywords.txt
Merge `tryvexan` into `tryvexin`
> Update bad_keyword.txt --autopull

- parsing.py
The fixes the error where some answers get reported as a question. As seen is [this message](https://chat.stackoverflow.com/message/40942991) some characters are added by SE. Therefore, this pull request edits the regex to cover that situation.
Fixes #1428
> Improve regex

- bad_keywords.txt
- watched_keywords.txt
Raiditem was on two lists & improperly represented in one.
> clean up for raiditem

- findspam.py
Let's stop the FP generator:
```
You guys may be interested in parcitipating in Math.SE.
Title - Keyword *interested* with email Math.SE
Post - Keyword *interested* with email Math.SE
```
> Fix bad email pattern --autopull

- rooms.yml
Request [here](https://chat.stackexchange.com/transcript/message/42502674#42502674). Has 677 rep on Stack Overflow and is an active reporter to Natty. The request sounds reasonable.
> +chade_ in SOBotics

- rooms.yml
Already privileged in SOCVR and Charcoal HQ. Would like privs here to reduce some spam down in the SOCVR room, as I'm usually hanging around in the SOBotics room often.
> +FrankerZ in SOBotics

- watched_keywords.txt
`cyberforum.ru` is a legitimate site.
> Update watched_keywords.txt autopull

- chatcommands.py
- datahandling.py
This commit adds the `!!/unnotify-all` command.
>  Add unnotify-all command

- bad_keywords.txt
- findspam.py
bwDraco noticed it's not caught and blacklisted it. IMO this word should better be caught as "offensive keyword" so I'm moving it into the code.
> Migrate "dumbass" from blacklist to offensive

- bad_keywords.txt
Basically just changed `CeluRaid` to `Cell?uRaid`.
> Blacklist "CelluRaid"

- rooms.yml
> +GrumpyCrouton to SOBiotics as requested by @AWegnerGitHub

- bad_keywords.txt
> Remove accidentally added duplicate

- bad_keywords.txt
> +[Richcopy 360] autopull

- watched_keywords.txt
CI failed for duplicate entries
> Remove duplicate

- findspam.py
See [example](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body=www.goo.gl&commit=Search).
> Catch shortened URL starting with www

- bad_keywords.txt
Whoops. https://chat.stackexchange.com/transcript/message/42938054#42938054
> revert blacklist of adderall

- chatcommands.py
See [Mithrandir's idea](https://chat.stackexchange.com/transcript/message/42941763#42941763) and [iBug's idea](https://chat.stackexchange.com/transcript/message/42941771#42941771).
> Shorten "!!/allnotificationsites"

- findspam.py
A new list that could be populated just like "company|facility|etc in india".
> Catch "India Tour"

- findspam.py
"slut" with any number of "t"s, optionally followed by a "y"
> add "slut" to offensive regex

- chatcommands.py
- test/test_chatcommands.py
So in case Smokey misses a post, any privileged user can force it to scan it.
One can also use this command to scan a potential spam without `!!/report`ing it.
> Add !!/checkpost command (mostly complete)

- watched_keywords.txt
3 FPs, no TPs: https://metasmoke.erwaysoftware.com/domains/13389
> !!/unwatch accuwebhosting\.com

- findspam.py
[MS Search](https://metasmoke.erwaysoftware.com/search?body_is_regex=1&body=ur%5B+-%5Dmum)
> Catch "ur mum" as offensive

- rooms.yml
Since he is a regular in SOCVR and seemed to attempt to provide feedback, I offered him privileges.
https://chat.stackoverflow.com/transcript/message/41522202#41522202
> +EJoshuaS to SOCVR

- rooms.yml
- Known from the Tavern and SOBotics
- 6,5k rep on SO
- Generally regarded as sane
Requested here: https://chat.stackexchange.com/transcript/message/43315531#43315531
Approve or deny at leisure
> Adding Princess Luna to CHQ

- chatcommands.py
- test/test_chatcommands.py
Finally, canonically, ultimately,
A solution to #513
> Show reasons that would have been caught for !!/report posts

- bad_keywords.txt
Bad Keywords are case insensitive
> removed duplicate of "nitridex"

- chatcommands.py
> Fix "all blacklisted user" by #1711

- rooms.yml
> Add charcoal Test to rooms.yml

- chatcommands.py
Blame the user of a targeted blame if they provide an invalid user id.
> fix crash on targeted blame

- chatcommands.py
The previous pull was not correct
> move code that causes error into try block

- chatcommands.py
- chatcommunicate.py
- deletionwatcher.py
- spamhandling.py
- tasks.py
- ws.py
> Deletionwatcher refactor

- chatcommands.py
> Use protocol URL in !!/scan command

- chatcommands.py
- spamhandling.py
> Try reducing reason count and keep MS link, close #1737

- bad_keywords.txt
> Remove dbal, close #1757

- test/test_chatcommands.py
I plan to add tests for the new command `!!/scan` and the post analysis in `!!/report`.
~~~When complete, I'll drop the notice in the title.~~~ Completed now and waiting for review/merge.
> Add more tests for newly added features

- .gitignore
That does't belong to the repo, right?
> Ignore deletionIDs.p from .gitignore

- watched_keywords.txt
Last TP is 4 months old, two recent FPs
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=pure+core&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> remove "pure core" watched keyword

- chatcommands.py
A command that we can use to point new users to that explains briefly what Smokey is, without pointing to a list of commands.
> Add welcome command

- chatcommands.py
Fix current error, and add possibility to ping other user with the welcome command
> Add params to welcome, add other user

- chatcommands.py
Hopefully sanitise the welcome other user input - so it removes the @, and only accepts the first word.
> Sanitise welcome input

- chatcommands.py
Here's hoping this is the last one!
> Less characters

- findspam.py
> No need for try/except block

- blacklisted_usernames.txt
Replaces https://github.com/Charcoal-SE/SmokeDetector/pull/1801
> Properly blacklist f**k in usernames

- parsing.py
The URL parsing bug should be ultimately fixed. Some old (failed) attempts are still left in the code. This PR cleans them all up.
> Cleanup missed fixes from #1723

- findspam.py
See [this MS post](http://m.erwaysoftware.com/posts/by-url?url=//ell.stackexchange.com/a/161652).
> Update to better watch for inappropriate (offensive) text drawings

- watched_keywords.txt
Probably should also watch `enhance` as well
Should also catch:
enhance (fe)male fertility
> K.Davis: Watch enhances \W(?:fe)?male\Wfertility

- findspam.py
Inspired by https://meta.stackoverflow.com/q/365215
> Catch "ur gay" and variants

- nocrash.py
See [this post](https://stackoverflow.com/c/charcoal/questions/285) in Charcoal (SO Teams).
> Fix double credential prompt

- metasmoke.py
One-line change; not tested, hopefully I got Python syntax right
> Restrict new user messages

- watched_keywords.txt
Inspired by https://metasmoke.erwaysoftware.com/post/113268
> Extend "X my Y" watch

- watched_keywords.txt
https://metasmoke.erwaysoftware.com/post/113411
Manual PR because MS !!/watch was not functional
> Watch domains from unrecognized spam post

- metasmoke.py
No longer needed, now that MS allows us to silence these messages.
> Revert "Restrict new user messages"

- chatcommands.py
Standby all instances except matching ones
> !!/standby-except command

- findspam.py
We currently have only this text for the reason:
```
Post - Username similar to website
```
It isn't very clear in some cases.
Resolves #1655
> Show username is similar to which website

- bad_keywords.txt
See https://chat.stackexchange.com/transcript/message/43917775#43917775
> phone number updated to include other numbers beforehand

- rooms.yml
https://chat.meta.stackexchange.com/transcript/message/6859061#6859061
> added πάντα ῥεῖ to MSE Tavern

- findspam.py
Restrict to a small-ish set of sites and users with max rep 1
> Watch for 1-rep troll user on Judaism etc

- findspam.py
Extend "Bad NS" to cover more name servers which are prevalent in hosting domains seen in spam URL links.
> Bad ns too

- rooms.yml
> added Hovercraft Full Of Eels

- watched_keywords.txt
Remove invisible characters added by chat. It appears that I'm the only one that's added regexes long enough to be affected.
Improve the longer offensive regex
> Repair regexes with invisible characters and improve Makyen regex

- bad_keywords.txt
Individually, this is the following user-targeted offensive posts (basic metasmoke searches just for the usernames in posts):
* [Targeting Rubellite Fae on Hinduism](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=Rubellite+Fae&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search)
* [Targeting Sarvabhouma on Hinduism](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=Sarvabhouma&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search)
* [Targeting Rohit on Hinduism](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=Rohit&username=&why=&site=249&post_type=&feedback=&autoflagged=&reason=&user_rep_dir …
> Catch user targeting of Rubellite Fae, Sarvabhouma, Rohit, and Anisha on Hinduism.se.

- rooms.yml
> adjusted socvr settings

- rooms.yml
[approval](https://chat.stackexchange.com/transcript/message/44330079#44330079)
> added Stephen Kennedy to SObotics and SOCVR

- blacklisted_websites.txt
https://chat.stackexchange.com/transcript/message/44481131#44481131
2tp/3fp
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=wuinstall.com&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> removed wuinstall.com from blacklist

- findspam.py
- test/test_regexes.py
[Originally proposed by tripleee](https://stackoverflow.com/c/charcoal/q/375/41).
> Reason: Body starts with title and ends in URL

- findspam.py
See #2012
Attempt to fix this by changing post title to some placeholder text if the post is an answer.
> Don't check title when scanning answers

- rooms.yml
> delay messages

- rooms.yml
[Chat message with RO authorization](https://chat.stackoverflow.com/transcript/message/42677072)
> Add Makyen to SOBotics. Authorized by Petter Friberg

- findspam.py
Slightly extend the corresponding "blacklisted username" rule
> Remove watch on username ^John$ --autopull

- rooms.yml
Request has been discussed with room owners, no one raised any objections
> Grant Shree privileges in SOBotics

- rooms.yml
[Request here](https://chat.stackexchange.com/transcript/message/45422994#45422994) and [chat user profile here](https://chat.stackexchange.com/users/40662).
> +Frenzy Li to CHQ

- findspam.py
The upgrade of this dependency should be done by now. Anyone can merge this request to finalize this upgrade.
> Remove tld 0.7 compatibility code, expect tld 0.8

- rooms.yml
See conversation in CHQ starting [here](https://chat.stackexchange.com/transcript/message/45531666#45531666)
My first interaction with this user was this conversation.
> Add Erik the Outgolfer to CHQ

- findspam.py
This is an improvement on mostly_dots.
> Catch punctuation spam

- metasmoke.py
Change the code to receive the new data sent by MS to unblacklist the user when fp is sent (see https://github.com/Charcoal-SE/metasmoke/pull/473)
> Receive new 'unblacklist' data from MS

- rooms.yml
As a SOCVR RO, I approve this addition. :-)
> Add Jim Garrison to SOCVR

- rooms.yml
by a majority vote between RO's
> added Michael Dodd for SOCVR

- chatcommands.py
> Resolve #546: !!/test-json prototype

- rooms.yml
> added Erik von Asmuth for SOCVR

- chatcommands.py
> Adding escape to fix render issues with shrug face

- watched_keywords.txt
Remove an extra space from a recent number regex. Provide a time for a couple of recent additions which is between the entries on either side.
> Remove extra space in a regex. Give recent additions a time.

- watched_keywords.txt
Don't detect in `<code>`.
Add additional excluded domains.
> Reduce FP in test for expansion of link following arrow.

- globalvars.py
This fixed #2399
This makes the branch check use `git symbolic-ref -q HEAD` instead of `git status`, if in a non-detached state the result of symbolic-ref is `refs/heads/master`, if the head is in a detached state it exists with exit code 1.
> Use git porcelain for branch checking

- findspam.py
Added check in regex to ignore whitespaces
> Fixed regex causing FP on white spaces

- apigetpost.py
- bodyfetcher.py
- chatcommands.py
- datahandling.py
- deletionwatcher.py
* http://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls
> Use requests' params keyword argument instead

- rooms.yml
See https://chat.stackexchange.com/transcript/message/47490030#47490030
> Added K.Davis to SOCVR permissions

- rooms.yml
He already has privileges in SOCVR and has experience with the commands.
> Added EJoshuaS to CHQ Privileges

- rooms.yml
https://chat.stackexchange.com/transcript/message/47779396#47779396
Also some background chatter with Angus in Keybase
> rooms.yml: Add sau226 to Charcoal HQ

- rooms.yml
Please add reports to the main Stack Apps chat.  Note that I am a moderator on Stack Apps.
> Add reports to Stack Apps chat.

- rooms.yml
approved by me, Makyen and gunr
> added SOCVR privs for iBug

- findspam.py
Since we have a lot of similar objects in `findspam.py` (the rules, which are currently individual dictionaries), they're best wrapped into a class.
Some time earlier I already wrapped chat commands into a class (4629191ad3ca9af6156e740f1ede3a484861138f), but this time it's going to provide more maintainability than the previous one.
- Rules can have default values for attributes and a more unified handling
- Any function can be wrapped into a rule with a decorator, so adding a function-based rule only requires adding one block of code, not two. Currently you need to define a function and then add a dict into `FindSpam.rules`
- Default values for rule properties, like default "max rep", similar to default arguments for the chat command decorator. This keeps things clean and minimal
- …
> Refactor findspam.py

- chatcommands.py
- test/test_chatcommands.py
per https://meta.stackexchange.com/a/321263/358161
> added actual winterbash end date

- blacklisted_websites.txt
> Removed potentially erroneous equals sign

- findspam.py
- globalvars.py
- requirements.txt
- tasks.py
This is an alternative approach to #2597 using Python 3.5 `async` keyword, an alternate event loop, as well as some other async-related libraries.
Well, true asyncio this time, not creating an extra thread for every call.
Now that this PR is complete (ready to merge), reviews and suggestions are welcome.
> Run network-based spam checks with asyncio

- bad_keywords.txt
Bumps the tp rate on both, still 0 hits on SE (aside one current tp, but that one isn't worth counting)
> Fixes a couple mistakes

- rooms.yml
As an RO I approve the addition
> Adding Zoe to priv users

- README.md
- docker-compose.yml
Docker Compose is one of the most popular container management tool, adding support for it to Smokey would be nice :)
> Add Docker Compose instructions and configurations

- test/test_spamhandling.py
Unfortunately, there's been an issue with the test cases for the offensive title tests which resulted in the `pytest` test silently failing on every CI build over the last month.
This resolves the issues which were causing the failure, but doesn't resolve the problem that `pytest` can silently fail.
In addition, this adapts the offensive title tests to the updated code which implements sending masked and unmasked messages to appropriate rooms. It just checks that `chatcommunicate.tell_rooms()` is called appropriately. It does not check for the messages actually being sent to appropriate rooms.
This is related to Issue #3467, but doesn't solve the problem that `pytest` *can* fail silently.
> Fix issues with offensive title tests

- findspam.py
> Remove trailing whitespace

- findspam.py
- test/test_findspam.py
> IP check examines nameserver IP addresses, too

- test/test_chatcommands.py
Added info and location test cases to chat commands
> Added chat test cases

- findspam.py
To combat spam like this:
https://metasmoke.erwaysoftware.com/search?username=lustresparasalacom
> gratidão (Portuguese for thanks) added to bad keyword + link

- blacklists.py
- findspam.py
- test/test_blacklists.py
blacklists.py: normalize NS to lower case
_normalize method added to facilitate this
test/test_blacklists.py: validation code for the above
> findspam.py: normalize NS to lower case

- ws.py
Changed those code initiating websocket into a function init_websocket;  changed recovery using the newly created init_websocket
> Proposed potential bug fixes

- watched_keywords.txt
arxiv.org is definitely not spam. It is a platform on which papers are uploaded, and is the standard way for researchers in some field (example: math) to announce their new work.
> arxiv.org is not spam

- bad_keywords.txt
> Update raydia blacklist entry

- ws.py
Appended instance location to auto reboot message string to avoid confusion.
> Adjusted auto reboot message

- ws.py
Added waiting to init_se_websocket in the hope that network issues may be resolved after some time.
> Added waiting to init_se_websocket

- bad_keywords.txt
Too many fps. Move to watchlist instead.
> Entry "rock\W?hard(?:\W?bull)?" removed from blacklist

- gitmanager.py
Warning: further adjustment needed in `_anchor()` if @tripleee 's PR is merged.
> Anchor MS search string on PRs

- bad_keywords.txt
> bad_keywords.txt: Allow plural in support-number spam

- rooms.yml
Add chat room named Chat Restricted for feed for gaming.stackexchange.com
> Add room for Arqade

- rooms.yml
Add experimental and AU meta by request: https://chat.stackexchange.com/transcript/message/54784272#54784272
> Add experimental and AU meta by request

- findspam.py
> Add visit my channel to bad keyword with a link

- chatcommands.py
- chatcommunicate.py
Note that "sh " and "!!/" are of the same length.
Linked issue #4083
> chatcommunicate.py: Using sdc to invoke standard commands

- findspam.py
Improved image block finding regex; specify the digits to put into `why` data.
> findspam.py: Minor improvements in mostly-image reason

- gitmanager.py
> Replace None with empty string in GitHubManager

- chatcommands.py
Force `delete-force` for all messages in Charcoal HQ.
> Delete force in CHQ

- chatcommands.py
Removed an unecessaey line, thanks to a spaghetto for pointing this out.
> Delete force in CHQ (remove unnecessary line)

- chatcommands.py
Use a more permanent image link instead of a generic one which could go down.
> Use a more permanent image link

- chatcommands.py
Credit to Makyen for the code, tested and working
> Leave reason blank when not provided.

- test/test_chatcommands.py
Add's CI tests for the `reject` command, similar to the `approve` tests.
> CI testing for the reject command

- test/test_chatcommands.py
Updates CI tests for the reject command as the aliases used could have been confusing
> Updates CI tests for the reject command

- findspam.py
A lowercase L looks like an uppercase I: https://metasmoke.erwaysoftware.com/post/261698#preview-tab
This PR amends the offensive regex. 1/0/0 on MS, no legitimate hits on the site
> [findspam] expand n-word regex

- .pullapprove.yml
Caused the check to fail, see https://pullapprove.com/Charcoal-SE/SmokeDetector/pull-request/4998 for example.
> Change Daniil's username on GitHub

- chatcommands.py
"Please provide an adequate reason for rejection (at least 20 characters long) so the user can learn from their mistakes. Use `-force` to force the reject"
https://chat.stackexchange.com/transcript/message/55884729
> Changed !!/reject 

- watched_keywords.txt
Exclude API, help site, widget, bare domain, and code blocks.
Removes 63 FP, 2 NAA, and 1 very questionable TP (https://metasmoke.erwaysoftware.com/post/97032)
> Tighten SurveyMonkey watch

- blacklists.py
- gitmanager.py
- test/test_blacklists.py
Reinstate proper formatting for watch expressions; required some additional refactoring.
Add a test case for watchlists.
> Fix watch (regression from #3884)

- findspam.py
@ThatRyanPerson  reports all FPs for this:
https://chat.stackexchange.com/transcript/11540?m=56131298#56131298
Git blame suggests this was added by @makyen
> findspam.py: remove ecoflex

- chatcommunicate.py
> chatcommunicate.py: Remove user ID check for 435118

- watched_keywords.txt
> Remove code matches for Pinterest

- watched_nses.yml
This domain no longer resolves and is resulting in test failure. It also has no hits on MS or SE.
> permainanceme.online no longer resolves (NXDOMAIN)

- rooms.yml
Per @M-Daniil request: https://chat.stackexchange.com/transcript/11540?m=58648588#58648588
> Per Xnero request, add Outdoors site to Travel's SD reports room

- rooms.yml
Add SmokeDetector to https://chat.stackexchange.com/rooms/129590/cgcc-mod-office for content on CGCC
> Add CGCC Mod Office to rooms.yml

- findspam.py
- test/test_findspam.py
test/test_findspam.py: add a test case for this scenario
Closes: #6700
> findspam.py: use tld.get_tld().fld to get domain for NS query

- datahandling.py
- helpers.py
- ws.py
https://github.com/Charcoal-SE/SmokeDetector/pull/3971#issuecomment-930616269
>  Use plain text for queue timings data, part 2

- findspam.py
- test/test_findspam.py
test/test_findspam.py: test for the above
> findspam.py: "several emoji in title" rule

- datahandling.py
The prior code was making a request to chat for the current users in the room  for every report which was posted in chat, regardless of if that information was needed (i.e. that there were users who had requested notifications to be sent with reports to that room only when the user was in the room).
This PR changes the logic to only fetch from chat the list of users currently in the room when that data is actually needed (i.e. there's at least one user who has requested to be notified for reports in that room only when they are present in the room).
Ideally, we'd cache this information after the first report into a room and then only watch for notifications of users joining or leaving the room. However, it's rare for people to request pings only when they are in the room (it's a, …
> For notifications, don't fetch the users in the room unless needed.

- findspam.py
- test/test_findspam.py
Simple 1337 decoder for a small set of troll / phone support scam keywords
test/test_findspam.py: test case for the above
> findspam.py: obfuscated_word(): new rule "obfuscated word"

- findspam.py
... where X is "title", "body", or "username", as for other similar rules
> findspam.py: update "obfuscated word" to include "in X"

- rooms.yml
Approved by Double Beep https://chat.stackoverflow.com/transcript/message/53566138#53566138
> Added Adrian Mole to SOBotics list

- findspam.py
Also, some mild refactoring to improvbe the legibility of the link_at_beginning and link_at_end functions
> findspam.py: add regexr (regexr.com) to WHITELISTED_WEBSITES_REGEX

- findspam.py
9/9 over 4 years, been picking up significantly over the last week
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=ductcleaning
> findspam.py: add ductcleaning to nwb list

- findspam.py
This should hopefully identify a recently prevalent pattern.
The rule so far is very specifically tailored to the samples I have at hand; going forward, we might want to try to generalize it for broader use.
> findspam.py: body_text_repeated rule

- bodyfetcher.py
For the sites where we fetch all recently modified posts (i.e. only SO), there's no need to schedule an explicit re-scan of the post when there's a post processing conflict (i.e. when one thread encounters a post that is currently being scanned by another thread). For SO, it's effectively guaranteed that we will be requesting all of the recent posts back far enough, currently 6 minutes before the most recent `last_activity` date we find, such that it's very likely that if the version was currently being tested isn't the actual most recent version, then that we will be fetching and testing the potentially updated version very soon.
The goal here is to reduce the number of effectively useless API fetches which we do (useless in that they are just giving us redundant data). The `stats` …
> Don't re-request posts when post processing conflict for some sites (e.g. SO)

- chatcommands.py
Osiris is intermittently logging errors when it posts some reports in chat, because [Xnero's old chat account](https://chat.stackexchange.com/users/435118) was deleted while there were still notifications set for that account to get pings for some reports.
This PR adds the command `!!/unnotify-all-admin <user_id>` which can be used by metasmoke admins to remove the notifications for the specified user ID on the chat server on which the command is executed. So, when merged, I expect to execute the command `!!/unnotify-all-admin 435118` in Charcoal HQ to remove the impossible to send pings.
Also related: https://stackoverflow.com/c/charcoal/questions/824
> Add command: !!/unnotify-all-admin <user_id>

- findspam.py
This PR does:
* Add a `threading.RLock()` for `findspam.LINK_CACHE` (thread safety)  
The "right" solution for this is to have this information as part of the `Post` object, so there isn't a global variable which is being modified by multiple scan threads. That, however, takes the `Post` changes I'm working on plus reworking the detections which currently use this information to get it from the `Post`, rather than from a global variable. Even then, we'd *still* need a lock for it, and everything else in a `Post`, if/when we move to having the actual tests use multiple threads, rather than a single thread for all testing. The alternative to threading locks in the `Post` is to have all tests which get passed the `Post` object be in a single thread, while those which use just the title, …
> Add a threading.RLock() for findspam.LINK_CACHE

- number_homoglyphs.py
This PR adds functions which can be used in testing/development to generate a regular expression character class which covers the desired `included_obfuscations`. In addition to a general purpose formatting function, `table_as_regex()`, functions are provided which are specific to the format needed for each of:
* MS searches ([Mongdb database regex engine; PCRE version 8.42 with UTF-8 support](https://www.mongodb.com/docs/manual/reference/operator/query/regex/)), `table_as_ms_search_regex()`,
* Individual character escapes are in the form of `\x{x}`, where the hex value is 1 to 4 hexadecimal digits.
* MS Regexp ([Ruby 2.7.4 Regexp](https://ruby-doc.org/core-2.7.4/Regexp.html)) ,`table_as_ms_regexp_regex`, and 
* Individual character escapes are in the form of `\uxxxx`, with 4 hexadecimal …
> number_homoglyphs: Add translation table to regex character class text convenience functions

- findspam.py
https://chat.stackexchange.com/transcript/message/62326916#62326916
> findspam.py: trap ValueError from get_domain()

- findspam.py
- test/test_findspam.py
> finspam.py: obfuscated_words: avoid FP on simple possessive

- chatcommands.py
- classes/dns.py
Provide transparency for DNS from SmokeDetector's perspective
Also, improve robustness against invalid queries, and refactor the underlying code somewhat.
> Implement !!/ns and !!/soa chat commands alongside !!/dig

- findspam.py
add special-character arrows to the "link following arrow" reason
> add special-character arrows

- CONTRIBUTING.md
vulnerabilitites -> vulnerabilities
> Fix typo error in  CONTRIBUTING.md

- watched_nses.yml
Reverts Charcoal-SE/SmokeDetector#8565
> Revert "Update watched_nses.yml: Remove nccloud.shop NS - NXDOMAIN"

- rooms.yml
see https://chat.stackoverflow.com/transcript/message/57110674#57110674
> Update rooms.yml to add privileges for Cow to SOCVR

- rooms.yml
https://chat.stackoverflow.com/transcript/message/57467250
> Added Cocomac to SOCVR

- rooms.yml
- users.yml
Requested in chat https://chat.stackexchange.com/transcript/11540?m=66131562#66131562
> Give privs to Jeremy in Tavern on the Meta

- watched_nses.yml
> Watch NS seodns.one.

- watched_nses.yml
Resolves recent build failures, e.g. https://github.com/Charcoal-SE/SmokeDetector/actions/runs/12206395258/job/34055765884
> Commented out fusionlogicx.com -- NXDOMAIN

- watched_keywords.txt
First time trying to edit a watch that is too big to be handled in CHQ Chat.
> Edited watch that was too long for chat.

- watched_nses.yml
- no matches as of 2025-05-02
- registry expired 2025-03-18
> disable ns accesget.com

- blacklisted_nses.yml
unixplorer.com NXDOMAIN as of 2025-05-12
> Update blacklisted_nses.yml - disable unixplorer.com

- watched_nses.yml
It was causing CI build errors, the domain seems to be not responding.
> Temporarily disable studentdatabase[dot]co[dot]in ns watch
