- chatcommunicate.py
Remove !!/commands, replace with wiki link in !!/help, probably better
to keep command help in as few locations as possible; less work to
update.
> Remove !!/commands, replace with wiki link in !!/help

- findspam.py
1) skin care is sometimes written as one word, so I've made space optional.
2) sites with garcinia in the name don't need to be blacklisted: garcinia is blacklisted without word boundaries
P.S. user currently known as 1999
> skin ?care, removed redundant sites

- findspam.py
1. Neuroluma showed up 3 times recently: http://stackexchange.com/search?q=neuroluma
2. Moved "eye ?serum" to nwb list, so that it also takes care of domains and variations
3. Generalized health{numbers} regex because numbers vary:  health786.com  appeared recently
4. Moved "tophealth" to nwb list because domains vary. No false positives even on Health.SE (checked with http://data.stackexchange.com/health/query/330774/search-with-no-word-boundaries?pattern=tophealth 
5. Removed redundant garcinia site (garcinia is nwb blacklisted)
6.... not sure why the diff shows the first line as edited
> neuroluma, eyeserum, health-regexes

- findspam.py
A med being promoted today; better to blacklist the name than the ever-created sites.
> +Alpha Rush

- findspam.py
A bunch of spam domains match  buy[a-z0-9-]{6,}\\.com
like {something}buyonline.com or buy{something}.com 
The length restriction rules out bestbuy.com, buy.com, buysql.com ... 
(Also added some explicit regexes)
> +buy.......com etc

- findspam.py
A few sites ending with workout.com are spammy. Put into the regex that excludes fitness.SE  and health.SE
Also, that regex had a bug: body ?builder was entered as if we expect "weight" in front of it. Moved it to a proper place and generalized to body ?build(er|ing)
> +workout.com to health regex, debug

- findspam.py
- Moved "muscle" outside of word boundaries on non-health sites. It's not a part of any other word, but is usually a part of spam domain name.
- moved anti[- ]?aging to nwb list. They hardly ever use this term on biology/health/fitness; even there it's likely to be spam. 
- added "serum" to "bad part of domain" list
> make muscle, anti-aging nwb, etc

- findspam.py
More general patterns of "health"+something spam domains (can't blacklist health on its own). If they work as expected, some of specific domains can be trimmed later from the blacklist.
Also added a few specific domains.
> health+pro = spam

- findspam.py
- "black label no" is a popular... thing they sell
- "loan offer" detection, because they began to obfuscate email
> +black label, loan offer

- README.md
Ubuntu comes by default with a pretty ancient version of `pip` in its repositories. Unfortunately, that version is no longer compatible with the latest version of `requests`, which deletes (?) a package called `IncompleteRead` on that old `pip` still depends.
So as soon as you upgraded `requests` with your old `pip`, it will be broken due to that now missing package. It can be repaired with `sudo easy_install --upgrade pip` (`easy_install` is a python package management tool similar to `pip`, but slightly older and with less features, however it does not have that problematic dependency, so it still works.), but it's best to prevent this from happening by upgrading `pip` before `requests`!
> Add upgrade of `pip` before `requests`

- chatcommunicate.py
- globalvars.py
- ws.py
Before, the SmokeDetector user IDs were hardcoded.  Now, we use ChatExchange's .get_me() method to determine the ID.
> Determine bot user ID at runtime, and added !!/whoami

- findspam.py
- globalvars.py
Removed "black magic" and adjusted "weight loss" to reduce false positives.
Regarding "weight loss":
- It was causing too many false positives due to [the term *deadweight loss*](https://en.wikipedia.org/wiki/Deadweight_loss), which frequently occurs in economics.
- Reference [this chat on Charcoal HQ](http://chat.stackexchange.com/transcript/message/25247160#25247160)
- Tweaked the regex to only match when word starts with "weight".
<br>
For "black magic" see:
- Starting [here, on Tavern](http://chat.meta.stackexchange.com/transcript/message/4165391#4165391)  
and
- [Here, on Charcoal HQ](http://chat.stackexchange.com/transcript/message/25247400#25247400)
> Adjusted keywords to reduce false positives.

- findspam.py
**Warning: Untested!**  (How do we test filters without making bad posts, other than the `!!/test` command?)
"Black magic" was causing too many false positives.
Removed it from the Islam site only.
See:
- Starting [here, on Tavern](http://chat.meta.stackexchange.com/transcript/message/4165391#4165391)  
and
- [Here, on Charcoal HQ](http://chat.stackexchange.com/transcript/message/25247400#25247400)
> Removed "black magic" check only from Islam site.

- chatcommunicate.py
When a user issues multiple reply commands and they can't all be processed, make it clear to her that *none* of them were processed.
See starting at: http://chat.stackexchange.com/transcript/message/25432482#25432482
> Clarify to user that none of his previous command was implemented.

- bodyfetcher.py
Don't zero-out the quota record when the API glitches or when a filter that doesn't include quota_remaining is used.
See: 
- http://chat.stackexchange.com/transcript/11540?m=26314837#26314837
- http://chat.stackexchange.com/transcript/11540?m=26260124#26260124
- etc.
> Don't zero-out quota record on API glitches

- bodyfetcher.py
If Smokey has crashed or rebooted when the API rollover happens, Smokey doesn't detect it and we lose all sense of what the lowest quota remaining might be.
This change effectively adds an extra line soon after the customary start line that helps mitigate that loss.
The gold-standard way to track quota levels, is to update the quota in a file. But, this file would see about 10K read/write cycles a day.  Do we want to do that?
> Quota rollover is lost if it happens when Smokey is down.

- findspam.py
These websites have been used in spam:
accountingassignments.help: https://metasmoke.erwaysoftware.com/post/17725
phphelponline.com: https://metasmoke.erwaysoftware.com/post/17724
> Add `accountingassignments.help` and `phphelponline.com` to the blacklist

- findspam.py
Current detection's for this website are either "manually reported" or "blacklisted user":
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body=getcheaptwitter&commit=Search
> Add `getcheaptwitterfollowers.org` to the blacklist

- globalvars.py
I would like to propose adding 
- myself ([ByteCommander](http://stackexchange.com/users/5612515/byte-commander?tab=accounts)) to the list of privileged users in CCHQ and Tavern
- [kos](http://stackexchange.com/users/5423050/kos?tab=accounts) to the list of privileged users in the Tavern.
Both applications are combined as @ferrybig requested in the Ask Ubuntu General Room. (near [this chat message](http://chat.stackexchange.com/transcript/message/28311310#28311310))
> Add Users kos and ByteCommander to privileged list

- chatcommunicate.py
This removed multiple `if` checks in `handle_commands` to a check of a dictionary for appropriate substitutions. 
The new dictionary - `command_aliases` - holds the expected command as a key and the substitution in the value.
Currently the entire dictionary looks like this:
```
command_aliases = {
"f": "fp-",
"notspam": "fp-",
"k": "tpu-",
"spam": "tpu-",
"rude": "tpu-",
"abuse": "tpu-",
"abusive": "tpu-",
"offensive": "tpu-",
"n": "naa",
}
```
If no key exists, the single `if` check prevents substituting a `NoneType`.
> Reduces multiple if statements to a single dictionary check for command aliases

- chatcommands.py
- chatcommunicate.py
This relates to #166. 
This is phase 1 - cleaning up `handle_commands` to be more manageable. This change replaces the massive function that existed with two `try`/`except` blocks. Once block is for the `sd <response>` commands and the other is for any other `!!/*` commands. 
Any required parameters are passed to the functions as part of the `*_parameters` dictionaries. 
All commands themselves have been put in `chatcommands.py`. This file is rather large, but once these are broken out into functions, I can work on eliminating several areas of duplication. 
One such duplication has already been removed - the logging to Metasmoke has been moved to a single function call within the appropriate commands, instead of each command needing to set up a Thread.
Prior to merging, I'd appreciate …
> Phase 1 of handle_commands clean up

- chatcommands.py
- chatcommunicate.py
- helpers.py
This change creates a common namedtuple ([`Response`](https://github.com/AWegnerGitHub/SmokeDetector/blob/branch_common_return/helpers.py#L4)) that is returned from each command.
This tuple has two parameters - `command_status` and `message`. Previously, the `command_status` was optional and assumed `True` if not passed. This was accomplished via these two blocks of code:
```
r = result
if type(result) == tuple:
result = result[1]
if result is not None and result is not False:
reply += result + os.linesep
elif result is None:
reply += "<processed without return value>" + os.linesep
amount_none += 1
elif result is False or r[0] is False:
reply += "<unrecognized command>" + os.linesep
amount_unrecognized += 1
```
and 
```
if type(result) != tuple:
result = (True, result)
if result[1] is not …
```
> Create common Response tuple for command returns

- chatcommands.py
- chatcommunicate.py
- test/test_chatcommunicate.py
This changes the decorator from returning a boolean to instead return a Response tuple when a user doesn't have permission to run a command. This change also fixes the subcommands failing if an unknown command is passed
Also included is a unittest to detect the decorator failure in the future
> Decorator fix to return response

- findspam.py
Added `graspui.com` to the blacklist.
See [this](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=graspui.com&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search)
> + graspui.com

- findspam.py
Added the website `etrove.com.sg` to the blacklist, see [this](https://metasmoke.erwaysoftware.com/post/36092) post which was not detected by SD.
> + etrove.com.sg

- findspam.py
A particular user has been spamming maths.se with a post advertising this book. It normally goes like the following: 
> There is  a book death reckoning calculate..... I think.but if you want same precision as a ten digits calculator do for 1 
See:
- https://metasmoke.erwaysoftware.com/post/36105
- https://metasmoke.erwaysoftware.com/post/36108
- https://metasmoke.erwaysoftware.com/post/36107
- https://metasmoke.erwaysoftware.com/post/36106
I added the words 'death reckoning calculate' to the blacklist of words
> + 'death reckoning calculate'

- findspam.py
All of these have been recently used for spamming:
supplementsadvisor.org -> https://metasmoke.erwaysoftware.com/post/37616
pokercheatcenter.com -> https://metasmoke.erwaysoftware.com/post/37614
intelligentadvices.com -> https://metasmoke.erwaysoftware.com/post/37620
yoursbetterhealthsolutions.com  -> https://metasmoke.erwaysoftware.com/post/37621
drozforskolin.org  -> https://metasmoke.erwaysoftware.com/post/37618
> +5 new websites to blacklist

- findspam.py
See https://metasmoke.erwaysoftware.com/post/38183
The 'link following arrow' reason will now catch stuff like `Read more = = = http://www.spam.com`
Yes, I know, it's techinically *not* an arrow, but it fits the general concept of this reason.
> Added new form of link following 'arrows'

- findspam.py
`[a-z]+` means "only letters", and doesn't catch answers that include digits, punctuation or non-ascii. 
Motivated by http://chat.stackexchange.com/transcript/message/32262048#32262048
> improve the "no whitespace" regex

- findspam.py
See https://metasmoke.erwaysoftware.com/post/41397
Note: [this Metasmoke search](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=000webhost&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) returns mixed results. See [chat](http://chat.stackexchange.com/transcript/message/32527710#32527710).
> Added 000webhost.com

- findspam.py
For some reason the regex `bojiter` doesn't catch something like "sexsexbojiter". ([source 1](http://chat.stackoverflow.com/transcript/message/33068905#33068905) [source 2](https://metasmoke.erwaysoftware.com/post/41185))
> Improved the bad keyword regex that catches wingding

- findspam.py
See [this Metasmoke](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=iseepassword&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) search (13 hits, 1 NAA, 2FPs, 1 unrated)
> Blacklist iseepassword.com

- findspam.py
See [Metasmoke search](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=zen-promo&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search). Could only be caught manually.
> Added zenpromo.com

- findspam.py
I just made the astonishing discovery that we have a 50% false positive rate on RaspberryPi.SE. I had a look at all of the false positives, and reasoned that an easy way to fix that in the future would be to disable the link at end of answer reason for that site.
The current stats are 4fp/1naa/3tp. See [here](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=&username=&why=&site=164&feedback=&reason=73&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) for more info.  
Your thoughts?
(ignore the CI, it's been failing ever since the new blacklist changes)
> -raspi.se from LAE of answer

- blacklisted_websites.txt
Blacklisted:
- `dlapks.net` (https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=dlapks&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search)
- `peridotsystems.in` (https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=peridotsystems&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search)
- `vincentfinancialservices.weebly.com` (https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=vincentfinancialservices&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search)
^ all have occurred more than once.
(I haven't committed directly to the master branch as it doesn't allow me to)
> Blacklisted few websites

- spamhandling.py
`//metasmoke.` is bad URL prefixing; use `https://metasmoke.`... instead
Note that this is the only occurrence I could currently find, but was an issue brought up in Charcoal HQ a little while ago when a `why` was called.
> Properly format URL for blacklisted user/post URL

- blacklisted_websites.txt
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=offersreviews.org&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> Adding offersreviews.org to blacklist after 7 TPs and no detection

- blacklisted_websites.txt
Used twice in known spam, not currently caught. Last occurence wasn't caught at all.
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=serverbasket.com&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> Blacklisting serverbasket.com

- blacklisted_websites.txt
Not currently caught as pattern matching, bad keyword or blacklisted website. 
8 tp occurences in the past month: 
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=usadrugguide.com&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> Blacklisting usadrugguide.com

- findspam.py
We're getting a flood of posts containing plagiarized content from unregistered accounts with the username "Marlin Woods" on Super User. Each post is on a separate unregistered account. See http://meta.superuser.com/questions/11908/flood-of-plagiarized-answers-from-marlin-woods.
> Add Marlin Woods to username blacklist

- bodyfetcher.py
Recent ValueError failures from attempting to decode JSON which
wasn't there, apparently because SO is now killing off hung sockets
after a timeout.
> bodyfetcher.py: give up if post doesn't have data

- blacklisted_usernames.txt
- findspam.py
In [this reply](https://github.com/Charcoal-SE/SmokeDetector/issues/305#issuecomment-262158807) to #305, bwDraco suggested that we should implement `!!/blacklist-username` as well as `!!/blacklist-keyword` and `!!/blacklist-website`.
To do that, we have to do the following (assuming we want to keep the format of the username blacklist consistent with the website blacklist and bad keywords):
1. Export the username blacklist to its own text file
2. Make [findspam.FindSpam](https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L201) use that text file instead of a hardcoded regex to figure out which usernames are blacklisted
3. Add the `!!/blacklist-username` command
Since 1 and 2 mess with parts that require no interaction with users, I decided to do them and leave the …
> Make findspam.FindSpam load the blacklisted username regex from a separate file instead of having it hardcoded

- findspam.py
Check for misleading link text which appears to go to one site but instead links to another, for example [https://github.com/Charcoal-SE/SmokeDetector](https://www.youtube.com/watch?v=dQw4w9WgXcQ).
I'm not a regular expression expert and this is my first time contributing anything like this to Smokey, so please review the code before merging -- I might have made a big mistake.
> Detect misleading link text

- findspam.py
The misleading link filter caught a post because that post linked to `http://example.com` but with the link text `http://www.example.com`.  I added a check for that in `misleading_link`.
Hopefully I can pass `flake8` this time...
> allow "www" in the misleading link filter

- findspam.py
I added checks to the misleading link filter so that it will not report posts unless both the link and the link text:
- Contain a period.
- Do not contain a space that is not leading or trailing.
- Do not contain things like "http://https://."
> Add checks to misleading link filter

- findspam.py
[wingding just found out how to circumvent the bad keyword filter.](https://metasmoke.erwaysoftware.com/post/49416) This could be caught by the bad keyword filter if each letter of the regex `bojiter` was separated by a `.?`.
(P.S ignore the merge commit, that was me updating my Smokey fork)
> Improve the no-word-boundary bad keyword that catches wingding

- gitmanager.py
We have a case here which we ran into today, where an attempt to create a pull request was returning an "Bad credentials" response from GitHub, without the `html_url` key in the JSON reply.  This was throwing a `KeyError` type error without any useful error output.
This change here attempts to capture such invalid replies, and throw a more useful error message as its return value, rather than just flat out crash and burn.
> Better-handle invalid GH replies when creating pull requests

- findspam.py
Confused img and a attributes; a can have rel, but img has optional alt
> findspam.py: Fix for Academia images (PR#324)

- blacklisted_websites.txt
I saw that there were only [five hits](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=faasoft&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) for "faasoft" and they were all false positives, but there isn't any command to remove a blacklisted site, so I figure this was the best way to do it. ¯\_(ツ)_/¯
> Removed 'faasoft' from blacklisted websites

- findspam.py
The misleading link filter I wrote is really bad at finding spam (almost all false positives), so I added it to FireAlarm and will remove it from Smokey.
> remove misleading link filter

- findspam.py
Detection of 'obfuscated' Yahoo email addresses
The aim is to detect posts like these: http://m.erwaysoftware.com/posts/by-url?url=//pets.stackexchange.com/a/15911
> Detection of 'obfuscated' Yahoo email addresses

- gitmanager.py
Apparently, bad keywords with spaces in [between were breaking links on github](https://github.com/Charcoal-SE/SmokeDetector/pull/369#issue-196215314). @angussidney made [a commit](https://github.com/Charcoal-SE/SmokeDetector/commit/cf72e1088d97f15aa3f900b6725a0dc157fb75db) to fix that.
Here is the markdown of the example link after angus's change:
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=muscle%20supplement
The `%20` up there represents a space. If you notice, there is only one `%20`, and that is after the `?`.
The space can also be represented by `+`, which I've tested and it works. [As per this answer on StackOverflow](http://stackoverflow.com/a/29948396/5735775), to represent spaces, `%20` should be used before the `?` and `+` should be used after …
> Replacing spaces in the MS search link with '+' instead of '%20'

- findspam.py
Many of these spams have been detected only by the domain name heuristic, which could fail if they post with a domain name which doesn't contain terms on the blacklist.  To strengthen the filter, add a rule to identify the conspicuous use of nested blockquotes.
Example: https://metasmoke.erwaysoftware.com/post/50594
> findspam.py: Nested blockquotes

- bad_keywords.txt
More specifically, I decided to take care of a long-overlooked pattern in the gibberish posted by [wingding](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=&username_is_regex=1&username=w.ng.%3Fd.ng&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) by adding `ANG kimoc.?hi`, a regex that has [19 hits with a 100% TP rate](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=ANG+kimoc.%3Fhi&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search), to the list of bad keywords.
> Add yet another regex for catching wingding

- blacklisted_websites.txt
Blacklisted webdebu.com
MS Search - https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=webdebu.com&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
A specific user has been [promoting content on that website.](http://chat.stackexchange.com/transcript/message/34332677#34332677) 
---
As a side note, I created a PR instead of blacklisting with the blacklist command as AFAIK, the command is broken.
> Blacklisted webdebu.com

- gitmanager.py
(1) While *extremely* unlikely, there is a tiny risk, if we change something about blacklist types and then forget to update `gitmanager.py`, that we'll have something blow up due to a no-value variable.  Let's have an "Else" case that will prevent that.
(2) Class methods tend to have `cls`, not `self`, in their arguments.
> Some minor code fixes

- findspam.py
Require eight or more levels in order for the rule to trigger.
FP fix for PR#377 which ended up generating quite a number of false positives.
Based on (incomplete) spam evidence, the pattern we are looking for is a *substantial* level of nesting, definitely more than the four levels the rule would originally match.
("Incomplete" because I cannot figure out how to search for this in Metasmoke, even with the regex option, and the samples I have saved for my own testing are too few and don't include false positives.)
> findspam.py: Tighten regex for deeply nested blockquotes

- bodyfetcher.py
This is the first attempt at the logic, so it'll need reverted if it stops working on timeouts.
This would put any posts as part of that timeout/failure in the request back into the queue.
> Add API request retry logic.

- findspam.py
Disastrous Track record recently: https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=Nike&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> Remove "Nike" bad keyword from Findspam.py

- bad_keywords.txt
Based on discussion with Glorfindel, capturing a single mistake is probably less important than covering a recurring pattern, so lose the single mistake and cover half a dozen or so samples from Metasmoke instead.
http://chat.stackexchange.com/transcript/message/34648436#34648436
> bad_keywords.txt: fix word boundary from PR#427

- bad_keywords.txt
I could find no evidence of these phrases in the collected evidence.  Maybe they never worked, or maybe they are just obsolete.  Either way, they don't seem to defend their place in the current blacklist.
> bad_keywors.txt: Remove obsolete long phrases

- findspam.py
Experimentation reveals six nested blockquotes or more are all TP.  Add the requirement to have a link alone inside the blockquotes.
This updates the rule introduced in PR#377 and tweaked in PR#416.
I have updated the rule description, I hope that's acceptable.  This no longer looks merely for nested blockquotes, so the old description would be misleading (but I'm wondering whether this will make Metasmoke regard this as a new heuristic).
> findspam.py: Update link inside nested blockquotes

- findspam.py
If I can guess the intent here, there's an alternation operator | missing before the fragment "(^| )(porno? "... -- without that, there is no way there could be a match on ^
> finspam.py: bad_link_text: typo fix

- blacklisted_websites.txt
fiverr\.com/w+ had 20 TPs out of 28, which isn't too great, and not a very frequent pattern anyway.
http://chat.stackexchange.com/transcript/message/34749585#34749585
> blacklisted_websites.txt: remove fiverr

- bodyfetcher.py
- chatcommands.py
Code simplification 1: We don't need to use datetime.strftime(datetime.now(), ...) we can just call strftime from datetime.now() itself.
Code fix 2: Undefined variable reference, I don't think we actually reach that currently, but it could error out (and probably should be from GlobalVars)
> Code simplifications and fixes

- chatcommands.py
Currently, we split on spaces.  For the blacklist commands, we are going to join multiple message parts with spaces, under the assumption that only one pattern is actually provided at a time.  Also, we need to include a merge from Master into this branch, because I made a mistake of not updating the Master branch first.  (My bad!)
> Quick and dirty solution for blacklist patterns that would have spaces

- gitmanager.py
While working on a test case for the blacklisting functionality, I bumped into problems with Unicode user names again.  This hopefully fixes at least part of the problem.
> gitmanager.py: Add more Unicode fixes

- metasmoke.py
Right now, when the Metasmoke websocket dies, SmokeDetector logs a message to the console and stops listening.  
I changed it (by stumbling along with the help of Undo) so that, if a MS connection has previously succeeded, it attempts to reconnect after 10 seconds.  
I also set a timeout so it will reconnect if it stops receiving heartbeats.
> Reconnect a dead Metasmoke websocket

- findspam.py
Spammers occasionally paste in a space before the URL and that currently bypasses this rather strict rule.  Edit it to tolerate this variation.
> http://%20 antipattern fix for repeated URL rule

- chatcommands.py
The ValueError exception attempted to use the variable we just failed to assign.
Fix by displaying the raw content in the error message instead.
> command_pending error references unset variable

- findspam.py
Just "safflower" gets 4 FPs currently; extending to "safflower\Woil" fixed 3 of them.
> findspam.py: fix safflower FPs

- bad_keywords.txt
As discussed here: http://chat.stackexchange.com/transcript/message/34997711#34997711
234/235 TP (one NAA): https://metasmoke.erwaysoftware.com/search?body=%28%5E%7C%5B%5EA-Za-z0-9_%5D%29%5C%2B234%5B0-9%5D%7B8%2C%7D%28%24%7C%5B%5EA-Za-z0-9_%5D%29&body_is_regex=1&commit=Search&feedback=&feedback_filter=naa&reason=&site=&title=&user_rep_direction=%3E%3D&user_reputation=0&username=&utf8=%E2%9C%93&why=
The proposal is Glorfindel's but we agreed I would make the PR. This is somewhat more far-reaching than your routine blacklisting request so I think we want to have this reviewed by the authors.
> bad_keywords.txt: Add Nigerian phone number pattern

- bad_keywords.txt
These were not working, because the leading plus is consumed by the word boundary condition in the code, so we can't match that directly, but we can say "if we just skipped a plus sign" with a lookbehind.
I included a couple of comments in the text file which are simply never going to match anything; but down the line, we might want to add code to skip comments in the file, or just remove these lines.
> bad_keywords:txt: Fix plussed phone numbers

- ws.py
These errors pop up every so often, and tend to cause hard-crash reboots, perhaps we can better capture/handle these by "looping" over getting values until they are valid, and raise a reboot-causing error with the error values.
Maybe we can handle them this way, and 'silently' capture the errors.
> Attempt to transparently handle "invalid literal" ValueErrors in ws.

- bad_keywords.txt
"textomenix" was a typo; proper "testomenix" remains.
"growth formula" may have been too aggressive; removing due to FP risk.
> bad_keywords.txt: Remove a couple

- findspam.py
Math.SE triggers a lot of false positives on this filter.
We should consider special-casing that site so that it has to have 5 or more and 15 or less unique characters for Math.SE.
This is free to be modified as necessary to adjust the threshold, or for a better approach/solution.
> Add special-case handler for Math.SE on 'has few characters'

- findspam.py
Design development company etc in Agra would match; make the regex stricter by requiring word boundaries around the city name.
Discussion: http://chat.stackexchange.com/transcript/message/35171323#35171323 (that's somewhere in the middle but the first comments are much earlier and not much of a discussion yet)
Kudos to Glorfindel again for briging this up.
> attempt to fix Vagrant FPs

- globalvars.py
- metasmoke.py
- nocrash.sh
- ws.py
**This is not thoroughly tested, and needs review before inclusion!**
We don't currently track the 'last time' a ping from MetaSmoke was processed.  Therefore, we have some odd cases where SmokeDetector will 'die off' and not ping.
By tracking the 'last pinged' time, and check if that time is greater than 60 seconds into the past.  If it is, then die off with exit code '10' and write to the ErrorLogs accordingly, then wait 5 seconds, and restart SmokeDetector with a brand new set of sockets.  The 5 second wait is for 'networking must settle' waits, just in case.
This should allow for 'not pinging' cases to 'try' and recover by a forcible restart to SmokeDetector, and will kill existing sockets and use brand new ones, in case of uncaught network interruptions.
> Metasmoke: Track 'last ping time', reboot if time > 60 seconds

- gitmanager.py
Ignore exit code 1 when checking whether global user.name and user.email
are set or not.  Also, fix copy/paste error in user.email check.
> Run git.config safely

- gitmanager.py
Refer to #505.
This code change would add code which will automatically delete the created auto-blacklist branch in the local tree after we are done with it - either when the merge was done and pushed automatically by SmokeDetector (for code priv. users) or once the branch is pushed up to GitHub and a Pull Request made.
Note this branch deletion only affects the `.git` folder where the SmokeDetector runs.  This leaves the rest of the branches intact on GitHub, but cleans up the local git tree a little.
I also discovered an issue here with when we handle git push/pull request errors in gitmanager when creating the pull requests, where it might not switch back to the "Deploy" branch, so let's forcibly go back to the branch.
> Delete auto-blacklist branches in local tree (#505)

- blacklisted_usernames.txt
The name of the "user" who posted https://metasmoke.erwaysoftware.com/post/56146 explains why I made this commit better than I could.
> Get rid of the anchors in wingding's username regex

- blacklisted_websites.txt
We already have fornatgaex in the blacklist, so the \.com is redundant.
> fornatgaex\.com duplicate removed

- bodyfetcher.py
- datahandling.py
Don't merge yet, but feedback is welcome.
See http://chat.stackexchange.com/transcript/message/35339676#35339676 for context. Here's the theory:
1. When we make an API call, for example, for post IDs `[1,2,3,4]`, we store the *highest* ID (`4`)
2. When *another* API call for that site is triggered (for `[7,8,9,10]`), we:
1. take the highest ID from the new batch (`10`), 
2. compute all IDs between the previous highest ID (`4`) and the new highest (`10`) = `[5,6,7,8,9,10`]
3. Merge with the requested IDs (`[7..10]`) as they may contain an edited post (imagine if `0` was a valid ID and requested) and uniqueify
The idea is that if we make an API call for `[1,2,3]`, then one for `[5,6,7]`, we *probably* intended to get `4` too but the websocket didn't give it to us for whatever reason. …
> Infer missed IDs from previous API calls

- blacklisted_websites.txt
Today's hit for vpnranks.com was a FP.  The site hasn't had any other hits for 8 months.
The older hits were marked TP, but were more or less decent answers.
Discussion about removing the rule with Glorfindel, here:
http://chat.stackexchange.com/transcript/message/35572084#35572084
> Removing match for vpnranks.com

- findspam.py
- requirements.txt
- test/test_regexes.py
**Important Note:** DO NOT AUTOMATICALLY PULL THIS. A new library needs to be installed where ever Smokey is running to utilize this change.
pip install tld
---
This change implements the username like website check. The following steps are performed to do this:
- Common malformed protocols are corrected to be `http`. This eases parsing of links. Common patterns can be added by modifying the [`COMMON_MALFORMED_PROTOCOLS`](https://github.com/AWegnerGitHub/SmokeDetector/blob/5d45b6215d47485654354915e9250d6a2b6988cb/findspam.py#L14) list of tuples.
- Links are extracted
- Each link is compared with the user name. Currently, there are 4 comparisons:
- Username vs Domain as is
- Username vs Domain with spaces stripped from Username
- Username vs Domain with hyphens stripped from both
- …
> This implements username like website; adjusts method calls to accept *args

- spamhandling.py
As per the first point of #488, this replaces the link to the repository with a shortened URL to the 'What's Smokey' section of our website. This would be more useful to newcomers than the repo link, and you can still access the repo via the pinned projects in CHQ.
Note that the prefix for the startup message remains unchanged (still pointing to the repo), as it is more likely that people would like to be linked to the repo then.
https://goo.gl/eLDYqh -> http://charcoal-se.org/#whats-smokey (sadly, git.io only works for Github pages sites under the .github.io domain.)
If there aren't any concerns, I'll merge this tomorrow.
> Change repo link to description in report prefix

- nocrash.py
This is to avoid a failover tug of war whenever `!!/pull` is used.  If we passed `standby` into `nocrash.py`, we should remove `standby` from the `persistent_arguments` variable, so that we don't autolaunch into Standby every time.  This way we're almost guaranteed to have at least one instance of Smokey in 'active' mode.
This required a couple additional changes.  We now check `persistent_arguments` instead of `sys.argv` for determining if we 'standby' launch.  We then add an `if` statement to 'remove' `standby` from the persistent args if we've quit with code 3 (the "pull" command code).  This way we don't 'restart' in standby mode in such cases, even if we don't intend for that to happen.
> Remove "standby" from runtime arguments when 'pull' is called

- findspam.py
Small fix to exclude [these FPs](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=male+performer&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search), as suggested by [@Gothdo](http://chat.stackexchange.com/transcript/message/35697197#35697197).
> Eliminate FPs for ‘(fe)male performer’

- ws.py
This issue has plagued us in the past.  Logon may randomly fail, and we get an "invalid literal" error when trying to parse a string as an int.  Our first attempt at this capture didn't fix the core issue.
This is a major refactor to the logon process, *but* it will give us a better way of handling things.
Firstly, split the individual logons and value acquisitions into separate little segments of code.
Secondly, put a `for` loop around each segment, and track how many times we've iterated over the logon attempts, waiting 1 second between each failed attempt.  This also limits us to 10 attempts by 'for' loops.  We then try to get the logon data and values that are valid, but when it fails it waits a second, then goes to the next item in the loop and tries again.  The moment we've got a …
> Try and better handle logon failures and "Invalid Literal"

- apigetpost.py
- bodyfetcher.py
`api_get_post` has error handling in case it is passed an invalid URL or the API does not return any `items`.  However, this error handling does not release `api_request_lock`, causing a deadlock the next time `api_get_post` is called.  A similar bug occurs in `bodyfetcher.py`.
This bug is *a* cause of `!!/report` breaking, but it may not be *the* cause.
> Fix leak of api_request_lock

- gitmanager.py
This attempts to work around the "git push.default simple" symptom.
See also http://stackoverflow.com/questions/21772279/why-is-pushing-to-matching-the-default-in-git/21772695#21772695
Example transcript:
http://chat.stackexchange.com/transcript/message/36096835#36096835
> add_to_blacklist(): explicitly push to master

- classes/Post.py
- findspam.py
Rules can now have a new `whole_post` key that if true will cause the entire `Post` object to be passed to the method. Currently it's a little messy since due to how `test_post` is structured you have to include `title` `username` and `body` keys even though they're being ignored anyways (it tries to access them for generating the regex why without checking to see if the rule even is a regex...)
Additionally this also has the 'answer similar to existing answer on post' rule, which uses `difflib` like username is similar to website. This is to catch spammers that merely copy and paste another answer and add a bunch of spam links to it. I'll try to get tp/fp data as soon as I can.
> Added whole_post and  'answer similar to existing answer on post' reason

- bodyfetcher.py
- datahandling.py
- queue_timings.py
This should measure how long a post has been in the bodyfetcher queue at the point that the API call for its site is made. It stores the timings locally in `bodyfetcherQueueTimings.p` so that stats can be analysed. Also created a Python script to do that analysis.
PR'd so I can get a code review, and cc @Undo1 since he was talking about doing this.
> Measure post queue timings

- findspam.py
We've been getting a rash of spam posts that try to be "clever" like this: http://chat.stackexchange.com/transcript/message/36131864#36131864
We catch them anyways since our phone number detection isn't dumb, but I figured it wouldn't hurt to throw in an extra rule to catch them. This rule will trip if the ratio of dots to characters in the post is greater than 40%.
> Added 'mostly dots' rule

- chatcommands.py
Currently, there are several joke responses to the !!/alive command which only show in SOCVR and the Tavern. I'd like to make CHQ great again by bringing them back to Charcoal HQ.
Does anyone have any objections? It's quite obvious by the fact that Smokey's posting a message that the bot must be alive, so there shouldn't be any concerns from that perspective.
> Allow joke !!/alives in CHQ

- blacklisted_websites.txt
[Metasmoke Search](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=click2trial&username=&why=&site=&feedback=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) - been used in 7 spam posts over the last couple of weeks now
> Add click2trial.com to blacklist

- findspam.py
Previously I had used the same threshold for this rule as "username similar to website," which was *way* too high considering the difference in sizes between usernames and posts. After a little bit of experimentation, I've decided 70% is a good number to try.
> Lowered threshold for similar_answer

- findspam.py
Generally, where we already had .in and .info, also capture .us
> findspam.py: Add .us to popular scam TLDs

- findspam.py
Pune is a large city in India which frequently occurs in spam
(Metasmoke stats are currently 32 TP / 5 FP / 1 NAA).
http://chat.stackexchange.com/transcript/11540?m=36640159#36640159
> findspam.py: add Pune to city_list

- bad_keywords.txt
Somehow an empty line ended up before the latest new blacklist entry.
> remove empty line

- gitmanager.py
read() on a file opened with 'a+' mode yields an empty string.
Accommodate by looking for either that or '\n' at the end.
Regression; see also [PR#658](https://github.com/Charcoal-SE/SmokeDetector/pull/658) which fixes recent symptoms.
> gitmanager.py: empty line fix for Python 3

- bad_keywords.txt
Allow "zytekxl" as well as "zytek".
Remove "male enhancement" (which is now separately blacklisted anyway) from "purple rhino" phrase and allow punctuation as well as space between the words (commonly, in URLs, it is instead a dash).  This captures five additional samples in the current Metasmoke database, two of which had a score only sligthtly over 190.
Details in individual commit messages.
> Update bad keywords

- findspam.py
- test/test_spamhandling.py
For the time being, it specifically matches URLs ending with "-reviews"
(with a couple of oddball variations from old spam).  This is a common
MO for the Indian pharma spammer.  Most of these spams are detected just
fine, but they are mutating brand names etc. incessantly and might one
day succeed in getting past the usual filters.  This is added as just
one more layer of "defense in depth".
It should be relatively easy to see how to add more fragments to the
rule in the future.
There are two new test cases to check both branches of the regex at
the heart of this rule.
Current Metasmoke report for a similar query suggests 3494/3494 TP rate:
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=%28%5E%7C%5B%5EA-Za-z0-9_%5D%29%5BA-Za-z0-9_%5D%2B-reviews%28-%28 …
> findspam.py: New reason "Bad pattern in URL"

- bad_keywords.txt
"Novellus Skin" was blacklisted, but "Novellus" occurs in recent spam
with a lot of other suffixes, too.
> bad_keywords.txt: Blacklist novellus alone

- bad_keywords.txt
<del>Refactor "breasts? enlargement" to also work with e.g. a dash between the keywords,
as commonly seen e.g. in URLs.</del>
> Remove breast enlargement phrase from bad keywords

- classes/Post.py
Instead, depend on helpers.log() for reporting parsing problems.
This makes the error less visible, but avoids the potential risks of using an exception (see discussion on [PR#668](/Charcoal-SE/SmokeDetector/pull/668), which this supersedes).
Also coincidentally fix the `api_response=` handling so that a `None` value will not override a default (notably, passing Metasmoke results with `"score": null` would fail further down in the code when you attempt to manipulate them).
> don't depend on GlobalVars

- bodyfetcher.py
- classes/Post.py
- classes/__init__.py
- spamhandling.py
- test/test_parsing.py
- test/test_spamhandling.py
For modularity, avoid doing anything with globals from this module.
Instead, possibly raise a ValueError for the caller to handle somehow.
> classes/Post.py: Don't pull in GlobalVars

- spamhandling.py
This avoids (un)intentional formatting in titles
> Prevent report title from containing ], *, `, or \n

- findspam.py
Case in point: https://metasmoke.erwaysoftware.com/post/66842
> findspam.py: allow multiple characters in punc-only link

- blacklisted_websites.txt
Commit d492454398d1ae9d1079bb3b47875521c4b46405 was a typo.
> blacklisted_websites.txt: typo fix

- findspam.py
Idiosyncratic title formatting, starting with lowercase "what is this".
Metasmoke results are approximate because it doesn't support case-significant searching. 
I get 101/114 TP rate with this, but the actual result is closer to 90/90 (however with some low-hanging fruit being missed by the rule): https://metasmoke.erwaysoftware.com/search?body=&body_is_regex=1&commit=Search&feedback=&reason=&site=&title=%5Ewhat+is+this+%28%5BA-Z%5D%7Chttp%3A%2F%2F%29&title_is_regex=1&user_rep_direction=%3E%3D&user_reputation=0&username=&utf8=%E2%9C%93&why=
> findspam.py: what_is_this_pharma_title()

- gitmanager.py
SmokeDetector should not care whether this setting is global or not,
as long as the value is correct in the current working directory.
Forcing it to be set globally hampers work on private check-outs and
makes some tests very hard to write.
> gitmanager.py: don't force or require --global git config

- findspam.py
Ignore regex101.com and getbootstrap.com for link at end; they produce too many FPs.
> Ignore regex101.com and getbootstrap.com for link at end

- chatcommands.py
TODO: display an orthography & grammar nazi warning badge
> chatcommands.py: allow common typo for "privilege"

- test/test_blacklist_integrity.py
Fail on empty line, no linefeed, or DOS CRLFs in any of the files.
> test/test_blacklist_integrity.py: Simple checks for blacklist files

- test/test_blacklist_integrity.py
Run a check against duplicates entries as well while we are already scanning the blacklists.
Incidentally, also refactor to put the function inside a `test_blacklist_integrity()` function so it works like the other `test/*.py` scripts.
> Test blacklist integrity duplicates

- findspam.py
Added bluenik.com as link shortener; it's an alternative domain for adf.ly. Used [here](https://m.erwaysoftware.com/posts/by-url?url=//askubuntu.com/a/913446).
> Added bluenik.com as link shortener

- spamhandling.py
- test/test_chatcommunicate.py
- test/test_spamhandling.py
This adds additional test cases and adds a patch in `handle_spam` so that it can correctly determine if it is in the test suite. This is done because `handle_spam` doesn't return the standard `Response` object in all cases, and instead prints directly to the chatrooms.
> More test cases

- gitmanager.py
This way, only one blacklisting request can be in progress at any time.  Further requests will simply block on attempting to acquire the lock, and thus wait nicely in queue.
Fixes #679
> gitmanager.py: add a critical section with a lock

- ws.py
The functionality in chatexchange_extension.py is partial; need
to also prevent ws.py from setting up connections to various rooms
to really make it use Charcoal only.
> ws.py: don't visit other rooms with charcoal-hq-only

- chatcommunicate.py
Due to AIM and MS, we are using 💩 to feedback naa in chat, while it is currently tp-. This swaps that.
See [here](https://chat.stackexchange.com/transcript/message/37460309#37460309) for one example
> We are using 💩 to feedback naa in chat

- bad_keywords.txt
The correct keyword progentra was separately blacklisted already.
> -progenta typo

- gitmanager.py
Stupid copy/paste of a code fragment which doesn't belong here.
> gitmanager.py: fix erroneous split

- findspam.py
@​quartata:
> [**↰**](https://chat.stackexchange.com/transcript/11540?m=37549828#37549828) @​SmokeDetector Oh jeez, is that going to trip on every ><> answer <sup>[source](https://chat.stackexchange.com/transcript/message/37550380#37550380)</sup>  
> That's not good, ><> is a very common esolang <sup>[source](https://chat.stackexchange.com/transcript/message/37550383#37550383)</sup>
> Don’t trigger “Linked punctuation in answer” if the text is `><>`

- gitmanager.py
The watch_keyword handling was simply reusing the blacklist messages.
Refactored for clarity to indicate what was done and fix e.g. the generated Metasmoke query for the PR for new watches.
Not entirely happy with the wording in the generated messages, but this should fix the biggest issues.
> Fixup commit message, PR title, etc

- blacklisted_websites.txt
- watched_keywords.txt
This adds a number of recurring spam domains to the blacklisted web site list.
Each domain is a separate commit, with brief statistics in the commit message.
Every one has at least one Metasmoke hit with a weight below our default autoflagging threshold.
> Indian pharma spammers

- findspam.py
"lose weight" was causing too many false positives on Pets.SE, including an autoflagged one today.
https://metasmoke.erwaysoftware.com/search?body=lose+weight&site=212
As per [moderator request](https://chat.stackexchange.com/transcript/message/38185045#38185045):
> I think we should remove the word weight gain and/or loss from the pets.se
> "lose weight" was causing too many false positives on Pets.SE

- findspam.py
This looks like an accidental commit.  The commit message when this was introduced indicates that a simple addition to a previous pattern was intended to be added, and nothing more.
https://github.com/Charcoal-SE/SmokeDetector/commit/fae73d8c3
> remove \w{9}rev\.com --autopull

- watched_keywords.txt
A couple of lines in `watched_keywords.txt` had broken formatting; line 205 had a trailing space (I'm not sure if it's a big deal or not, but I removed it), and line 206 had two spaces instead of a tab (which caused an error message when loading the keywords).
> Fix formatting of watched_keywords.txt lines 205 and 206

- chatcommands.py
This came up yesterday, when someone tried to blacklist a keyword that was in the old `bad_keywords_nwb`.  I added a check, similar to `!!/test`, before each blacklisting operation so that confirmation is required if blacklisting a keyword that is already caught.
Since the pattern to blacklist is a regex and not just a keyword or URL, this is not perfect, since the blacklist *pattern* is run through the filters and not necessarily what the pattern was intended to catch.  I replace `\W` with a space and `\.` with a period, so it should work for most blacklist/watchlist operations.
> Require confirmation if a blacklist pattern is already caught

- bad_keywords.txt
This matches "T Complex" instead of just T-Complex.
> Use \W instead of hyphen for T-Complex

- chatcommands.py
`!!/watch` accidentally set `force` to `True` instead of `False`.  <s>My testing says that, with this change, `!!/watch` will work but not `!!/watch-force`.</s> actually, I don't think it will fix the bug.
> !!/watch shouldn't force

- bad_keywords.txt
- removed zeushacks; only ever 3 TPs and they all included an email that would be caught.
- removed two redundant "hack tool" patterns since we have a dedicated "hack tool" pattern
- updated `hacker@` (34tp/2fp) --> `hacker\w*@` (145tp/2fp) 
- added `hack\w*@` (268tp/4fp), could maybe replace the `hacker@` one since it covers it, but it catches more FPs
- removed `\w*cyberhack\w*@\w*mail\.com` since it's covered by the `hack\w*@` pattern
> updated hack keywords

- bad_keywords.txt
consolidated a few neuro-something keywords. adding a `\W*` boosts matches from 59tp/0fp -> 62tp/0fp.
> updated neuro keywords

- bad_keywords.txt
- the "writing service" keyword will no longer capture people mentioning "code-writing service" or "script-writing service" as false positives. no post mentioning that has been a true positive.
- removed two names of doctors from witch doctor spam. don't bother blacklisting the individual doctor names, they come up with new ones each time.
- removed several obsolete phone numbers with zero matches ever or zero matches in the past couple of years.
> keyword updates: reduce writing service fp, remove obsoletes

- watched_keywords.txt
`text\Wreload` catches `test.reload` code, so i'd like to make this a bit more specific. all matches so far are hyphen or space.
> updating test-reload watch

- parsing.py
- test/test_parsing.py
Use the full link as suggested [here](https://meta.stackexchange.com/questions/297554/can-u-userid-redirect-to-users-userid-even-for-deleted-users-for-moderato#comment965491_297554) to prevent redirection problems when the user is deleted.
> Use the 'full' user link in Smokey reports

- watched_keywords.txt
these keywords all showed up in recent spam/abusive posts my autoflags have been used on, but these were not themselves recognised in any form
> add multiple watches from recent spam

- bad_keywords.txt
when adding these keywords I wasn't aware that they were implicitly surrounded by `\b ... \b`. updating these to work within that constraint.
> fix some bad keywords for word boundary

- bad_keywords.txt
The spell spam regex wasn't built with the implicit `\b ... \b` word boundary in mind so it basically wasn't working: it had [7tp/1fp](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=%5Cb%28spell%28home%29%3F%7Ctemple%7Cclasses%29%5Cw*%40gmail%5C.com%5Cb&username=&why=&site=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search). These emails usually have extra words at the beginning like "hindu spell temple" or "dr agave spell temple" or whatever.
I've made two changes to this regex:
- added a `\w*` at the beginning, which [makes this regex functional](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=%5Cb%5Cw*%28spell%28home%29%3F%7Ctemple%7Cclasses%29%5Cw*%40gmail%5C.com%5Cb&user …
> Updated spell spam regex & added herbal centre

- findspam.py
Added `rurl.us` as link shortener after some manually reported answers today:
https://metasmoke.erwaysoftware.com/search?body=rurl.us
> Added rurl.us as link shortener

- datahandling.py
When we did a shift from Py2 to Py3, we ended up having a unicode decoding issue with some pickle files.  Mostly because we didn't store the pickles in UTF-8 encoding.
As such, loading in UTF-8 mode breaks some of the pickles.  We should probably just *delete* the pickles and continue on when we get a `UnicodeDecodeError` for the pickles, so that we can continue without issue.
I wrote a `_load_pickle` function that can handle that, and did some revisions so that we only have one pickle 'loader' function that we can use to help handle invalid pickles.
> Pickles: If UTF-8 decoding fails, delete the pickle file and don't crash.

- findspam.py
Attempt to catch posts like this one: https://metasmoke.erwaysoftware.com/post/76646
where the email address is `@ g mail . com`.
> Improved detection of obfuscated email addresses

- watched_keywords.txt
only has 4 fps in MS. no need to keep watching it.
> remove z-a-recovery\.com

- watched_keywords.txt
Isn't a spam site - I've used it myself. It was watched for being used as an example of a site that had a lot of lyrics, so https://metasmoke.erwaysoftware.com/post/72014 probably shouldn't have been deleted as spam.
> removed musixmatch\.com

- spamhandling.py
Looks like the old logic would *exclude* Charcoal and post to all other rooms (sic).
Also wrapped some horribly overlong lines in the subsequent code.
Fix for https://github.com/Charcoal-SE/SmokeDetector/issues/949 (I hope).
> Attempt to fix Charcoal only for all experimental (#949)

- bad_keywords.txt
- findspam.py
I added a "Pattern-matching email" reason, which catches emails containing patterns like "spell," "hack," and "temple."  There were a few of these patterns already in `bad_keywords.txt`, so I moved them into the new reason.
> Add a "Pattern-matching email" reason

- watched_keywords.txt
This was, apparently, watched because some spammers named themselves that - https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=&username=ufuoma&why=&site=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search . All it's done so for is detect a couple FPs (https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=ufuoma&username=&why=&site=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search), as well as that there are legit users named that (https://stackoverflow.com/users/1781064/ufuoma for instance).
> remove ufuoma

- findspam.py
Pattern-matching email matched anything containing `dr`, but this caused a couple of `fp`'s because `dr` is a fairly common combination of letters.  I changed the regex to require `dr` to be at the beginning of the email (and killed Metasmoke for 2 minutes in the process).
> Require "dr" to be at the start in pattern_email

- gitmanager.py
When a pull request is being created on a user's behalf, include the number of the pull request in the chat message.
`<` You don't have code privileges, but I've [created a pull request for you](https://github.com/Charcoal-SE/SmokeDetector/pull/1017). 
`>` You don't have code privileges, but I've [created PR#1017 for you](https://github.com/Charcoal-SE/SmokeDetector/pull/1017).
(The abbreviation might be slightly bewildering to a newcomer, but it should be familiar to anyone who understands what a "pull request" is anyway.)
> gitmanager.py: Show number of generated PR in chat message

- bad_keywords.txt
The `t\Wcomplex` regex in the blacklist is prone to false positives; fix it by requiring the word boundary before the first character to not be a single quote (which is also the conventional apostrophe in plain ASCII).
> Prevent "this isn't complex" etc. from being triggered.

- globalvars.py
@NathanOliver1 recently [made a PR](https://github.com/Charcoal-SE/SmokeDetector/pull/1029) to add Makyen to SOCVR. He [still didn't get privileges](https://chat.stackoverflow.com/transcript/message/38816260#38816260), I'm assuming because of the syntax error Nathan made.
This PR _should_ fix the problem.
> Possible bug fix for Makyen privileges in SOCVR

- findspam.py
- watched_keywords.txt
Ramse Dave Loan Company (an apparent knock-off of [Dave Ramsey](https://en.wikipedia.org/wiki/The_Dave_Ramsey_Show_(radio_program))) has been used in a lot of recent loan spam, so [`ramse\Wdave`](https://metasmoke.erwaysoftware.com/search?utf8=✓&title=&body_is_regex=1&body=ramse%5CWdave&username=&why=&site=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) was already on the watchlist.  However, Ramse Dave isn't the only variation -- I've seen Ramse Dave, Ramsey Dave, and Ramsy Dave (plus the email address, `ramsedave121@gmail.com`).
I changed the regex to [`rams[ey]+\W?dave`](https://metasmoke.erwaysoftware.com/search?utf8=✓&title=&body_is_regex=1&body=rams%5Bey%5D%2B%5CW%3Fdave&username=&why=&site=&feedback=&autoflagged=&reason=&user_rep_direction= …
> Improve Ramse Dave regex, move to bad_kewords_nwb

- findspam.py
For consistency, prefer r"...\W..." over "...\\\\W..." elsewhere in bad_keyword_nwb too
(i.e. use Python raw strings with single backslashes than regular Python strings where
regex backslashes have to be doubled).
> findspam.py: bad_keywords_nwb: fix invalid escape sequence \W

- globalvars.py
HTMLParser.unescape() was supposed to have been removed in Python 3.5
(but was allegedly still forgotten in).  The canonical replacement is simply
html.unescape().  Hack it in to the parser object so the existing code can
continue to work without deprecation warnings (though it's only actually
used in 3 places; we should really avoid using a global for this eventually).
Ref: https://stackoverflow.com/questions/2087370/decode-html-entities-in-python-string
> GlobalVars.parser.unescape(): avoid deprecation warning

- globalvars.py
I accidentally added my StackExchange UserID, rather than my StackOverflow UserID.
Related pull request: https://github.com/Charcoal-SE/SmokeDetector/pull/1010
> Fix Rob's UserID for SOBotics

- watched_keywords.txt
!!/unwatch suganthan - it's causing too many false positives (in usernames)
> !!/unwatch suganthan

- Dockerfile
Update Dockerfile to use Python3 and correctly pull in dependencies.  (#1047)
Also, create a separate SmokeDetector user instead of running as root.
* Remove obsolete MAINTAINER direcive
* Ubuntu provides python3-pip so no need to separately `wget` pip
* Install SmokeDetector with a virtualenv so that `tld` can be updated by SmokeDetector
* The image starts up with `su - SmokeDetector` by default
* Optimize by using a single `RUN` directive
> Update Dockerfile for Python 3 etc (#1047)

- chatcommands.py
- Alter delete command to block deletion when run in Charcoal HQ
- Add delete_force command (`sd delete-force`)
---
This should satisfy the requirements of #1071.
Let me know if anything looks odd or if improvements are necessary.
> Implement delete_force command (#1071)

- bad_keywords.txt
Turns out the comma is a separator for multiple patterns. Edited the last line to correct.
> Fix regex for p---/d--- length --autopull

- test/test_chatcommunicate.py
- tox_tests.ini
In order for Pytest to count a file towards coverage, it has to be imported by the test. This fixes that (and will also cause a dip in coverage).
> Fix chatcommands coverage

- findspam.py
Currently mostly dots strips code blocks first, then calculates the ratio of dots to characters in the post. This causes a lot of FPs when posts have long code blocks but not much else. This change makes it so that the length of those code blocks is still factored in, just not any dots in them.
> Make mostly dots calculate length *before* stripping code blocks

- chatcommands.py
`!!/whois` currently returns weird info. For example, if you run `!!/whois code_admin` it returns `I am aware of 22 code_admin` and if you run `!!/whois admin` it returns `I am aware of 5 admin`.
With this pull request, `!!/whois code_admin` will be `I am aware of 22 code admins` and `!!/whois admin` returns `I am aware of 5 admins` which looks better and is grammatically correct.
> Add better whois return info

- datahandling.py
This fixes #1164 (the shorthand for !!/unnotify)
> !!/unnotify shorthand

- gitmanager.py
When reviewing a blacklist/watchlist PR, I often do a [global Stack Exchange search](https://stackexchange.com/search) for the keyword or URL, just to be sure the keyword isn't used in non-spam posts.  I modified the auto-generated blacklist PR message to add an SE search link.
While I was at it, I also changed the MS search link to use `urllib`'s `quote_plus`, which converts spaces to pluses and percent-escapes other special characters.
> Include an SE search link in blacklist PRs

- gitmanager.py
Replaces `\W` and `\.` with ` ` and `.` in the Stack Exchange search link in blacklist PRs, so patterns like `example\.com` link to SE searches like `example.com`.
> Replace \W and \. in the SE search link

- chatcommands.py
When`!!/report` is used on something that is previously reported, the response is 
> @XXX Post X: Already recently reported
With this PR, the message would be
> @XXX Post X: Already recently reported [MS]
With a link to the MS report.
Closes #990
> Enhance "Already recently reported" by adding MS link

- gitmanager.py
Smokey gets wedged if you blacklist or watch something while a previous Git operation is still running in CI.  Prevent that by creating a local lock directory which is removed when you pull.
The `gitmanager_lock` is probably redundant if this is accepted, but I am no longer entirely sure whether there were some other failure scenarios which it covered differently...
> Git lockdir

- gitmanager.py
This reverts commit 8fc11601664d337ee52f1b4e008b33a044e9755c.
The lockdir implementation is broken and prevents further blacklisting. Back to the drawing board.
> Revert "Guard against gitmanager clashes with a lock dir"

- gitmanager.py
Search links in the generated PR text were still wrong. Use the same expression for both Metasmoke and StackExchange search. (Both are still pretty brittle, because we are trying to convert a regex to a plain search string.)
> Neither SE nor regular Metasmoke supports regex search

- findspam.py
Exclude the main TCL site from the *.tk answer regexes.
I can find no good way to test this so just throwing a PR in the hopes that someone can validate the fix.
> FP fix for tcl.tk

- spamhandling.py
Don’t ask me why it works, but it does:
```python
>>> import regex
>>> print(regex.sub(r'([\]*`])', r'\\\1', 'a ** b ] `c`'))
=> r'a \*\* b \] \`c\`'
```
Fixes #1273.
> Fix #1273 by correcting interpolation

- findspam.py
This adds a new function called `blacklist_factory`, which acts as a wrapper that takes in a list of keywords (either `wb` with word boundaries or `nwb` without word boundaries) and transparently constructs a regex out of them and returns a function that tests a given string against it. Most importantly however, it wraps each keyword in its own named group. Then, when constructing the why data, it uses the last matched named group to retrieve which keyword was matched. A bit of a hack, but it's the best we can do without hooking into the regex engine or maybe using something like Perl's Regexp::Assemble.
Currently the `blacklist_factory` is employed for the `bad_keywords.txt` keywords, `bad_keywords_nwb`, `blacklisted_usernames.txt`, `blacklisted_websites.txt` and `watched_keywords.txt`. …
> Show which pattern was matched in the why data

- findspam.py
Case in point: https://metasmoke.erwaysoftware.com/search?body=lose+weight&site=90
Most of the Parenting.SE posts reported by SmokeDetector are trolling anyway.
> Disable health-related bad keywords for Parenting.SE

- findspam.py
This changes two things:
- replace the closure with a callable object
- instead of using named groups, construct a mapping of regular group indices to line numbers. When I tried this previously, it didn't work out because any groups in the keywords themselves would throw off the count, but now I count the number of groups in each keyword when constructing the mapping.
This went from a 2x slowdown to a little above a 1.25x slowdown.
> Optimize BlacklistFactory

- watched_keywords.txt
- refactoring `keroncong`
- toddmotto\.com removed, only FPs so far: https://metasmoke.erwaysoftware.com/domains/13296
> Watchlist maintenance

- watched_keywords.txt
No TPs yet: https://metasmoke.erwaysoftware.com/domains/13368 and many hits on stackexchange.com
> !!/unwatch toster\.ru

- chatcommands.py
- classes/feedback.py
- deletionwatcher.py
- metasmoke.py
- spamhandling.py
- tasks.py
- ws.py
This swaps out many of our short-lived threads (things like sending stats to Metasmoke) for efficient [asyncio Tasks](https://docs.python.org/3/library/asyncio.html) that run on a single dedicated thread.
The base of this is a new class `Tasks` with three methods:
- `Tasks.do`: takes in a function and arguments and schedules it to be run as soon as the thread is free (first in, first out)
- `Tasks.later`: takes in a function and arguments and schedules to be called after a certain delay in seconds (specified by the keyword argument `after=`)
- `Tasks.periodic`: takes in a function and arguments and schedules it to be called every `interval` seconds
Some examples:
Tasks.do(metasmoke.Metasmoke.send_deletion_stats_for_post, post_url, True)
Tasks.later(restart_automatically, after=21600) …
> Use asyncio Tasks

- findspam.py
Series of troll posts across Interpersonal.Stackexchange over the last couple days.
Plus, it's fairly accurate with 416 <-> 8 rate
https://metasmoke.erwaysoftware.com/search?autoflagged=&body=&commit=Search&feedback=&feedback_filter=tp&reason=&site=&title=.%2A%5C%2C%24&title_is_regex=1&user_rep_direction=%3E%3D&user_reputation=0&username=&utf8=%E2%9C%93&why=
Requested by Catija (IPS Moderator)
> Added new rule for titles that end with comma

- findspam.py
Looks like we were misled in https://github.com/Charcoal-SE/SmokeDetector/commit/c0b52fe1a35dab9ef3fcdc290754e374983edfb7 by metasmoke's natural tendency toward true positives. [It's not doing well](https://metasmoke.erwaysoftware.com/reason/140) on real data from the network. The detected posts are 3/13, and the true positives have plenty of weight without this reason (which metasmoke is still clamping to 0).
> Revert rule for titles that end with comma

- chatcommands.py
This PR implements the request for levels of deletion in #1139. Currently, all messages in CHQ have to be deleted with -force, but with this PR only reports need to be deleted with -force.
(Fixes #1139)
> del-force only for reports

- findspam.py
The `<pre>` and `<code>` tags are stripped before the code blocks themselves are stripped. Changing the order should fix this issue.
> Fix code block strip

- findspam.py
Fix the bad reason display for "repeated characters" (see [example](https://metasmoke.erwaysoftware.com/post/95895)). Also lowered the threshold for "repeated" from [11](https://chat.stackexchange.com/transcript/message/42084205#42084205) to [10](https://chat.stackexchange.com/transcript/message/42084202#42084202).
> Fix bad report for "repeated characters"

- findspam.py
Word `shit` is not being detected as offensive (it should have been). [Example here](https://metasmoke.erwaysoftware.com/post/100532).
> Fix missed offensive word detection

- blacklists.py
Automatically ignore all lines starting with a hash (treat as comments and ignore) in `blacklist_*.txt` and `bad_keywords.txt`
> Remove hash comments from blacklist --autopull

- findspam.py
Numbers shouldn't be treated as whitespace or formatting.
```
amdieb1730xhw73oxb2910
```
> Update No Whitespace detection --autopull

- findspam.py
The `\S+` detection for "no whitespace" starts to catch valid one-line answers with enough punctuation. [For example](https://metasmoke.erwaysoftware.com/post/102944). Changing to "word" (letters+digits+underscore) should solve this issue (although underscore isn't necessary)
> Improve "no whitespace" detection --autopull

- rooms.yml
See [his request](https://github.com/Charcoal-SE/SmokeDetector/issues/1545). He's already privileged in CHQ.
> +Sonic the Anonymous Hedgehog in Tavern on the Meta

- watched_keywords.txt
According to [this MS search](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=234%5B%5Ea-zA-Z0-9_%5D*%5B0-9%5D%7B3%7D%5B%5Ea-zA-Z0-9_%5D*%5B0-9%5D%7B3%7D%5B%5Ea-zA-Z0-9_%5D*%5B0-9%5D%7B2%2C8%7D&username=&why=&site=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search), the pattern `234\W*\d{3}\W*\d{3}\W*\d{2,8}` has caught 37 posts since it was added to watch. 26 of these were fps, and the remain 11 tps where also caught by another reason, so I don't think we'll miss any posts by removing it.
Note that in the search I've replaced `\W` with `[^a-zA-Z0-9_]` and `\d` with `[0-9]` to make it work on MS.
> Removing 234\W... because of fps

- parsing.py
Originally in #1554 I tried to fix `!!/report`, but it does not seem to work. Therefore, the new solution is to trim the extra characters added by SE first and then parse the id out.
> Fix report fix

- gitmanager.py
iBug requests the watch of the watch_keyword `keywords?`. See the Metasmoke search here and the Stack Exchange search here.
------
It surely looks better now.
> Add code format for the keyword

- findspam.py
https://m.erwaysoftware.com/posts/by-url?url=//expatriates.stackexchange.com/a/13069
This post was not caught by the automated filters, because it used a short URL that isn't on the blacklist.
> Add new URL shortener, per link below

- bad_keywords.txt
The "penis/dick x inches" regex at line 814 failed to catch a wingding post which used cm instead of inches (https://metasmoke.erwaysoftware.com/post/98237). This commit changes the regex to handle metric units as well as abbreviations, as well as when the length value and unit are not separated by a space.
> Update penis/dick length regex to catch more units --autopull

- spamhandling.py
The check to decide whether a message should only be posted to experimental rooms was:
if set(reasons) & GlobalVars.experimental_reasons == {}:
However, `set(reasons) & GlobalVars.experimental_reasons` is the intersection of the two sets, which equals the set of experimental reasons that caught the post.  We wanted the set of *non*-experimental reasons, which is `if set(reasons) - GlobalVars.experimental_reasons`.
Additionally, [`{}` is a dictionary literal](https://stackoverflow.com/questions/6130374/empty-set-literal); we want `set()` for the empty set.
Fixes #1455.
> Fix handling of experimental reasons

- bad_keywords.txt
Word `copula` has a lot of legitimate uses, so I removed it. See the Stack Exchange search [here](https://stackexchange.com/search?q=copula).
3 other fixes (no need for `whatever male enhancement` because `male enhancement` is already caught).
> Remove bad blacklist (autopull)

- findspam.py
Basically just removed `ejaculate` which generated a lot of FPs. Some other tweaks.
Before looking at MS results, please note that most of the TPs are spam, instead of "offensive". They should not count for this keyword.
> Fix bad "offensive keyword"

- watched_keywords.txt
Pattern generated many false positives lately: https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body=gummy&commit=Search
Blacklisted more precise pattern "cbd\W?gummy\W?bears?" instead: https://github.com/Charcoal-SE/SmokeDetector/commit/962ad6d
> Remove "gummy\W\bears?" from watchlist

- findspam.py
"Misleading link" linking to `i.stack.imgur.com` is too falsey.
See [the MS search](https://metasmoke.erwaysoftware.com/search?body=href%3D%22https%3A%2F%2Fi.stack.imgur.com&reason=139&commit=Search).
+Another minor tweak.
> Stop catching i.stack.imgur.com

- findspam.py
The [previous attempt][1] seems to have failed. See [the MS search][2].
[1]: https://github.com/Charcoal-SE/SmokeDetector/pull/1630
[2]: https://metasmoke.erwaysoftware.com/search?reason=139
> Fix missing Misleading Link FPs

- watched_keywords.txt
Too many FPs. See the MS search [here](https://metasmoke.erwaysoftware.com/search?body=sites.google.com%2Fsite)
[This](https://metasmoke.erwaysoftware.com/post/106388) is the only TP it has generated so far. All other TPs are also caught for other more accurate reasons/keywords.
> Remove sites.google.com

- watched_keywords.txt
it's a legitimate site and not an indicator of spam.
> remove hashflare\.io from watchlist

- chatcommands.py
- parsing.py
#1554 seems to have failed because it's wrong. Smokey receives the actual invisible characters instead of the HTML-encoded ones. See tests starting from [this message](https://chat.stackexchange.com/transcript/message/43369764#43369764).
[Most recent occurrence](https://chat.stackoverflow.com/transcript/message/41585835#41585835) by Bhargav Rao
[The analysis of the message](https://chat.stackexchange.com/transcript/message/43368641#43368641#
> Attempt to fix the bad URL parsing in !!/report's

- chatcommands.py
the specific HTTPError that needs to be caught comes from `requests.exceptions`, so this PR specifies that in the code.  autopull
> Fix blame2 command

- chatcommands.py
The specific HTTPError that needs to be caught comes from `requests.exceptions`, so this PR specifies that in the code. `requests.exceptions.HTTPError` is spelled correctly this time
> Fix blame2

- bodyfetcher.py
AU is by far the most spammed site outside of SO. It was also hit by a troll recently. There is enough spare API calls to use queue size 1 for AU (doubling the number of requests to it). 
Also: since "time sensitive" category means that queue size drops to 1 between UTC 4 and UTC 12, the sites that have queue size 1 already need not be in that category, it's redundant.  
Finally, writers.SE is now writing.SE, the old name still works for the API but will not match the new site name provided by websocket connections.
> AU should be a special case with queue size 1

- findspam.py
In phone numbers, these may be used for obfuscation.  Example: https://metasmoke.erwaysoftware.com/post/111204
> Detect l and | as substitutes for 1

- metasmoke.py
Currently only fp feedback from chat will remove the user from the blacklist. With this PR, if someone marks a post fp in MS (via the API or review), the user will be removed from the blacklist too.
> remove blacklist if fp from MS (incomplete)

- findspam.py
A user named Keshav has just posted [a bunch of anti-Semitic content](https://metasmoke.erwaysoftware.com/search?utf8=✓&title=&body=&username=keshav&why=&site=98&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search) to Mi Yodeya.  The username has many false-positives on other sites, but none on Judaism.SE.
> Blacklist username "Keshav" on Judaism.SE

- findspam.py
Now the "Messaging number" regex also matches the posts 
https://metasmoke.erwaysoftware.com/post/114005
https://metasmoke.erwaysoftware.com/post/114006
https://metasmoke.erwaysoftware.com/post/114007
that were not caught.
> WhatsApp number may be preceded by +

- chatcommands.py
Custom reporting syntax would then be:
`!!/report url1 [url2 url3 ...] ["Custom Reason"]`
... where both custom report reasons *and* more than one URL are both optional.  This allows for the following 4 command syntaxes to work:
```
!!/report url
!!/report url "Custom Reason"
!!/report url1 url2 url3
!!/report url1 url2 url3 "Custom Reason"
```
... where for batch reports they *all* get the same 'custom reason' for each report generated by the batch, and also supports the original "Manually reported" reason without subsequent details as well.
The original "request" for this feature is in #1965, but this needs approval from at least Undo or Art, as well as a third set of eyes before we consider including.
> Add custom reporting reasons for manual reports. (#1965)

- watched_keywords.txt
This was supposed to be a non-capturing group that was missing the question mark:
`(:yo)` was supposed to be a non-capturing group, but is missing the `?`. Fixed that in the PR.
> Fix Missing Question mark

- findspam.py
This is an attempt to decrease fp's when a legitimate word starts with 'fag', such as in a recent FP: Fagnano's.
See the relevant MS post: https://metasmoke.erwaysoftware.com/post/115362
This may actually find more TP's than originally designed: old method wouldn't catch something like:
faaaag, while simultaneously catching less FP's by utilizing a word boundary on the end. No boundary exists in this update at the start of the word - we can adjust if necessary.
> Update: fag(g?ot)?   -->   fa+g+(ot)?s?\b

- blacklisted_usernames.txt
We are getting a lot of fp's on words that contain `fuk\w*`. Essentially the largest part of this fix is that it forces word boundaries so something like **Fukuda** won't be caught. But because we are adding word boundaries, I updated to catch varieties of the usage.
**NSFW:** https://regex101.com/r/vU7McB/1
> Updated username-blacklist for fuc?k

- watched_keywords.txt
Smokey created two watchlist entries for some reason, [apparently in response to one command](https://chat.stackexchange.com/transcript/message/44073072#44073072).
> Remove duplicate watchlist entry

- watched_keywords.txt
The regex `(nice|useful|good)\W?(article|answer|blog)` is intended to catch blogspam, but "good answer" causes [a lot of fps](https://metasmoke.erwaysoftware.com/search?utf8=✓&title=&body=good+answer&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search).  This PR removes "answer" from the regex.
> Unwatch "good answer"

- chatcommands.py
- classes/_Post.py
- globalvars.py
- parsing.py
- spamhandling.py
Sanitize post titles in markdown posts, which were not properly escaped (sometimes escaped twice, sometimes not at all).
See https://chat.stackexchange.com/transcript/11540?m=44097072#44097072 and https://chat.stackexchange.com/transcript/11540?m=44097075#44097075 for examples of the problem.
This pulls the sanitation out into a separate method that can be called from all locations where it is required in the same way.
Also fix some warnings from PyCharm's code analysis.
> Post title sanitize

- findspam.py
Refactor bad_ns_for_url_domain to an anlysis function ns_for_url_domain
and two caller functions which call it with different lists of nameservers
> findspam.py: watch_ns_for_url_domain

- blacklisted_usernames.txt
We've seen a couple FP on this blacklisted username in the past few days. This tightens it up to catch all the TP we've seen in the last 3 months. With this adjustment it does miss 1 post from 9 months ago and 3 from 2 years ago, but those appear to be incidental to what this is primarily attempting to catch.
[Search with old blacklist entry on MS](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=&username_is_regex=1&username=%28%5E%7C%24%7C%5CW%29virk%24&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search)  
[Search with new blacklist entry on MS](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=&username_is_regex=1&username=%28%5E%7C%24%7C%5CW%29%5Cw*%5Cd%2B%5CW%2Bvirk%24&why=&site=&post_ …
> Tighten Virk blacklisted username to avoid FP

- bad_keywords.txt
- watched_keywords.txt
Detection is down to 17/9/0, which is 68%.
If we count only what we've seen in the last year, then it's 7/8, or 46.7%.
This watch has been solely responsible for two autoflagged false positives (detected in title and body).
Basically, it's accuracy has fallen far below what we need for the blacklist.
[Here is a metasmoke search for this regex](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=%28%5E%7C%24%7C%5CW%29alibaba%5CW*cloud%28%5E%7C%24%7C%5CW%29&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search).
There's a [meta post](https://meta.stackoverflow.com/q/363423) about Alibaba Cloud being used for spam seeds.
> Move alibaba cloud from blacklisted keywords to watchlist

- helpers.py
- test/test_helpers.py
`api_parameter_from_link` incorrectly returned `stackoverflow` for localized SO sites and their metas.  I fixed the bug by modifying the `parser` regex to allow optionally two word characters followed by a dot before "stackoverflow."
In order to make Metas work, I removed `meta.stackoverflow` from the exceptions list and excempted sites containing "stackoverflow" from being reversed as is usual for Meta sites.
Fixes #2161.
> Fix api_parameter_from_link for localized SO

- blacklisted_websites.txt
- watched_keywords.txt
This site does not qualify for inclusion in the blacklist.
This site, urlopener.com ([metasmoke search](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=%28%5E%7C%24%7C%5CW%29urlopener%5C.com%28%5E%7C%24%7C%5CW%29&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search)), has only 2 TP, which are from 2 years ago. It recently picked up an FP, which was reported 3 times. Even discounting the FP, it doesn't have enough TP to justify being on the blacklist. With the FP, it's TP rate is 66.7% (counting all FP as one report). If we count all the FP reports of that one post separately, then urlopener.com's TP rate is only 40%.
> Move urlopener\.com from URL blacklist to watchlist.

- bad_keywords.txt
The \W? has resulted in 11 FP ([MS search](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=%28%5E%7C%24%7C%5CW%29D%5CW%3FBal%28%5E%7C%24%7C%5CW%29&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search)) while `d\W?bal` has been active in the blacklist. It was [initially added](https://chat.stackexchange.com/transcript/11540?m=43306031#43306031), but then removed by PR #1763 as a result of issue #1757 (too many FP). It was later [re-added as `D\W?Bal`](https://chat.stackexchange.com/transcript/11540?m=44474453#44474453).
Changing to `D\W+Bal` ([MS search](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=%28%5E%7C%24%7C%5CW%29D%5CW%2BBal%28%5E%7C%24%7C …
> Tighten D-Bal blacklist

- chatcommands.py
As discussed in #2177, use `content_source` to get the message plaintext when blacklisting.  Prevents Markdown characters such as asterisks from being turned into HTML tags.
> Use raw message text when blacklisting/watching

- bodyfetcher.py
We've been getting quite a bit of trolling on four sites: Buddhism, Judaism (Mi Yodeya), Islam and Hinduism. Islam and Hinduism were previously lowered to a queue of 1. This lowers the queue depth on the other two sites to 1 also. The impetus for doing so is that we've had people running a manual `!!/scan` on 5 posts on Judaism today. I've also included Buddhism to provide it a similar level of scanning.
> Reduce queue to 1 on Buddhism and Judaism

- helpers.py
My bad for not noticing that `https://` is stripped before the URL is sent to the function.
Should be fixed now.
> Fix uid/site/None being generated

- bad_keywords.txt
Just `adelina` is getting [some (7) FP on usernames](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=&username=Adelina&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search).
There are [another 17 posts on on SE](https://stackexchange.com/search?q=adelina) which would be detected due to the word being in the post body (or so, some hits in this search are duplicates).
Tightening the regex to:
adelina(?:(?:\W*(?:skin|anti\W*aging))?\W*cream(?:ing)?|\W*skin\W*care|\W*revitalizing\W*moisturizer)
avoids all of the FP we've seen, while still catching all the TP we've seen.
With the updated regex:
[MS search as body (17)](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body_is_regex=1&body=%28%5E%7C%24 …
> Tighten bad keyword for Adelina to avoid FP

- blacklisted_websites.txt
- watched_keywords.txt
Per discussion started by @Videonauth [here](https://chat.stackexchange.com/transcript/message/44915752#44915752).
Some research results [here](https://chat.stackexchange.com/transcript/message/44916041#44916041), which show that it's 4/3/1 with two of the TP having conflicting feedback.
There are also [61 hits](https://stackexchange.com/search?page=1&q=url%3acode-industry.net) on SE (tends to show duplicate hits).
I'm not sure that this even deserves a watch at this point, but...
> Demote code-industry\.net to watchlist

- bad_keywords.txt
- blacklisted_usernames.txt
- watched_keywords.txt
Blacklisted usernames: 
* Remove extraneous Unicode Left-to-right Override characters that were at the end of a few usernames. Comparing searches on metasmoke and the listed detections indicate this prevents matching (i.e. these changed blacklisted usernames were not effective).
Blacklisted Keywords:
* Account for searches being bookended by `\b`. When searching for characters from languages other than English (i.e. using non- \w characters) a `\W*` is needed to consume all \W characters up to a `\b` word break.
Comparing searches on metasmoke and the detections listed for various TP posts indicated in each case this prevents matching (i.e. these changed blacklisted keywords were not effective). There were some few cases for a couple words where these did match correctly on a couple TP, …
> Account for searching for non-\w characters; remove unintensional non-printing characters

- gitmanager.py
This makes it more easy to determine *why* git fails if it doesn't fall into one of the already-caught categories of Git errors we capture.  Unspecified git problems in the code will not result in a crash, but will now spit out error data with a timestamp to the errorLogs.txt file with these changes.
> Allow 'unspecified' git failures to be logged to errorLogs.txt.

- chatcommands.py
because we are lazy and shorter commands are better.
> added 'live' and 'errlogs' aliases

- chatcommands.py
We have 'errlog' now, but not 'errorlog' which is a common typo that (at least I) regularly make when trying to access error logs.  So let's add that in there while we're at it.
> Add 'errorlog' alias

- chatcommands.py
- metasmoke.py
So far if anyone manually reports a post via MS API, there's no post analysis given in the "why" section, which is very different from when a post is reported via chat.
This PR just adds the analysis to posts reported via MS, and a few patches to other parts of the code base.
> Show reasons for posts reported via MS

- findspam.py
[This post][1] could've been caught by the reason and thus, autoflagged. Fix by removing white spaces before comparing.
[1]: https://metasmoke.erwaysoftware.com/post/123116
> Improve "body starts with title" detection

- watched_keywords.txt
Remove watches missing a `?`. Remove duplicate watch created by SD taking the original version of the message, not the edited version (not sure why that happened).
> Cleanup my recent !!/watch commands.

- datahandling.py
Solar Flare died unexpectedly today with an unpickling error regarding pickle data being truncated.  The only way to recover from this failure was to remove the offending pickle file, and restart the SmokeDetector instance.
We already restart Smokey on an unhandled exception such as this unpickling error, but because this issue persisted until we removed the file in the Solar Flare instance, and it caused a constant crashing problem/loop because a specific pickle had data truncated, it's better to capture this error and handle the pickle as we would an EOFError, which would remove the file and raise the error, triggering another restart without causing a constant crash loop like Solar Flare was having.
> Better handle 'pickle data was truncated' unpickling failures.

- findspam.py
- helpers.py
I think [I've resurrected][1] the "pattern-matching product name" reason. See [this example][2].
Since it's been left alone for a long time without maintenance, we can probably utilize this reason by updating the keywords list so it catches more recent spam. I have added and changed a few keywords according to the [latest "blacklisted website in title" posts][3]. I'd like to know what else we can do about this reason.
[1]: https://github.com/Charcoal-SE/SmokeDetector/commit/9eccdd5e62c60c61b1e8feb6d788e05c3f0f11af
[2]: https://chat.stackexchange.com/transcript/message/45169071#45169071
[3]: https://metasmoke.erwaysoftware.com/reason/61
> More keywords for "pattern-matching product name"

- gitmanager.py
- globalvars.py
This would be a better solution to the broken chat messages caused by special characters in commit messages than escaping them. However I'm not sure if Smokey's commit message format is important (will break userscripts, etc.).
> Wrap commit messages in code blocks

- findspam.py
Currently "writing service" in link text is reported, but "writing help" is not. This expression comes up too:
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=writing+help&username=&why=&site=&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search
> Detect "writing help" in link text

- watched_keywords.txt
```
maleenhancement.{1 7}\..{2 4}
```
I have never learned a syntax like this, and according to my experiences, I suppose it should look like this:
```
maleenhancement.{1,7}\..{2,4}
```
Should it be fixed?
> What is this regex?

- flovis.py
We have an observed problem with Flovis where the socket is sometimes closed without any other errors, and then trying to use the socket triggers a `WebSocketConnectionClosedException` error.
This may be because we don't have a mechanism to reinitialize the Flovis socket on these errors.
This PR includes my proposed changes to the Flovis code so that if we stage something to Flovis, we don't get a crash, or rather, reinit the websocket and retry if the Flovis socket is already down.
We could probably expand this to fix the SSL problem as well, but that's a different issue for a different time.
> Flovis: Fix unhandled "Socket already closed" errors.

- chatcommands.py
- test/test_chatcommands.py
The `!!/scan` command currently only scans one post per message. It's more convenient to scan more messages in one message. Results are either given as reports (problem found) or squashed into one single chat message.
This is a preparation for implementing #2289. I'll start implementing that after this one is done and merged.
> Scan multiple URLs with one chat message

- chatcommands.py
- gitmanager.py
New command `!!/unblacklist`. Removes an item from the three blacklist files. This would be useful when people think a blacklisted item generates too many FPs.
Same as `!!/unwatch`, code-admins only, no PR.
There was originally an idea about something like `!!/demote` that moves a blacklist item to watchlist, but I've decided to suspend it after evaluating the difficulty of implementing it over the current code base.
> !!/unblacklist command

- chatcommands.py
- helpers.py
- spamhandling.py
- test/test_chatcommands.py
#2289 is a good idea. I had thought of it several times before but didn't bring it up.
This PR basically just implements what's proposed in #2289, with the following changes:
- `!!/scan` gets merged into `report()` as an alias
- `!!/report` acts the same as `!!/scan` if the given post is determined as spam
- `!!/report` falls back to original "report" if the post isn't caught, while `!!/scan` will tell you "it doesn't look like spam"
- New command `!!/report-force`, which as intuitive as its name suggests, skips the "scan first" and acts exactly like the original `!!/report`, with scan analysis supplied in the `why` section
- A new `to_metasmoke_link` function that simplifies code and increases maintainability. More uses of this function ~~will come up in another PR or be pushed directly …
> Force scan with !!/report, merge !!/scan in

- chatcommands.py
- gitmanager.py
If MS is down we get a connection error problem.  When that happens, we should force code_permissions to be False.  However, to get the proper chat reply that MS is down and a PR made because we can't determine if someone is code privileged or not, we need a metasmoke_down tracker in the 'add to blacklist' function so we can determine which chat reply to send.  This way, we can make PRs if MS is down and we can't determine if someone has code privs.
However, the same can't be said about unblacklist.  It doesn't have PR-branch-creation functionality at all.  So the best we can do is fail with a specific error message.  unblacklist/unwatchlist will need refactored to be able to do that functionality before we can force PRs if someone isn't code-priv'd.
> Adapt for MS downtime in (un)blacklist/watchlist commands/replies

- spamhandling.py
See https://chat.stackexchange.com/transcript/message/45508505#45508505 and https://chat.stackoverflow.com/transcript/message/43164457#43164457
This is a workaround by detecting if the `why` text starts with `Post manually`, which should always be the case if the post is manually scanned/reported.
> Ignore experimental reasons if the post is manually reported

- findspam.py
The Python `\b` assertion matches `^\w` and `\w$`, but it doesn't match `^\W` and `\W$`. If we want to have blacklist and/or watchlist entries which are able to match the beginning or end of the body (and/or titles and usernames when looking for `\W` characters), then we need to bookend the matches with `(?:^|\b)` at the start and `(?:\b|$)` at the end, rather than just with `\b` on both sides.
Documentation: [6.2.1. Regular Expression Syntax](https://docs.python.org/3/library/re.html#regular-expression-syntax)
> Allow the watchlist and blacklist to match the start and end of strings

- findspam.py
- test/test_regexes.py
See #2217
I was quite resistant about doing this before I noticed that Python has `str.encode('idna')`. So I just happily did this. URL-decoding is also involved in the post mentioned in 2217 so I added support for it, too.
> Don't catch IDNA domains as "misleading links"

- spamhandling.py
To fix [messages with \\, \[ and \] in the link name](https://chat.stackexchange.com/transcript/message/45561684#45561684).
> Escape markdown link name

- gitmanager.py
Attempt to fix #2219 by checking for duplicates on `master` instead of `deploy`.
> Test blacklist integrity before commit

- globalvars.py
- requirements.txt
`dulwich.repo` is only used once for obtaining Git commit information, which can well be replaced with a subprocess call to CLI `git-log`.
> Drop requirement of dulwich

- config.sample
- globalvars.py
- ws.py
In addition to loading CE creds from environment variables, this enables the loading from local `config` file. If both are present, the ones defined in environment takes precedence, so this does essentially nothing to running instances.
As a downside, I removed asking for input via `input` and `getpass` as it causes confusion.
Previously CE cred is asked in both `nocrash.py` and `ws.py` if it's not found. It can be confusing if one is present in `config` but still asked from input, because `nocrash.py` does not load config. There were two options available:
1. Load `config` in `nocrash.py` and suppress terminal input if cred is found
2. Totally drop terminal input for cred
To keep things simple, I picked 2, because `nocrash.py` is a replacement for `nocrash.sh` and does not depend on any …
> Load ChatExchange credentials from config file

- chatcommands.py
- globalvars.py
- metasmoke.py
MS gets down from time to time and it throttles Smokey a lot because communication with MS runs on the main thread.
This approach does these:
> [Pending Test] Detect if MS is down and disable it

- findspam.py
- watched_keywords.txt
illuminati is 85/0 (tp/fp)
vampire is 26/0 (tp/fp)
They've both been on the watchlist for 3 months. However, the `vampire` is being changed to `vampire?` in order to catch more recent examples.
> Move "illuminati" and "vampire" pattern-matching email into findspam.py.

- regex_proxy.py
We're compiling the same regexes repeatedly in various places. It can be a little hard and complicated to fix all of them into reusing the compiled regex object. Here's another approach by wrapping up the `regex` module and make `regex.compile()` cache regexes on its own. This way minimal changes to the source is required. We only need to replace `import regex` with `import regex_proxy as regex` with 100% compatibility.
I want some reviews before pushing this.
> Wrap up the regex module and make a global cache

- metasmoke.py
Implement as requested in message https://chat.stackexchange.com/transcript/message/46883691#46883691
Example text: `Post manually reported by *user*.`
> Provide username of reporter when reporting in API

- bodyfetcher.py
The site formerly known as Health is now Medical Sciences, but bodyfetcher has the old URL.
> health was renamed as medicalsciences

- test/test_findspam.py
https://github.com/Charcoal-SE/SmokeDetector/blob/8b5d6e5cc1e728d8d2e78c053e4def548a9d07e5/test/test_findspam.py#L108
```python
>>> "Expected {1} on {}".format('body', 'expected_spam')
Traceback (most recent call last):
File "<input>", line 1, in <module>
ValueError: cannot switch from manual field specification to automatic field numbering
>>> "Expected {1} on {0}".format('body', 'expected_spam')
'Expected expected_spam on body'
```
> Fix string formatting error

- flovis.py
https://github.com/websocket-client/websocket-client/blob/efcf31b30122e05701fb3f696b029baf8faa6d8e/websocket/_exceptions.py#L29-L33
https://github.com/websocket-client/websocket-client/blob/efcf31b30122e05701fb3f696b029baf8faa6d8e/websocket/_exceptions.py#L50-L55
```python
>>> class WebSocketException(Exception):
...     """
...     websocket exception class.
...     """
...     pass
... 
... 
... class WebSocketConnectionClosedException(WebSocketException):
...     """
...     If remote host closed the connection or some network error happened,
...     this exception will be raised.
...     """
...     pass
... 
... 
... try:
...     raise WebSocketConnectionClosedException
... except WebSocketException:
...     print('caught here')
... except WebSocketConnectionClosedException:
... …
```
> Modify order of except clauses

- globalvars.py
disk-partition.com has been in and out of the blacklist repeatedly. It should not be blacklisted.
Add disk-partition.com to GlobalVars.valid_content so as to trigger the "too broad" check if someone attempts to blacklist it again.
> Effectively blacklist blacklisting disk-partition.com

- chatcommands.py
- chatcommunicate.py
- datahandling.py
- rooms.yml
- test/test_datahandling.py
Implements and closes #2511, the Smokey Pickle Transfer Protocol
It should pack selected data into a `dict` and pickle that dict, then compress the pickled data to reduce size, and base64-encode the compressed data so it's suitable to be posted as a chat message. A header line and an ending line similar to PGP armored data are also added. A loader function does the reverse thing, with some data validation in place.
Example data (try to break the CI test and it'll show up in stdout):
```
-----BEGIN SMOKEY DATA BLOCK-----
eNpVjz1OAzEQhfOz/BOh3MAdKVDEbgjJFhSIAkU+AUUUeXfH6xEbG63HiShAFCiV
O8zVOAo1m6RipCnme6On9z6i77t2azdvYeBPFksgUQgSYXtGhEsIj/c/v18Xq893
f1yZXBAaHfzTg9GE2hln2UwTlPVOGLKZZK/GXdbALADqkpFCe8XyGgQBEyw3WmLJ
JFbA1kiKWaGbX3JSMtQMKfhuDavgByJNiySB0TQdJ9Miza7jOE7GtyIdT+BGTmEi …
```
> Smokey Pickle Transfer Protocol

- chatcommands.py
- gitmanager.py
- test/test_chatcommands.py
This time it's just that I have a feeling this would be useful. E.g., when either MS or PullApprove is down.
Code-privileged users can issue a command `!!/approve 8888` to approve pull request 8888. Necessary checks are performed before doing any Git operation. The checks include
- User is code-privileged
- The PR is created by Smokey itself
- The PR contains a valid description as used by MS
Operation for merging PR:
```
git checkout master
git fetch origin +refs/pull/8888/merge
git merge FETCH_HEAD --no-ff -m "Merge pull request #8888 from Charcoal-SE/{} --autopull"
git push
```
The fetch command is taken from Travis CI build logs (Travis builds PRs in that way), I have tested it briefly and it seems OK.
If you're wondering how can Smokey merge conflicts, read more >>> …
> Make an !!/approve command to merge PRs

- rooms.yml
During a concentrated June/July spam wave, Smokey was moved to a separate overflow chat from the main RPG General Chat room. Now that the spam wave has died down we can move Smokey back to RPG General Chat.
(I'm one of the RPG.SE diamond moderators.)
> Move Smokey back to RPG General Chat

- metasmoke.py
Update the filter used for the /posts/urls endpoint when fetching data for the `autoflaged` command.
Adjust the logic to use the oldest report for the URL, which is the only one that will be autoflagged.
> autoflagged command update filter & use first report

- findspam.py
This reduces the non-TP for this entry by 50% without missing any of the TP.
[Search on MS for current entry](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=%5Cbnutra): 765/719/41/3
[Search on MS for updated entry in this PR](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=%5Cbnutra%28%3F%21l%28%3F%3A%7Cy%7City%7Ci%5Bsz%5Ding%7Ci%5Bsz%5Ded%3F%29s%3F%5Cb%29): 743/719/22/0
> nutra in bad_keywords_nwb: reduce non-TP by 50%

- findspam.py
This detection was [modified 3 months ago](https://github.com/Charcoal-SE/SmokeDetector/commit/a9ab576031737d8baed61b8750a53c3939a69467#diff-0763921f6af04c4a434786e1674a91c9L1127). Since then, it's had 7 FP and 1 TP, which is nowhere close to what's needed in a blacklisted item.  Even exempting es.stackoverflow.com would have resulted in 1 TP and 1 FP, which also doesn't justify a blacklist.
Prior to the change 3 months ago, the detection was broken. The regex used `\bgratis\b$`, which will never detect anything in bodies, due to SE never ending a post with text, but will detect in titles. However, even if we look at [just that detection in titles](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title_is_regex=1&title=%5Cbgratis%5Cb%24) it would be 2 TP and 3 FP, which again …
> Move gratis to watch and exempt es.stackoverflow.com

- watched_keywords.txt
For those posts found during the time it was being tested, the change to the already added updated version should reduce total FP and NAA to 40% of what they were.
This is being removed via a PR, because SD didn't permit me to `!!/unwatch` this entry. It [claimed the entry did not exist](https://chat.stackexchange.com/transcript/message/47966424#47966424).
> Remove 1st version of watch testing link at start of post.

- findspam.py
Currently the "why" text for a post only contains two information: the keyword and the aspect of the post (title, body or username). This change replaces the "aspect of post" with "reason caught", so people can more easily figure out which reason caught which keyword
Compare:
```
Body - Position 3-14: weight loss
Body - Position 3-20: weight loss pills
```
```
Bad keyword in body - Position 3-14: weight loss
Pattern-matching product name in body - Position 3-20: weight loss pills
```
This is going to be particularly helpful when trying to determine "blacklisted website" vs. "pattern-matching website", as the latter often generates "truncated" text ([example](https://metasmoke.erwaysoftware.com/post/155649)) and confuses people.
> Generate more detailed "why" output

- findspam.py
This creates a whitelist - ASN_WHITELISTED_WEBSITES - and modifies
the asn_for_url_host() check to shortcut if `hostname' is on the
whitelist.
There are a few sites which were causing fp's because they
happened to come under a watched ASN. Some will be used on
particular sites more than others (eg [thefreedictionary on
ELL/ELU](https://metasmoke.erwaysoftware.com/post/160036), docs.unity3d.com on Game Dev).
Mentioned in chat, Makyen suggested a simple static list:
https://chat.stackexchange.com/transcript/11540?m=49080625
Top 20 hosts watched with ~178 MS records between them at
time of creation.
ASN fp search (MS):
https://metasmoke.erwaysoftware.com/data/sql/queries/164-bad-asn-in-false-positives
> Add whitelist for ASN checks

- blacklisted_websites.txt
v.ht currently has a high inaccuracy rate, and catches posts such as [this one](https://metasmoke.erwaysoftware.com/post/168765) where the URL contains an HTML file that ends with `v` (`https?://.*v\.html`). Prefixing the watch with `//` removes all the false positives.
It does also exclude 10 true positives that were caught for the same reason as several of the false positives: HTML file ending with v. These 10 posts can be viewed [here](https://metasmoke.erwaysoftware.com/search?body=%28%3F%3C%21http%3A%2F%2F%29v%5C.ht&body_is_regex=1&feedback_filter=tp&utf8=%E2%9C%93). I've also put up various watches for other patterns seen in the post as well, so this shouldn't reduce coverage
> Fix watch for v.ht

- rooms.yml
Creating a PR for visibility.
SOCVR room owner, over 1000 feedbacks in Metasmoke (1.13% invalid but none in the last month).
> Add Stephen Kennedy to Charcoal HQ

- findspam.py
These changes were prompted after [Samuel Liew](https://stackoverflow.com/users/584192/samuel-liew) flagged [this](https://metasmoke.erwaysoftware.com/post/170959) post for admin attention after it recieved 4 autoflags due to the title alone (!!!). After some investigation of our checks, it became clear that we have a fair bit of overlap between many of the rules.
Changes performed: 
Any posts caught by this rule will *always* be caught by other existing reasons: mainly 'repeating characters in title', but also 'mostly punctuation in title', or 'mostly dots in title'. As such, this reason is artificially inflating the reason weight of many posts by 95. This is the main reason that the aforementioned post was incorrectly autoflagged (without it, the reason weight would have been only 121, …
> Rebalance checks for trolling-type spam

- chatcommands.py
fix https://github.com/Charcoal-SE/SmokeDetector/issues/2398
> added async comment call on report post call

- spamhandling.py
- test/test_spamhandling.py
This adds handling for #3321.
If the 'offensive title detected' reason is detected when handling a spam post, the built message will not feature the post's title, but instead `(Potentially offensive title -- see MS for details)`. A test has also been added to verify this behavior.
One question: I took a quick look, but are there any other reasons that should cause the post title to be left out of the message?
> Don't post the title in chat when it's been identified as offensive

- nocrash.py
Discussions today in Charcoal HQ were in favor of doing enforcement of Python version 3.5.0 or newer for the use of SmokeDetector.
In this implementation, we adjust the static-defined tuple `(3, 5, 0)` to the version we want to define as "minimum supported" - in the case of Python 3.7.4 if we wanted this to be enforced as needing that version we would have `(3, 7, 4)` for the Tuple comparison.
This also includes a singular no-op for line length on a comment underneath it; this is, however, a no-op that has no other functional bearing.
All SmokeDetectors on this using nocrash.py may need to be manually restarted to get this change.
> Enforce Python >= 3.5.0

- .pullapprove.yml
- chatcommands.py
- gitmanager.py
Ref: Charcoal-SE/metasmoke#682, Charcoal-SE/metasmoke#683.
Surprisingly few changes actually required in Smokey code to make this work. I haven't tested this, because I don't have a live instance available at the moment, but I have replaced or discounted all instances of `code_admin`. Code privilege checks come via the metasmoke v1 API, which should still return the correct results because its backing has been updated by metasmoke#682.
PR'd for sanity checking.
> Change code_admin to blacklist_manager

- chatcommands.py
There's only singular for the blacklist manager role, which results in [this](https://chat.stackexchange.com/transcript/message/52254964#52254964) chat message.
> Use plural when blacklist managers are 2 or more

- chatcommands.py
Replace:
with:
in GH messages by SD when a PR is approved from chat.
> Change code-admins|approved label to blacklisters|approved

- findspam.py
I propose adding this TLD to the list of domains we always flag.
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=%5C.ae%5Cb&post_type=answer indicates 87/95 where 3 of the 4 TPs are more than a year old.
> Add .ae to pattern-matching TLD rule

- chatcommands.py
Currently, it looks like [this](https://chat.stackexchange.com/transcript/message/52786635#52786635).
> Add backticks to commands and a missing space

- findspam.py
Ping @iBug -- this was committed in https://github.com/Charcoal-SE/SmokeDetector/commit/3912c669f5332a784572b4b08b8271bdf426506a apparently by accident?
> The COUNTRY list was initialized but never used for anything

- helpers.py
This patch includes the following fixes / improvements for the link unshortener helper
- Use GET requests
Some link shortener servers reject HEAD requests or otherwise disregards the W3 specs for HEAD requests by returning something different (e.g. 200 OK, try `curl -I https://t.cn/blahblah`)
- Limit maximum redirect chain length
Previous code would block if any url(s) in the chain loops and this function will unfortunately run forever. Now raises an exception instead. Default depth is 10 which should cover 99.9% of them. For reference, most browsers stop after 20 or so (see [this Stack Overflow answer](https://stackoverflow.com/a/36041063/5958455)).
- Allow arbitrary HTTP method (body is always discarded)
Now that the response body is discarded (credits to [this …
> Improve link unshortener function

- chatcommunicate.py
- rooms.yml
- spamhandling.py
In rooms.yml under `msg_types`:
* Change `experimental` to `experimental-all-sites`, which indicates that reports with only experimental reasons will be sent to the room for all sites.
* Add `experimental-site-<site domain>` (e.g. `experimental-site-stackoverflow.com`). This is similar to the format of the `site-<site domain>` entries which already exist.
* Change `all` to `all-sites`, so it's clearer the setting indicates the room accepts reports for all sites. "All sites" is the current actual meaning of `all`. Unfortunately, `all` within `msg_types` could be interpreted in various ways. Personally, when I see just `all`, I assume it means that the room should receive every single chat message type, not that it means just "all sites".
Implements #3768
> Per-site "experimental-site-<site domain>" setting for rooms.yml

- blacklisted_nses.yml
- blacklists.py
- test/test_blacklists.py
- watched_nses.yml
This adds a test case to check the YAML lists for some simple problems.
Testing revealed a number of issues which are also solved with this PR.
- Embarrassing typos in a regex
- Embarrassing typos in a couple of watched NS entries
- Comment out a number of stale NSes which no longer resolve
The commented-out entries should probably be removed eventually, but some of the issues may be transient, so I want to keep them around and revisit them in a few weeks.
> YAML validation

- blacklists.py
- test/test_blacklists.py
This should fix #3793 as it now handles and catches upon the unhandled `dns.resolver.NoNameservers` error that was breaking CI when DNS SERVFAILs are encountered.
> Reenable DNS tests, catch on dns.resolver.NoNameservers (fix #3793)

- findspam.py
Also refactors URL shorteners so they are only defined in one place.
#3720 asks for /forms/ but I am not including that for now; see comment in the ticket.
> Exclude goo.gl/maps/ from URL shortener (#3720)

- metasmoke.py
According to [this](https://github.com/Charcoal-SE/SmokeDetector/pull/3850#issuecomment-629596302) message
Implemented multiple retries to initiate MS websocket rather than only one attempt. Also implemented logging when initiation failed.
> Multiple retries to initiate MS websocket

- metasmoke_cache.py
According to issue #3631 
Added exception handler in generator() and fetch().
The handler in generator() will log the exception, and re-raise it
The handler in fetch() will terminate fetch() and return None, 'MISS-NOGEN'
This change may help to solve the problem, as the log message provided [here](https://chat.stackoverflow.com/transcript/message/48175386) indicates that the problem was caused by an uncaught exception repeatedly terminating SD, and hence triggering reversion before request_sender() in metasmoke.py was able to turn off MS.
> Catch exceptions in generator and fetch

- chatcommands.py
Adjusted async comment call to actually post the custom reason for reporting.
Potentially fixed issue #3874
> Adjusted async comment call on report post call

- bodyfetcher.py
- chatcommands.py
- globalvars.py
- metasmoke.py
Added lock protection to metasmoke.py and chatcommands.py regarding to the read operation of apiquota from GlobalVars.apiquota. The lock may be needed as the write operation in bodyfetcher.py may not be atomic, and hence without lock, half-written and corrupted data may be read - the same reason why metasmoke.py in method send_statistics acquired posts_scan_stats_lock before reading post scan statistics.
> Added lock protection

- chatcommands.py
- requirements.txt
- tox.ini
- ws.py
As the title says
New complaints (from 3.6 to 3.8):
```text
./chatcommands.py:1336:17: E741 ambiguous variable name 'l'
./chatcommands.py:1341:20: F523 '...'.format(...) has unused arguments at position(s): 0
./chatcommands.py:1346:20: F523 '...'.format(...) has unused arguments at position(s): 0
./chatcommands.py:1350:13: E741 ambiguous variable name 'l'
./ws.py:50:21: F523 '...'.format(...) has unused arguments at position(s): 2
./findspam.py:1220:9: E741 ambiguous variable name 'l'
```
F523's are fixed, while E741's are ignored (we're using lowercase L as variable names for a good reason, could fix but not interested).
> Upgrade Flake8 to 3.8

- chatcommands.py
Append location of the rebooting instance to the start of the rebooting message posted.
> Adjusted rebooting message to avoid confusion

- chatcommands.py
Added comments for threads, so next time someone runs this command, they do not need to figure all this out again.
"message sender" is started by SD.
"message_sender" is started by CE, one for each server.
> Minor changes in chatcommands.py: Added comments for threads

- REFDOC.md
- chatcommands.py
- metasmoke.py
Implemented new chat commands stat and counter.
- stat: get post scan statistics.
- counter: get metasmoke ping failure counter.
counter is to be distinguished from ms-status.
> chatcommands.py: Implemented new commands stat and counter

- findspam.py
- watched_keywords.txt
[Discussed in CHQ](https://chat.stackexchange.com/transcript/11540?m=54586828#54586828). The reason has its own whitelist for now, until we have unified whitelist-checking.
> Split link-at-beginning watch into new reason

- bad_keywords.txt
vision[\W_]*+20 removed for low accuracy 0.389. Should be moved to watchlist.
> vision[\W_]*+20 removed from blacklist

- chatcommands.py
- test/test_chatcommands.py
The latter is a super set of the former. Doing so may also reduce the work in future maintenance/refactoring/development, as LoC is reduced and there is one less place to search/replace in case there is a change.
> location command redirected to rev

- apigetpost.py
- bodyfetcher.py
- chatcommands.py
- classes/_Post.py
- metasmoke.py
- spamhandling.py
Context: Charcoal-SE/metasmoke#734
This PR implements the Smokey side of stuff. Apparently depends on the deployment of the target MS PR.
---
Changes to filters: Added `body_markdown` for questions and answers where `body` is already selected.
> Send post Markdown from SE API to MS

- CONTRIBUTING.md
- CONTRIBUTING_PULLREQS.md
Due to a small flurry of less-than-useful pull requests with no justification, etc. which in turn require us to go *digging* to actually understand what the pull reqs do, we should more explicitly define our requirements for pull requests including Minimum Requisite Information.
watchlist and blacklist changes are much simpler to review but when we start putting in heavier code changes, functionality, etc. it becomes more necessary to have more details and justifications in the pull request.
This Pull Request is a draft until we get review of language, etc. at which point we'll make it a standard Pull Request.
Anyone with commit access is allowed to revise the branch, which is why I made it under SmokeDetector.
> Revise CONTRIBUTIONS to dictate requirements for Pull Requests, etc.

- watched_keywords.txt
Reverts Charcoal-SE/SmokeDetector#4183
This watch was added through another `!!/watch` command shortly after the PR was created.
> Revert "Sonic the Masked Werehog: Watch ido\.kiwi"

- findspam.py
Running with a too old version of the regex library can cause the test to take an excessively long time and even crash the system
> test/test_findspam.py: fail immediately if regex too old

- chatcommunicate.py
If the command used `sdc` instead of the `!!/` prefix, normalize `message.content` to the `!!/` form.
Split off here from #3884
> chatcommunicate.py: simplify sdc handling

- config.sample
- datahandling.py
- globalvars.py
One of the things that's hampered testing is that it's necessary to connect to MS to get a list of blacklist manager approved users. This has been handled in a few cases by copying a codePrivileges.p file around. That's a bit clunky.
This PR adds 3 new optional values to the config file:
* `se_blacklisters`
* `mse_blacklisters`
* `so_blacklisters`
Each value is a comma separated list of IDs which are to be blacklist manager approved on the respective chat server. If there is an existing list of blacklist managers available from MS, then the IDs are added to it. If there is no list of blacklist managers available from MS (i.e. there's no MS key), then the lists that are provided in the config file by chat server are used alone.
> Add blacklisters to config file for testing

- gitmanager.py
[Once again](https://github.com/Charcoal-SE/SmokeDetector/issues/565), leaked locks cause Smokey to randomly die.
In this case, the `!!/reject` command acquired the gitmanager lock but never released it. This means that when the *next* gitmanager operation attempts to acquire the lock, it deadlocks forever, permanently stalling the calling thread.
Resolves #4291 (or at least one possible cause of the issue).
> [gitmanager] Fix deadlock caused by leak in reject_pull_request

- bodyfetcher.py
The Stack Exchange API allows us to fetch a maximum of 100 posts in one request. Whenever we make a request, if we have less than 100 posts to fetch we fill the extra space with some "Hybrid Intermediate IDs" -- in other words, post IDs interpolated between the highest post IDs we've seen. (For example, if the highest post ID we've seen is 1000, and we suddenly see post 1050, we will pad out our next API request with post IDs in the range 1001-1049).
Well, at least that's the intention. There was an arithmetic error [when calculating the number of intermediate post IDs to include](https://github.com/Charcoal-SE/SmokeDetector/blob/84a139690eceb8a690e4705628446839662d26fa/bodyfetcher.py#L161):
intermediate_posts = intermediate_posts[(100 - len(new_post_ids)):]
This doesn't take the last …
> [bodyfetcher] Fix math error interpolating post IDs 

- bad_keywords.txt
- findspam.py
These do different things than what's in bad keywords. Importantly, they both also have a dramatically different %TP than what we target for bad keywords, which makes it inappropriate for us to be lumping them in with the bad keywords detection.
* "scam aimed at customers in" is [734 Total / 250 TP (34.06% TP) / 426 FP / 69 NAA](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&why_is_regex=1&why=Scam+aimed+at). 34%TP is **way** under what we target seeing for bad keywords.
This PR will move it from under "bad keyword in", where it's wildly under the target %TP, to "potentially bad keyword in". The combination of very low detection volume and mid-level %TP doesn't justify having this as a separate named detection.
Without excluding the duplicate detection with bad keywords (this …
> Split "customer support phrase in {}" and "scam aimed at customers in {}" from bad keywords

- findspam.py
This is sufficiently different from bad keywords such that it should be its own detection.
On MS, this is currently: [2216 Total / 2190 TP (98.83% TP) / 27 FP / 0 NAA](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&why_is_regex=1&why=Health-themed+spam).
> Split Health-themed spam detection from bad keywords

- CONTRIBUTING_PULLREQS.md
Since we're already advocating good code comments and PR descriptions, why not roll in commit messages as well? I often admire Makyen for their detailed commit messages for seemingly simple or straightforward changes, and I see it particularly helpful in the long run, so I want to add that as an option for "description of purpose" in our contributing guidelines.
Plus a grammar fix.
> Advocate good Git commit messages in `CONTRIBUTING_PULLREQS.md`

- chatcommands.py
Display a warning; require -force to override it.
For the record, I have repeatedly submitted commits to remove this character where it had slipped in; most recently, https://github.com/Charcoal-SE/SmokeDetector/commit/7c9aa02d9407dc110a934a44271a586a0c5d92ce
> chatcommands.py: trap U+202D invisible character

- rooms.yml
Hi, 
the Bitcoin folk is not particularly active on the SE chat and we mostly just remove whatever crops up with flags on the site long before we see it in the chat. So, I'd like to stop the smoke detector from posting to the mempool chat (the Bitcoin public chat room, 8089). Hope this PR does that. 
Thank you for your work!
> Stop posting to room 8089 Mempool

- chatcommands.py
Per [Thomas Ward's slight annoyance here](https://chat.stackexchange.com/transcript/message/56600773) ... And [here](https://chat.stackexchange.com/transcript/11540?m=55625359) ... And [here](https://chat.stackexchange.com/transcript/11540?m=55478132) ... and tripleee's [attempt here](https://chat.stackexchange.com/transcript/11540?m=55435758), `accept` seems like a pretty **accept**able alias for `approve`.
Thomas Ward also [mentioned he was going to add this anyway](https://chat.stackexchange.com/transcript/message/56601228), so I figured I would save him the keystrokes. :)
> Add "accept" as an alias for the "approve" command

- .pullapprove.yml
To enable @cigien as blacklister.
Sent invitation to Charcoal team on Github and clicked blacklister on metasmoke account. (In fact, I guess somebody else did the latter already.)
> .pullapprove.yml: add cigien

- chatcommands.py
I recently [accidentally watched an expression with a space at the beginning](https://chat.stackexchange.com/transcript/11540?m=57953326) completely unintentionally, as I was copy-pasting off of a list. In chat, this looks as though everything worked correctly and there is nothing wrong, but there's actually some hidden leading whitespace there.
This isn't the first time I've run into this problem. I've approved #5921 and #5789 ([knowingly](https://chat.stackexchange.com/transcript/message/57130415), I'll add) just to see if they would work, because the watch commands as viewed from chat would lead one to believe it was entered correctly. Naturally, the watches did not catch their intended targets in these instances.
**What this PR does:**
This addition checks for leading white space …
> Check for whitespace at beginning of a watch pattern, requiring -force to continue

- globalvars.py
According to the documentation for `configparser.RawConfigParser` (https://docs.python.org/3/library/configparser.html#configparser.RawConfigParser), this is a **legacy** API call that allows for non-string section names, option names, and values via the unsafe `add_section` and `set` methods.  We don't use those methods, but it's overall still a legacy compatibility and should be avoided.
The documentation suggests that instead of using `RawConfigParser`, we should use `ConfigParser` and set `interpolation=None` at instantiation instead.
> globalvars.py: Use ConfigParser instead of RawConfigParser

- chatcommands.py
Back when we had a discrepancy in DNS results, we were afraid SmokeDetector might be a part of it.  Which is what let ArtOfCode to create the `dig` command, so we could look at DNS results returned by SmokeDetector.
With the recent changes done to SmokeDetector with #6541, we now have the capacity to customize SmokeDetector's DNS settings and configurations.  Which means that having a customizable DNS means we need a mechanism to compare DNS output from SmokeDetector's DNS settings and a reliable DNS server.  In this case, I chose Google DNS as a comparative server for our use to compare against whatever DNS setup is done on SmokeDetector instances, whether system configured DNS or customized DNS with individual SD instances.
> Create DNS comparison command for privileged users.

- findspam.py
Attempt to work around some DNS issues in CI
> findspam.py: tweak up DNS timeout to 60s when running pytest

- chatcommands.py
- chatcommunicate.py
- globalvars.py
- metasmoke.py
This PR does two things which should improve how SD handles SE main being in read-only mode (and some of the ways SE goes down).
1. Login to chat only using stored cookies is added such that SD doesn't require SE main to be in read/write mode in order to continue to use the cookies which SD already has. If logging in fails, SD still falls back to both older methods. If SD ends up falling back to having to log in via username and password, then it still needs SE main to be in read/write mode.  
This should allow SD to communicate in chat after rebooting when SE is in read-only mode.
This is is still a bit brittle, particularly with respect to ditching the stored cookies upon a single failure. Not deleting the cookies upon failure needs some additional testing in various SE failure modes …
> Improve response to SE main downtime

- chatcommands.py
Adds a TLD check for blogspot domains. Tested here: The pattern is a blogspot watch but keeps the TLD, in most cases this should be removed.
> Adds a TLD check for blogspot domains.

- config.sample
- findspam.py
- globalvars.py
This adds an optional "valid_detection_reasons" entry in the config file. When used, only the specified detection rules are run. The entries in the list must exactly match the `reason` which was specified in the detection rule. This is primarily for testing/development. The intent is that it allows testing to focus on a new or changed detection without running all of the other detections on every post.
> Add capability for "valid_detection_reasons" list in the config file

- chatcommunicate.py
Currently, SD just drops any message which is > 500 characters and doesn't have a `\n` in it to make it multi-line. This change just forces adding a `\n` and posts the message as a multi-line chat message. At a minimum, this will let us see the messages, rather than only have them in the console log.
> For chat messages > 500 characters, don't drop, add a newline

- findspam.py
- globalvars.py
Similar to [Add capability for "valid_detection_reasons" list in the config file](https://github.com/Charcoal-SE/SmokeDetector/pull/6771), this PR adds an optional `valid_rule_ids` entry to the config file, which can be used to to restrict the rules used by the SmokeDetector instance. This will be useful for testing. In working on the number detections, I found I needed to be able to target specific rules for enabling, rather than detection reasons, due to there being multiple rules with the `reason` of "potentially bad keyword in {}".
If a rule has a `rule_id`, then it's required to be unique. I haven't gone through and added `rule_id` properties to every rule.
> Add optional "valid_rule_ids" in config, similar to "valid_detection_reasons"

- helpers.py
- requirements.txt
- watched_keywords.txt
* Revert `regex` package version limit.
After investigation, the CI failures which we had upon updating the regex package to 2022.3.15 were cause by the regex package now raising an exception when it encounters a backslash escape which it doesn't understand. This is a change in how the regex package handles such issues. As I understand it, the regex package now supports Python 3.6 as the lowest Python version it's compatible with. The author of the regex packed explained that the `re` regular  expression package was changed in 3.6 to also raise exceptions in such cases. 
* Add compiling each regex as a part of `blacklist_integrity_check()`. This should more clearly identify similar issues in the future and also more clearly identify such issues when the lists are edited through …
> Revert limit to regex package version; Testing: compile watch and blacklist regexes

- chatcommands.py
Previously, the names in the "COFFEE" list were all capitalized, while the names in the "TEAS" list were all lowercase. Grammatically, in the context of SmokeDetector's reply, lowercase is correct, so all names have been converted to lowercase, except where a particular name is a proper noun, in which case, it is correctly rendered in uppercase.
> Correct casing of coffee and tea names to fix grammar in replies

- spamhandling.py
Adds the appropriate mini-Markdown syntax to ensure that the post title is rendered in boldface within the reports posted by SmokeDetector in associated chat rooms. The intention behind this change is to make it easier to identify the link to the post, given strings of indeterminate length and viewports of arbitrary width resulting in wrapping.
Context: https://chat.stackexchange.com/transcript/message/60730004#60730004
> Bold post title in chat report messages

- blacklists.py
- findspam.py
For CI testing of YAML based lists, we get a lot of random CI failures in DNS testing. These appear to go away if retested. It appears that these are caused by a timeout. This increases the timeout from 5s to 15s.
This uses code coped from [this commit](8a8efa80190cf64e82c14d088dab7c0bffdff3d6).
> Increase YAMLParserNS _validate() DNS lookup timeout to 15s during CI testing.

- .circleci/config.yml
- .github/workflows/build.yml
- helpers.py
- requirements.txt
- test/test_blacklists.py
This substantially reduces the amount of time which the CI testing takes in GitHub Actions and CircleCI.
| Which testing | without PR |  with this PR |
|---------------|-------------|--------------|
| GH Actions<br/>Python 3.6 | [6m 7s](https://github.com/Charcoal-SE/SmokeDetector/runs/6294209828?check_suite_focus=true)  | [2m 55s](https://github.com/Charcoal-SE/SmokeDetector/runs/6295148586?check_suite_focus=true) |
| GH Actions<br/>Python 3.10 | [6m 45s](https://github.com/Charcoal-SE/SmokeDetector/runs/6294209884?check_suite_focus=true) | [3m 3s](https://github.com/Charcoal-SE/SmokeDetector/runs/6295148678?check_suite_focus=true) |
| CircleCI<br>Python 3.8 | [5m 51s](https://app.circleci.com/pipelines/github/Charcoal-SE/SmokeDetector/69250/workflows/71f84c9a-d15d-4bd3-a22a-b9f27d6445d8/ …
> Improve CI testing speed

- chatcommunicate.py
When reconnecting using a modified cookie-login method introduced in #6733 , as we're not calling one of the Chat Exchange "client" object's login methods, the Chat Exchange _worker thread doesn't get restarted, and as a result, message deletion is queued up but not performed. This PR explicitly starts that thread back up.
Had a chat with Makyen about this [here](https://chat.stackexchange.com/transcript/message/61152096#61152096), and for future reference, [he mentions](https://chat.stackexchange.com/transcript/message/61152294#61152294) we should probably implement an abbreviated login function into our fork of Chat Exchange that doesn't rely upon Main/Meta sites being up, but that's more of a "Would be nice"/"Implement if you have time" thing.
This resolves issue #6776 and a sub-issue …
> Fix Smokey being able to self-delete messages (poof/delete-force, automated self-deletion, etc.)

- bodyfetcher.py
- chatcommands.py
- datahandling.py
- globalvars.py
- helpers.py
- metasmoke.py
Currently, all of the stats, including the ones for MS, are not kept through rebooting. In addition to substantially expanding the `stats` command, this PR stores the stats across reboots. At a minimum, it will make the stats collected by MS be more accurate.
This PR does the following:
* Creates multiple stats sets which are individually manipulable. The default list of stats sets is "all", "uptime", and "ms". These stat sets are protected from destructive operations unless a `-force` is provided in the command. The "all" set is intended to be all time. The "uptime" set is the default set displayed and is cleared upon reboot. The "ms" stats are the stats being accumulated for MS and are reset upon being sent to MS.
* Effectively, this means people can store a set of stats that starts and …
> Store scan stats and add thread stats in BodyFetcher

- chatcommands.py
- chatcommunicate.py
This PR does:
* Adds `CmdExceptionLongReply()`, which can be used to indicate a chat command didn't succeed, but allow the response text to use Markdown in a reply to the user which is longer than 500 characters. The primary limitation is that such responses can be only a single paragraph, but the paragraph can be long and use Markdown throughout.
* Use `CmdExceptionLongReply()` in some of the exception replies for the `!!/watch/blacklist-number` commands which were both long and attempting to use Markdown formatting.
* Some tweaks to `!!/watch/blacklist-number` command responses which appeared beneficial, based on problems encountered in Charcoal HQ.
* Perform and report the results from the `!!/bisect-number` which some of the responses from `!!/watch/blacklist-number` tell the user …
> Enable Markdown formatting in some longer !!/watch/blacklist-number command replies

- findspam.py
- helpers.py
This adds a helper function `regex_compile_no_cache()` which can be used to compile a `regex` without the regular expression entering the `regex` package's implicit cache, which allows us to do so on a per-compilation basis. Unfortunately, the `regex` package only exposes `regex.cache_all()` and `regex.purge()`. The `regex.cache_all()` method turns the cache on and off globally, which is fine in a single threaded application, but has undesired side effects if used dynamically in an application where there are multiple threads, like SD. We have been using `regex.purge()`, which works, but results in a notable number of regular expressions needing to be recompiled into the implicit cache.
Not putting specific compiled regular expressions into the implicit cache can leave the slots available …
> Allow us to force the regex package to not implicitly cache some regexes at compile time

- chatcommunicate.py
- findspam.py
- test/test_chatcommands.py
- test/test_chatcommunicate.py
- ws.py
In CI testing, we've been getting a notable number of errors in `test/test_chatcommunicate.py` and some other affected tests. These have indicated real thread safety issues in chatcommunicate.py (and some in the tests themselves). This PR is intended to resolve those issues.
In order to resolve the thread safety issues in chatcommunicate.py and resolve some issues in CI testing this PR:
* Adds and uses `threading.RLock()` locks for each of the global values in chatcommunicate.py, or groups of values which are used in similar areas, within chatcommunicate.py.
* Uses those locks in other modules where those modules directly access and/or manipulate the values protected by a lock.
* Adds some decorators to some tests in test_chatcommands.py to store and restore some of the values which are …
> Use threading.RLock() locks for global values in chatcommunicate.py

- findspam.py
This is primarily for debugging and/or monitoring how long individual runs of a `Rule` (detection) takes. Output is to the console and/or into rooms with the "long-rule-times" role (new role).
The general definitions are:
```
('debug', '', 1),  # > 1 s: Log a "debug" level message for the Rule; No chat message
('info', 'High ', 10),  # > 10 s: Log an "info" for the Rule and output to chat as "High "
('warning', '**Very High** ', 30),  # > 30 s: Log a "warning" and output to chat as bold "Very High"
```
Each `Rule` can define its own levels for these outputs, including turning them off. The main watchlist tends to be the rule that takes up the most time. It is currently using:
```
('debug', '', 10),
('info', 'High ', 20),
('warning', '**Very High** ', 45),
```
In order for there to be chat …
> Log and/or post in chat for FindSpam Rules which take more than a defined amount of time

- .circleci/config.yml
- .github/workflows/build.yml
Upon additional testing, it was seen that there needed to be more done in each CI run in order to make sure that a cache of the venv stayed at the most recent versions of our sub-dependencies without exceeding the versions required for our explicit requirements. The extra steps are required because `pip` doesn't update sub-dependencies of explicitly specified dependencies, unless required. Doing the extra steps cost enough time such that using a venv is, at best, neutral with respect to the amount of time required for installing all of the requirements from cached copies of the package downloads. In multiple cases, using the cached venv actually took longer. The entire point of using a venv in our CI was that fully caching the installed dependencies resulted in a savings in the run time …
> CI: Don't use a venv for either GitHub Actions or CircleCI

- blacklists.py
- helpers.py
This changes the CI validation of the "*_nses.yml" files to run the validations in parallel, rather than fully serial. The validation of these files is the longest running CI test, by a considerable margin, so tends to dominate how long it takes to perform CI testing. The changes in this PR use `concurrent.futures` to run 20 validations in parallel. While this doesn't actually reduce the time by a factor of 20, it significantly reduces it. How much it reduces the overall test time depends on how long it takes to get DNS responses for each entries/domain and the sequence of domains which are validated in each thread. While the test remains as the longest single test, it is substantially reduced and is intended to be run in parallel with the CPU intensive tests (already allocated within the …
> CI: Run NS validations in parallel. Shows all errors, not just first.

- .github/workflows/build.yml
- ws.py
Python 3.6 reached end of life more than six months ago on 2021-12-23. We don't have a reason to be supporting Python 3.6, as all currently used SD instances are on at least Python 3.7. While I'm not aware of anything currently in the code which doesn't work with 3.6, I have recently chosen to use less current solutions in order to maintain 3.6 compatibility.
* Moves our GitHub Actions CI testing from Python 3.6 to Python 3.7.
* Adjusts the text which we display when SD runs on a Python version which is above the minimum we know to be required (3.6), but less than the version we're testing on at the time this PR was posted (3.7.13).  So, effectively, we'll log a warning if SD is running on 3.7.13 > Python version > 3.6.0.
That warning currently is:
> SmokeDetector is tested on the latest …
> Move GitHub Actions testing to Python 3.7

- chatcommands.py
- chatcommunicate.py
- datahandling.py
This gets `!!/dump-data` and `!!/load-data` working. It includes the following changes:
* Allow specifying the chat domain, rather than requiring the dump room to be on chat.SE.
* Use pickle `protocol=4` in order to maintain compatibility with Python 3.7
* Implement `is_self()` in chatcommunicate.py to verify that the message being loaded is from the same user.
* Add a `!!/load-data-force` version which ignores the check for the message being from the same user.
> Get !!/dump-data and !!/load-data working

- bodyfetcher.py
- chatcommands.py
- ws.py
* Limits the number of BodyFetcher scan threads to one more than the number of available CPUs.
* Includes logging and reporting into chat when this prevents launching a new scan for more than 3 minutes.
* Limits the number of threads which a single site can consume to one less than the available number of threads, if the available number of threads is more than 2 (i.e. more than a single CPU).
* Improves robustness of releasing the `per_site_processing_thread_locks` semaphore under some possible error conditions
* Fixes a bug in choosing to pre-scan the `155-questions-active` WebSocket data. The logic was effectively inverted, causing SD to pre-scan when it really should have been skipped.
The primary existing limit is not to launch a new scan thread when the system CPU usage is too high. …
> Limit BodyFetcher scan threads to # CPUs +1

- findspam.py
- helpers.py
This PR prevents `<img>` elements within `<code></code>` from being considered as "images" when determining if the post is "mostly images". A [search on MS for posts detected by "post is mostly images" and which contain any `<code>`  in the body](https://metasmoke.erwaysoftware.com/search?body=%3Ccode&body_is_regex=1&reason=174) shows that this detection is 225 Total / 1 TP (0.44% TP) / 223 FP / 4 NAA if code even exists in the post. If [the `<img>` is within the code](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=%3Cimg+%28%3F%3D%28%3F%3A%5B%5E%3C%5D%7C%3C%28%3F%21%5C%2F%3Fcode%3E%29%29*%2B%3C%5C%2Fcode%3E%29&reason=174), it's 199 Total / 1 TP (0.5% TP) / 197 FP / 4 NAA.
The [1 TP](https://metasmoke.erwaysoftware.com/post/282663) would have still been …
> Don't detect images in code in "post is mostly images"

- chatcommands.py
- chatcommunicate.py
- datahandling.py
- gitmanager.py
- helpers.py
- metasmoke.py
- ws.py
This started out with just intending to add some additional debug logging of exception in the chat init sequence in order to be able to get a better idea of what was happening during that process when SE was down. However, prior to that, I made changes to the logging helper functions, `log()`, `log_exception()`, and `log_current_exception()` to have more descriptive argument names, more consistency, etc.
This PR does:
* More consistent argument name `level` -> `log_level` in `log_exception` and `log_current_exception()` to match `log()`
* More descriptive argument name in all three functions `f`->`and_file` to indicate the log is also being recorded in a file.
* Add ability to specify `log_level` and `and_file` for log_current_exception()`
* Use `log_current_exception()` for …
> More uniform exception logging helpers

- findspam.py
- test/test_findspam.py
This reduces the FP rate of "Phone number detected in title".
The baseline prior to this change is [7211 Total / 6406 TP (88.84% TP) / 803 FP / 1 NAA](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&reason=47).
This change excludes [448 Total / 7 TP (1.56% TP) / 440 FP / 1 NAA](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title_is_regex=1&title=%28%3Fs%29%5E%28%3F%3A%28%3F%23%5Cn%0D%0A+%29%28%3F%3D%28%3F%23various+text+which+tends+to+be+FP%2C+but+is+used+by+some+spammers%29%28%3F%21%28%3F%23Don%27t+match+in+combination+with+some+words%29.*%3F%28%3F%3Aquick%5B%5CW_%5D*%2Bbooks%3F%7Cbinance%7Csupport%7Chelp%28%3F%3Aline%7Cdesk%29%7C%5Cbcall%5Cb%7Cantivirus%7Ccustomer%7Cwhatsapp%3F%29%29.*%3F%28%3F%3Aerrors%3F%5Cb%7C%28%3F%23list+of+words%2Fphrases+which+tend+to+indicat …
> Reduce FP by 440+ in "phone number detected in title" by adding a second exclude regex

- blacklists.py
- helpers.py
The intent of this change is to prevent CI testing from failing due to intermittent DNS resolution issues. While we already do a second pass, it doesn't seem to resolve the issues we're seeing on particular domains. This collects the entries which failed the first round of testing and re-tests all of the failures (many/most will have already been tested twice, so this is a third and fourth attempt, but delayed).
In addition, with the prior code we don't have easy access to the entry which is is failing. With this change, the failing entries are collected into a list in both a first and second pass. If we continue to have issues with a specific domain that isn't actually a failure and something we want to remove from then list, then we can just exclude it from being reported as an error in …
> Add a second verification pass for initial NS verification failures

- globalvars.py
- metasmoke.py
This PR adds an optional `additional_failover_text` entry to SD's config file, which allows additional per-instance text to be added to the chat message the instance posts upon receiving a "failover" from MS.
The issue that this is attempting to address is that we have had several times recently where MS has sent a `failover` to Makyen/EC2-linux when Osiris was actually still operational. The chat notification of the failover and restarting text has gone generally unnoticed until the fact that there are two active instances running causes some secondary issue. This is intended to allow me to have text specific to Makyen/EC2-linux which calls more attention to the fact that there's been a failover, in order to make it more likely that the situation is evaluated and addressed by a human.
> Add optional "additional_failover_text" entry in SD's config file.

- chatcommunicate.py
This removes the feature of SD forwarding chat messages which are not direct replies to reports to MS as comments.
> Don't forward non-reply chat messages to MS as comments

- chatcommunicate.py
A reply to a report is not forwarded to MS as a comment if the reply satisfies all of the following:
* Matches `r'(?i)\bstill[\W_]+(?:alive|up)\b'`
* Has a length less than 100 characters once all links to the domains `(?:erwaysoftware\.com|stackexchange\.com|stackoverflow\.com|serverfault\.com|superuser\.com|askubuntu\.com|stackapps\.com|mathoverflow\.net)` have been removed
This resolves #6786.
> Prevent forwarding short "still alive" messages as MS comments

- chatcommunicate.py
This is needed in order to minimally comply with the CC BY SA license under which all chat messages are posted. It includes a link to both the chat message and the user account which posted the chat message. It should actually be a bit more involved, but this is a good first step.
The attribution looks like:
> This is a test of a reply 008 &ndash; from a [chat message](https://chat.stackexchange.com/transcript/message/61829040) by [Makyen](https://chat.stackexchange.com/users/156050/Makyen)
We probably should also add inline attribution for other types of comments which are forwarded to MS, but those are more clearly intended by the user to be included in reports (e.g. the comment at the end of a `!!/report`).
> Add inline attribution for chat replies which are forwarded to MS as comments

- chatcommands.py
- gitmanager.py
- test/test_chatcommands.py
Tl;dr when someone does `!!/watch` during CI testing it will ping them instead of just saying that it reloaded the watchlist. This PR explains what is happening (it will be added once the current CI testing is done), so it is clear what is happening
Context is [in the transcript](https://chat.stackexchange.com/transcript/message/61892018#61892018), phrasing suggested by @codygray.
TODO:
The spot in the code is here:
https://github.com/Charcoal-SE/SmokeDetector/blob/master/gitmanager.py#L260-L263
Do we also need to adjust that message for blacklisting? I suspect yes, but I should check that as well
> Improve message for watch during ongoing CI testing

- .github/workflows/build.yml
- requirements.txt
This PR makes a few changes to CI testing with GitHub Actions:
* Moves our "current" Python version testing from 3.10 to 3.11, due to recent release of Python 3.11.  
As an interesting note: testing on CircleCI (which this PR doesn't change) indicates a notable speedup on CircleCI testing when moving from Python 3.8 ([average of 5 runs 2m53s](https://app.circleci.com/pipelines/github/makyen/Charcoal-SE-SmokeDetector/3033)) to Python 3.11 ([average of 6 runs 2m 12s](https://app.circleci.com/pipelines/github/makyen/Charcoal-SE-SmokeDetector/3034), which is about a 24% improvement). Testing was on CircleCI merely because it's easier to see multiple runs on the same `git` commit.
* Updates to `actions/setup-python@v4` and `actions/cache@v3` from v3 and v2 respectively. We were seeing …
> Update GitHub Actions: Python 3.11, setup-python@v4, cache@v3, unlock coverage

- apigetpost.py
- bodyfetcher.py
- chatcommands.py
- datahandling.py
- deletionwatcher.py
- findspam.py
- gitmanager.py
- globalvars.py
- helpers.py
This PR does:
* Moves our use of the SE API to version 2.4 in order to support the Staging Ground on SO
* Adds 60 second timeouts to all `requests` accesses
* The exact timeout used may need to be adjusted based on any issues we see in use. Splitting between what's used for the SE API and each of the other things for which we make requests (e.g. SE API, Perspective API, GitHub API) may be desirable, but is not implemented at this time.
* Not having a timeout on all of our accesses may be what have caused some of the hangs we've seen over time, particularly for chat commands. ChatExchange already had a timeout for all accesses, but what we were doing in response to commands didn't in various cases.
* Use `with` semantics for `GlobalVars.api_request_lock`   
There were cases where the lock …
> Move to SE API 2.4 to support Staging Ground; add request timeouts

- watched_keywords.txt
Drops out 2 FPs; everything else remains the same.
> Tweak "top|best in 20xx" watch to exclude trailing `[\W_]*ms`.

- .circleci/config.yml
- .github/workflows/build.yml
- requirements.txt
This PR adds pytest-timeout and sets a per-test timeout of 300 seconds. This will have the following effects:
1. We won't have a, potentially, hours-long span of time where there are multiple CI tests running, which will all eventually fail, but which aren't reported into Charcoal HQ until the first one actually fails. In other words, we'll see that the CI tests failed much sooner.
2. We won't have as good information as to what exactly failed, other than that a test exceeded the timeout. What and how much information we get is going to depend on the test (most likely one of the `bisect` tests that are intended to identify poorly performing watches/blacklists) and the exact way that it failed. This will make finding the exact problem a bit more difficult, but the problem is highly likely …
> Add pytest-timeout and set 300 second per-test timeout

- blacklisted_websites.txt
- watched_keywords.txt
generalized most of the blogspot regexes in blacklisted_websites.txt; this resulted in some duplication with older entries in watched_keywords.txt, so this PR removes those older entries.
I don't know why the preview here doesn't show `everything4comp\.blogspot` remaining in blacklisted_websites; maybe because it was previously duplicated with my regex change?
> blogspot regex updates for blacklisted_websites.txt along with corresponding removals from watched_keywords.txt

- watched_nses.yml
nccloud.shop. is now a dead NS, NXDOMAINs.  Remove to allow testing to work again.
> Update watched_nses.yml: Remove nccloud.shop NS - NXDOMAIN

- findspam.py
https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&why_is_regex=1&why=Obfuscated+word+in+%5Cw%2B+-+%22who%27re%22 is massively FP, and the hits where it's not FP are coincidental, and usually also trigger other rules
> findspam.py: obfuscated_words: prevent FP on contraction of "who are"

- bodyfetcher.py
- chatcommands.py
- chatcommunicate.py
- findspam.py
- gitmanager.py
- helpers.py
- phone_numbers.py
This started out when I saw https://chat.stackexchange.com/transcript/11540?m=65513403#65513403 with the wording "Added MZ80T1 to watchlist However, the blacklists..." and so I wanted to add the missing period to that reply. That turned into scanning for a couple other missing periods, and then I ran the comments through `aspell` and piled those in as well.
> A collection of typo fixes in comments and ending periods in chat replies

- chatcommands.py
We used to store these icons behind a camo.githubusercontent.com link, but attempting to access that link throws a 403 now.
Example PR comment where the image is no longer visible: https://github.com/Charcoal-SE/SmokeDetector/pull/11282#issuecomment-2127452764
The source for these images is from https://shields.io/ 's [static badge](https://shields.io/badges/static-badge) generator. It has an API that this PR uses to generate and return a specified label with a given style.
We just need a simple green/red coloring for the "blacklisters|approved" and  "blacklisters|rejected" actions we perform, and the URL for that is very simple.
Here's how these two URLs will be rendered in a comment:
Where the markdown is `![Approved with SmokeyApprove](https://img.shields.io/badge/blacklisters-approved- …
> Restore the blacklisters-approved/rejected icons in PR comments

- deletionwatcher.py
- editwatcher.py
- globalvars.py
- helpers.py
- ws.py
* Recover from DeletionWatcher and EditWatcher SE WebSocket exceptions
* For the main SE WebSocket, EditWatcher, and DeletionWatcher, uniformly report SE WebSocket recovery into chat debug rooms, including seconds since the connection was made and seconds from last heartbeat.
* Add timeouts for SE WebSockets: 7 minutes (420 seconds). Normal operation is that SE sends a heartbeat every 5 minutes, so we should timeout shortly after that.
* Resolves #7043
* Fixes a bug in DeletionWatcher where expiration was always based upon post `creation_date`, rather than using `last_edit_date`, if it exists.
Testing for this begins [here](https://chat.stackexchange.com/transcript/message/65811005#65811005).
> SE WebSockets: timeouts, exception recovery, and reporting into chat

- chatcommands.py
- findspam.py
- helpers.py
This PR:
* Consolidates construction of watch and blacklist style regexes, both bookended and non-bookended, into helpers.py with the following additions:
* `KEYWORD_BOOKENDING_START`
* `KEYWORD_BOOKENDING_END`
* `KEYWORD_NON_BOOKENDING_START`
* `KEYWORD_NON_BOOKENDING_END`
* `keyword_bookend_regex_text(regex_text)`
* `get_bookended_keyword_regex_text_from_entries(entries)`
* `keyword_non_bookend_regex_text(regex_text)`
* `get_non_bookended_keyword_regex_text_from_entries(entries)`
This part of the changes is largely a DRY issue, allowing more consistent regexes and making further changes easier.
* Use the above helpers in findspam.py (watch and blacklists, along with various other detections) and chatcommands.py (`!!/bisect`)
* Change the start of bookending from …
> Use (*PRUNE) in bookended regexes to reduce overall CPU usage by 34%

- deletionwatcher.py
- editwatcher.py
- globalvars.py
- helpers.py
This fixes a few/several issues in EditWatcher and DeletionWatcher:
* EditWatcher and DeletionWatcher weren't actually rewatching the questions they were watching when those WebSocket was "recovered". This was a bug I introduced when going a bit too far with DRY in that code. Basically, they were both attempting to resubscribe to their `self.socket` WebSocket prior to the new WebSocket reference being stored in `self.socket`
* More aggressively unsubscribe to questions in EditWatcher. Questions were previously unsubscribed only if there was something received about that question after the time expired. Now, all expired questions are unsubscribed upon each receipt of a message. This keeps the total number of questions subscribed to from expanding throughout the time between reboots.
* …
> EditWatcher and DeletionWatcher bug fixes

- watched_asns.yml
Currently at [61/234/5](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&why_is_regex=1&why=ASN+46475). There are many FPs from [`proguard-rules.pro`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&why_is_regex=1&why=proguard-rules%5C.pro), [`pyautogui.click`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&why_is_regex=1&why=pyautogui%5C.click),  [`biblehub.com`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&why_is_regex=1&why=biblehub%5C.com) , and there aren't any 1-weight reports since this ASN was watched.
> Unwatch ASN 46475

- watched_cidrs.yml
[No TP since watch](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&why_is_regex=1&why=104%5C.21%5C.22%5C.135), all FPs due to [`gradle-wrapper.properties`](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&why_is_regex=1&why=gradle-wrapper%5C.properties) (which apparently resolves o_O).
> Unwatch IP pair 104.21.22.135 + 172.67.205.25

- README.md
Image moved from imgur to sstatic.net; Github no longer renders the old link correctly.
> README.md: fix broken image link

- chatcommands.py
- gitmanager.py
This is #11285 but with a less messy commit history (and a small regex adjustment).
I'd have done rebase-foo on THAT PR instead, but my Git wizardry is... Novitiate. That's a word, right?
---
Implements feature request #8642
This PR allows users to reject/close (including `-force`) their own auto-created watch and blacklist PRs.
This was tested in [this chatroom](https://chat.stackexchange.com/transcript/message/65699938#65699938) (where I removed SD ignoring its own messages when considering them for commands and some other changes, the full diff of which is available [here](https://github.com/Charcoal-SE/SmokeDetector/pull/11285/commits/d3993d17b832c66085ef56a5cd063cf09dd07ff1) where I mistakenly committed them to this branch and had to remove them).
One small change I made was making …
> Allow users to reject their own watch/blacklist PRs (v2: Now with cleaner commit history!)

- chatcommunicate.py
This adds the ability to override the users.yml file with a users_custom.yml file for testing. The feature needed for running test instances that was missing is the ability for the runner of the test instance to give a user SD privileges without changing users.yml from the text that's stored in the GitHub repository. This PR resolves that problem by adding the ability to have a users_custom.yml file that is conceptually similar to rooms_custom.yml.
> Add ability to have users_custom.yml

- blacklists.py
- test/test_blacklists.py
test/test_blacklists.py: restore case-insensitive duplicate test case
Changed the code to raise KeyError in this scenario, so the related test cases had to be updated.
> blacklists.py: normalize items when comparing for duplicates

- watched_nses.yml
The most recent builds (e.g. https://github.com/Charcoal-SE/SmokeDetector/actions/runs/11093250846/job/30819305773) are failing with:
```
FAILED test/test_blacklists.py::test_yaml_nses@long_runner_1 - Exception: 1 entry failed to validate in watched_nses.yml
cloudserverdns.co.in. in watched_nses.yml for dns.resolver.NXDOMAIN
```
This change comments out the entry in watched_nses.yml.
> Update watched_nses.yml: comment out cloudserverdns.co.in (NXDOMAIN)

- findspam.py
This prevents the blacklist and watchlist regexes from being recompiled upon the blacklists being reloaded when the source text for the regex hasn't changed. Currently, all of the blacklist and watchlist regexes are recompiled each time the blacklists are reloaded (i.e., for each and every `!!/watch*` and `!!/blacklist-*` command). That costs quite a bit of computing time, currently looks like about 12 seconds each time, which is expended, even when a particular list didn't change. This cost is, potentially, significantly higher, because the compilation of each regex might be done multiple times, once per thread/CPU, due to the thread concurrently needing the compiled regex and starting the compilation.
There's a lot more that can be done in this area to reduce the amount of redundant …
> Prevent recompiling the BL/WL regexes which are unchanged by a blacklists reloaded event.

- deletionwatcher.py
- globalvars.py
This PR does:
1. Prevents crashing SD when the response to `DeletionWatcher`'s SE API requests isn't valid JSON. This should resolve the issue that caused all of our SD instances to go offline during the spam wave.
2. BUG FIX: not truncate the number of posts per site to 10 upon reboot. This was happening because the `pagesize` was left as the default 10, even when more posts were requested. Thus, only data from the first 10 would be returned. This was solved by adding a default `pagesize` parameter of `100` to all SE API requests globally. For places where we specifically set that value, those will override the default.
3. BUG FIX: Handle sites with > 100 posts being watched by `DeletionWatcher`. That > 100 posts/site wasn't accounted for was the underlying cause of the crash.
4. BUG …
> DeletionWatcher: fix crashing issue; handle sites with > 100 posts; don't truncate sites to 10 posts upon reboot

- deletionwatcher.py
This PR resolves 
* #11539, and 
* #11540.
It also simplifies the process of loading the `DeletionWatcher` pickle, eliminating the need to make SE API requests for data about each of the posts being watched upon reboot.
In order to support the changes, the format of the `DeletionWatcher` pickle has been changed, but backward compatibility with pickles stored in the original format is maintained. Given that all of the data in the pickle becomes outdated after a couple of hours, the code for compatibility can be removed a few hours or days after this is merged and used in production.
Testing for this starts [here](https://chat.stackexchange.com/transcript/message/66520491#66520491).
> DeletionWatcher BUGFIX: Watch more than 1 post/question; Re-watch answers on reboot

- watched_nses.yml
quickflyllc.com has disappeared again; this PR disables it; resolves recent build failures, e.g. https://github.com/Charcoal-SE/SmokeDetector/actions/runs/11987444005/job/33421614923 and https://github.com/Charcoal-SE/SmokeDetector/actions/runs/11987444005/job/33421615033
> Update watched_nses.yml - disable quickflyllc.com (NXDOMAIN)

- watched_nses.yml
Resolves recent build failures based on cloudxspeed.com being NXDOMAIN again.
MX Toolbox result: https://mxtoolbox.com/SuperTool.aspx?action=mx%3acloudxspeed.com&run=toolpage
e.g.  https://github.com/Charcoal-SE/SmokeDetector/actions/runs/11996884075/job/33441859183 and https://github.com/Charcoal-SE/SmokeDetector/actions/runs/11996884075/job/33441859292
> Update watched_nses.yml - re-disable cloudxspeed.com

- blacklisted_nses.yml
my-wifiextnet.net is giving NXDOMAIN in recent builds, starting about 5 hours ago: https://github.com/Charcoal-SE/SmokeDetector/actions/runs/12291041507/job/34299163415 through: https://github.com/Charcoal-SE/SmokeDetector/actions/runs/12295763473/job/34313312748
> Update blacklisted_nses.yml - comment out my-wifiextnet.net again

- watched_nses.yml
https://github.com/Charcoal-SE/SmokeDetector/actions/runs/12582691045/job/35068797142 and several previous runs had failures on this entry:
> FAILED test/test_blacklists.py::test_yaml_nses@long_runner_1 - Exception: 1 entry failed to validate in watched_nses.yml
matkaparivar.in. in watched_nses.yml for dns.resolver.NXDOMAIN
> re-disable matkaparivar.in in watched_nses.yml

- watched_nses.yml
nccloud.shop has been triggering CI failures of "dns.resolver.NXDOMAIN" this morning: https://github.com/Charcoal-SE/SmokeDetector/actions/runs/13088726918/job/36522944474 and https://github.com/Charcoal-SE/SmokeDetector/actions/runs/13088521908/job/36522532569 for two examples.
> Update watched_nses.yml: re-disable nccloud.shop

- watched_nses.yml
askbeen.com has been giving NXDOMAIN in the recent builds; this disables it yet again.
> Update watched_nses.yml - re-disable ns entry askbeen.com.

- findspam.py
https://stackexchange.com/search?q=url%3A%22sciencedirect.com%22 gives 16450 results, and we have 121 FPs now (against 8 TPs, probably not many of them because of the link to that domain), so it makes sense to whitelist this domain. I am not sure *where* exactly to put it into the whitelist though ...
> add sciencedirect.com to ASN whitelist

- watched_nses.yml
hostnac.com has been causing build errors for about the past 10 hours, starting with: https://github.com/Charcoal-SE/SmokeDetector/actions/runs/14901618248 and as recently as: https://github.com/Charcoal-SE/SmokeDetector/actions/runs/14912838315/job/41891197554; this comments out the entry.
> Update watched_nses.yml - disable hostnac.com (NXDOMAIN)

- chatcommunicate.py
In `chatcommunicate.on_msg()`, if an `HTTPError` is encountered checking the `parent` of the message (the message that was being replied to), it's caught and logged, but not re-raised. Without this, the exception was immediately crashing SmokeDetector, forcing a restart. 
Avoids unnecessary crashes and restarts. In particular, avoids a vicious circle of unnecessary crashes and restarts.
Stack Exchange often refuses the requests in this part of the code with 403 errors. While a better fix would be for Stack Exchange to *not* do that, this patch makes SmokeDetector more resilient to the errors: instead of crashing and restarting the entire instance, it simply stops trying to figure out what the message was replying to, and goes on with the rest of its business.
Tried to do that.
Very short …
> chatcommunicate.on_msg(): don't crash on HTTPErrors when checking reply parent

- chatcommunicate.py
- test/test_chatcommunicate.py
This expands on PR #14794, preventing SD from attempting to get data for the reply parent when the message being replied to is not from the user under which SD is running. In addition, a reply is sent to chat upon the HTTP errors we're logging and ignoring. This should result in both the user being informed that what they wanted to happen didn't occur, but also result in a further exception if we're blocked from posting, which would mean rebooting is probably a good idea.
> Prevent trying to fetch reply parent data for replies not to SD

- watched_nses.yml
quickfix8.com is returning NXDOMAIN due to a client hold. The current NS of quickwebsitefix.com are under quickfix20.com, and had previously been under quickfix8.com. So I disabled quickfix8.com with a comment and added quickfix20.com to watched_nses.yaml.
> watched_nses.yml: disable quickfix8.com, add quickfix20.com

- chatcommunicate.py
- test/test_chatcommunicate.py
With the September 2025 chat UI changes, SmokeDetector stopped responding to replies. This appears to have been due to two changes in the UI:
- the initial "@ UserName" has been moved into the `<a><span>` which has the reply arrow
- the class name of this anchor has been changed from `reply-info` to `reply-info-container`.
@balpha's [PR 186 on upstream ChatExchange](https://github.com/Manishearth/ChatExchange/pull/186), when cherry-picked onto [our fork](https://github.com/Charcoal-SE/ChatExchange), fixes the loading of the reply info.
However, the code in `chatcommunicate.on_msg()` had been relying on the "@ UserName" string to compare with the username SmokeDetector is being run under. That string is now being stripped out of the message `content` somewhere. But it's present in …
> chatcommunicate.on_msg: check ChatExchange parent_username instead of @
